[fx]
providers = [ "frankfurter" ]
cooldown = "10m"
cache_ttl = "6h"

[symbols]
providers = [ "openfigi" ]
cooldown = "10m"
cache_ttl = "12h"

[equity]
provider = "consorsbank"
cache_ttl = "5m"

[alphavantage]
base_url = "https://www.alphavantage.co/query/"
api_key = ""

[consorsbank]
address = "localhost:40443"
skip_verify = false
ca_file = "root.pem"
secret = ""
preferred_currency = ""
preferred_exchanges = [ "TRG" ]

[frankfurter]
base_url = "https://api.frankfurter.dev/v2/"

[openfigi]
base_url = "https://api.openfigi.com/v3"
api_key = ""

[twelvedata]
api_key = ""

[cache]
type = "memory"

[cache.memory]

[cache.redis]
address = "localhost:6379"
password = ""
db = 0
