//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CommonSearchMappingRequestOptionType.
const (
	CommonSearchMappingRequestOptionTypeCall CommonSearchMappingRequestOptionType = "Call"
	CommonSearchMappingRequestOptionTypePut  CommonSearchMappingRequestOptionType = "Put"
)

// Valid indicates whether the value is a known member of the CommonSearchMappingRequestOptionType enum.
func (e CommonSearchMappingRequestOptionType) Valid() bool {
	switch e {
	case CommonSearchMappingRequestOptionTypeCall:
		return true
	case CommonSearchMappingRequestOptionTypePut:
		return true
	default:
		return false
	}
}

// Defines values for MappingJobIdType.
const (
	BASETICKER                MappingJobIdType = "BASE_TICKER"
	COMPOSITEIDBBGLOBAL       MappingJobIdType = "COMPOSITE_ID_BB_GLOBAL"
	IDBB                      MappingJobIdType = "ID_BB"
	IDBBGLOBAL                MappingJobIdType = "ID_BB_GLOBAL"
	IDBBGLOBALSHARECLASSLEVEL MappingJobIdType = "ID_BB_GLOBAL_SHARE_CLASS_LEVEL"
	IDBBSECNUMDES             MappingJobIdType = "ID_BB_SEC_NUM_DES"
	IDBBUNIQUE                MappingJobIdType = "ID_BB_UNIQUE"
	IDCINS                    MappingJobIdType = "ID_CINS"
	IDCOMMON                  MappingJobIdType = "ID_COMMON"
	IDCUSIP                   MappingJobIdType = "ID_CUSIP"
	IDCUSIP8CHR               MappingJobIdType = "ID_CUSIP_8_CHR"
	IDEXCHSYMBOL              MappingJobIdType = "ID_EXCH_SYMBOL"
	IDFULLEXCHANGESYMBOL      MappingJobIdType = "ID_FULL_EXCHANGE_SYMBOL"
	IDISIN                    MappingJobIdType = "ID_ISIN"
	IDITALY                   MappingJobIdType = "ID_ITALY"
	IDSEDOL                   MappingJobIdType = "ID_SEDOL"
	IDSHORTCODE               MappingJobIdType = "ID_SHORT_CODE"
	IDWERTPAPIER              MappingJobIdType = "ID_WERTPAPIER"
	OCCSYMBOL                 MappingJobIdType = "OCC_SYMBOL"
	OPRASYMBOL                MappingJobIdType = "OPRA_SYMBOL"
	TICKER                    MappingJobIdType = "TICKER"
	TRADINGSYSTEMIDENTIFIER   MappingJobIdType = "TRADING_SYSTEM_IDENTIFIER"
	UNIQUEIDFUTOPT            MappingJobIdType = "UNIQUE_ID_FUT_OPT"
	VENDORINDEXCODE           MappingJobIdType = "VENDOR_INDEX_CODE"
)

// Valid indicates whether the value is a known member of the MappingJobIdType enum.
func (e MappingJobIdType) Valid() bool {
	switch e {
	case BASETICKER:
		return true
	case COMPOSITEIDBBGLOBAL:
		return true
	case IDBB:
		return true
	case IDBBGLOBAL:
		return true
	case IDBBGLOBALSHARECLASSLEVEL:
		return true
	case IDBBSECNUMDES:
		return true
	case IDBBUNIQUE:
		return true
	case IDCINS:
		return true
	case IDCOMMON:
		return true
	case IDCUSIP:
		return true
	case IDCUSIP8CHR:
		return true
	case IDEXCHSYMBOL:
		return true
	case IDFULLEXCHANGESYMBOL:
		return true
	case IDISIN:
		return true
	case IDITALY:
		return true
	case IDSEDOL:
		return true
	case IDSHORTCODE:
		return true
	case IDWERTPAPIER:
		return true
	case OCCSYMBOL:
		return true
	case OPRASYMBOL:
		return true
	case TICKER:
		return true
	case TRADINGSYSTEMIDENTIFIER:
		return true
	case UNIQUEIDFUTOPT:
		return true
	case VENDORINDEXCODE:
		return true
	default:
		return false
	}
}

// Defines values for MappingJobOptionType.
const (
	MappingJobOptionTypeCall MappingJobOptionType = "Call"
	MappingJobOptionTypePut  MappingJobOptionType = "Put"
)

// Valid indicates whether the value is a known member of the MappingJobOptionType enum.
func (e MappingJobOptionType) Valid() bool {
	switch e {
	case MappingJobOptionTypeCall:
		return true
	case MappingJobOptionTypePut:
		return true
	default:
		return false
	}
}

// Defines values for SearchRequestOptionType.
const (
	SearchRequestOptionTypeCall SearchRequestOptionType = "Call"
	SearchRequestOptionTypePut  SearchRequestOptionType = "Put"
)

// Valid indicates whether the value is a known member of the SearchRequestOptionType enum.
func (e SearchRequestOptionType) Valid() bool {
	switch e {
	case SearchRequestOptionTypeCall:
		return true
	case SearchRequestOptionTypePut:
		return true
	default:
		return false
	}
}

// Defines values for StateCode.
const (
	AB StateCode = "AB"
	AC StateCode = "AC"
	AH StateCode = "AH"
	AK StateCode = "AK"
	AL StateCode = "AL"
	AM StateCode = "AM"
	AR StateCode = "AR"
	AS StateCode = "AS"
	AT StateCode = "AT"
	AZ StateCode = "AZ"
	BC StateCode = "BC"
	BJ StateCode = "BJ"
	CA StateCode = "CA"
	CB StateCode = "CB"
	CO StateCode = "CO"
	CQ StateCode = "CQ"
	CT StateCode = "CT"
	CZ StateCode = "CZ"
	DC StateCode = "DC"
	DE StateCode = "DE"
	EH StateCode = "EH"
	FH StateCode = "FH"
	FI StateCode = "FI"
	FJ StateCode = "FJ"
	FL StateCode = "FL"
	FO StateCode = "FO"
	FS StateCode = "FS"
	GA StateCode = "GA"
	GD StateCode = "GD"
	GF StateCode = "GF"
	GM StateCode = "GM"
	GS StateCode = "GS"
	GU StateCode = "GU"
	GX StateCode = "GX"
	GZ StateCode = "GZ"
	HA StateCode = "HA"
	HB StateCode = "HB"
	HE StateCode = "HE"
	HG StateCode = "HG"
	HI StateCode = "HI"
	HL StateCode = "HL"
	HN StateCode = "HN"
	HO StateCode = "HO"
	HS StateCode = "HS"
	IA StateCode = "IA"
	ID StateCode = "ID"
	IG StateCode = "IG"
	IK StateCode = "IK"
	IL StateCode = "IL"
	IN StateCode = "IN"
	IT StateCode = "IT"
	JL StateCode = "JL"
	JS StateCode = "JS"
	JX StateCode = "JX"
	KA StateCode = "KA"
	KC StateCode = "KC"
	KN StateCode = "KN"
	KO StateCode = "KO"
	KS StateCode = "KS"
	KT StateCode = "KT"
	KU StateCode = "KU"
	KY StateCode = "KY"
	LA StateCode = "LA"
	LN StateCode = "LN"
	MA StateCode = "MA"
	MB StateCode = "MB"
	MD StateCode = "MD"
	ME StateCode = "ME"
	MG StateCode = "MG"
	MI StateCode = "MI"
	MN StateCode = "MN"
	MO StateCode = "MO"
	MS StateCode = "MS"
	MT StateCode = "MT"
	MZ StateCode = "MZ"
	NB StateCode = "NB"
	NC StateCode = "NC"
	ND StateCode = "ND"
	NE StateCode = "NE"
	NG StateCode = "NG"
	NH StateCode = "NH"
	NJ StateCode = "NJ"
	NL StateCode = "NL"
	NM StateCode = "NM"
	NN StateCode = "NN"
	NR StateCode = "NR"
	NS StateCode = "NS"
	NT StateCode = "NT"
	NU StateCode = "NU"
	NV StateCode = "NV"
	NW StateCode = "NW"
	NX StateCode = "NX"
	NY StateCode = "NY"
	OH StateCode = "OH"
	OK StateCode = "OK"
	ON StateCode = "ON"
	OR StateCode = "OR"
	OS StateCode = "OS"
	OT StateCode = "OT"
	OY StateCode = "OY"
	PA StateCode = "PA"
	PE StateCode = "PE"
	PR StateCode = "PR"
	QC StateCode = "QC"
	QH StateCode = "QH"
	QL StateCode = "QL"
	RI StateCode = "RI"
	SA StateCode = "SA"
	SC StateCode = "SC"
	SD StateCode = "SD"
	SH StateCode = "SH"
	SI StateCode = "SI"
	SK StateCode = "SK"
	SN StateCode = "SN"
	ST StateCode = "ST"
	SX StateCode = "SX"
	SZ StateCode = "SZ"
	TA StateCode = "TA"
	TG StateCode = "TG"
	TJ StateCode = "TJ"
	TK StateCode = "TK"
	TN StateCode = "TN"
	TS StateCode = "TS"
	TT StateCode = "TT"
	TX StateCode = "TX"
	TY StateCode = "TY"
	UT StateCode = "UT"
	VA StateCode = "VA"
	VI StateCode = "VI"
	VT StateCode = "VT"
	WA StateCode = "WA"
	WI StateCode = "WI"
	WK StateCode = "WK"
	WV StateCode = "WV"
	WY StateCode = "WY"
	XJ StateCode = "XJ"
	XZ StateCode = "XZ"
	YA StateCode = "YA"
	YN StateCode = "YN"
	YT StateCode = "YT"
	YU StateCode = "YU"
	ZJ StateCode = "ZJ"
)

// Valid indicates whether the value is a known member of the StateCode enum.
func (e StateCode) Valid() bool {
	switch e {
	case AB:
		return true
	case AC:
		return true
	case AH:
		return true
	case AK:
		return true
	case AL:
		return true
	case AM:
		return true
	case AR:
		return true
	case AS:
		return true
	case AT:
		return true
	case AZ:
		return true
	case BC:
		return true
	case BJ:
		return true
	case CA:
		return true
	case CB:
		return true
	case CO:
		return true
	case CQ:
		return true
	case CT:
		return true
	case CZ:
		return true
	case DC:
		return true
	case DE:
		return true
	case EH:
		return true
	case FH:
		return true
	case FI:
		return true
	case FJ:
		return true
	case FL:
		return true
	case FO:
		return true
	case FS:
		return true
	case GA:
		return true
	case GD:
		return true
	case GF:
		return true
	case GM:
		return true
	case GS:
		return true
	case GU:
		return true
	case GX:
		return true
	case GZ:
		return true
	case HA:
		return true
	case HB:
		return true
	case HE:
		return true
	case HG:
		return true
	case HI:
		return true
	case HL:
		return true
	case HN:
		return true
	case HO:
		return true
	case HS:
		return true
	case IA:
		return true
	case ID:
		return true
	case IG:
		return true
	case IK:
		return true
	case IL:
		return true
	case IN:
		return true
	case IT:
		return true
	case JL:
		return true
	case JS:
		return true
	case JX:
		return true
	case KA:
		return true
	case KC:
		return true
	case KN:
		return true
	case KO:
		return true
	case KS:
		return true
	case KT:
		return true
	case KU:
		return true
	case KY:
		return true
	case LA:
		return true
	case LN:
		return true
	case MA:
		return true
	case MB:
		return true
	case MD:
		return true
	case ME:
		return true
	case MG:
		return true
	case MI:
		return true
	case MN:
		return true
	case MO:
		return true
	case MS:
		return true
	case MT:
		return true
	case MZ:
		return true
	case NB:
		return true
	case NC:
		return true
	case ND:
		return true
	case NE:
		return true
	case NG:
		return true
	case NH:
		return true
	case NJ:
		return true
	case NL:
		return true
	case NM:
		return true
	case NN:
		return true
	case NR:
		return true
	case NS:
		return true
	case NT:
		return true
	case NU:
		return true
	case NV:
		return true
	case NW:
		return true
	case NX:
		return true
	case NY:
		return true
	case OH:
		return true
	case OK:
		return true
	case ON:
		return true
	case OR:
		return true
	case OS:
		return true
	case OT:
		return true
	case OY:
		return true
	case PA:
		return true
	case PE:
		return true
	case PR:
		return true
	case QC:
		return true
	case QH:
		return true
	case QL:
		return true
	case RI:
		return true
	case SA:
		return true
	case SC:
		return true
	case SD:
		return true
	case SH:
		return true
	case SI:
		return true
	case SK:
		return true
	case SN:
		return true
	case ST:
		return true
	case SX:
		return true
	case SZ:
		return true
	case TA:
		return true
	case TG:
		return true
	case TJ:
		return true
	case TK:
		return true
	case TN:
		return true
	case TS:
		return true
	case TT:
		return true
	case TX:
		return true
	case TY:
		return true
	case UT:
		return true
	case VA:
		return true
	case VI:
		return true
	case VT:
		return true
	case WA:
		return true
	case WI:
		return true
	case WK:
		return true
	case WV:
		return true
	case WY:
		return true
	case XJ:
		return true
	case XZ:
		return true
	case YA:
		return true
	case YN:
		return true
	case YT:
		return true
	case YU:
		return true
	case ZJ:
		return true
	default:
		return false
	}
}

// Defines values for GetMappingValuesKeyParamsKey.
const (
	Currency      GetMappingValuesKeyParamsKey = "currency"
	ExchCode      GetMappingValuesKeyParamsKey = "exchCode"
	IdType        GetMappingValuesKeyParamsKey = "idType"
	MarketSecDes  GetMappingValuesKeyParamsKey = "marketSecDes"
	MicCode       GetMappingValuesKeyParamsKey = "micCode"
	SecurityType  GetMappingValuesKeyParamsKey = "securityType"
	SecurityType2 GetMappingValuesKeyParamsKey = "securityType2"
)

// Valid indicates whether the value is a known member of the GetMappingValuesKeyParamsKey enum.
func (e GetMappingValuesKeyParamsKey) Valid() bool {
	switch e {
	case Currency:
		return true
	case ExchCode:
		return true
	case IdType:
		return true
	case MarketSecDes:
		return true
	case MicCode:
		return true
	case SecurityType:
		return true
	case SecurityType2:
		return true
	default:
		return false
	}
}

// BulkMappingJob defines model for BulkMappingJob.
type BulkMappingJob = []MappingJob

// BulkMappingJobResult defines model for BulkMappingJobResult.
type BulkMappingJobResult = []MappingJobResult

// CommonSearchMappingRequest defines model for CommonSearchMappingRequest.
type CommonSearchMappingRequest struct {
	// ContractSize At least one entry should be non-null.
	ContractSize *NullableNumberInterval `json:"contractSize,omitempty"`

	// Coupon At least one entry should be non-null.
	Coupon   *NullableNumberInterval `json:"coupon,omitempty"`
	Currency *string                 `json:"currency,omitempty"`

	// ExchCode Example: US
	ExchCode *string `json:"exchCode,omitempty"`

	// Expiration At least one entry should be non-null.
	Expiration              *NullableDateInterval `json:"expiration,omitempty"`
	IncludeUnlistedEquities *bool                 `json:"includeUnlistedEquities,omitempty"`
	MarketSecDes            *string               `json:"marketSecDes,omitempty"`

	// Maturity At least one entry should be non-null.
	Maturity   *NullableDateInterval                 `json:"maturity,omitempty"`
	MicCode    *string                               `json:"micCode,omitempty"`
	OptionType *CommonSearchMappingRequestOptionType `json:"optionType,omitempty"`

	// SecurityType Example: Equity Option
	SecurityType *string `json:"securityType,omitempty"`

	// SecurityType2 Example: Option
	SecurityType2 *string    `json:"securityType2,omitempty"`
	StateCode     *StateCode `json:"stateCode,omitempty"`

	// Strike At least one entry should be non-null.
	Strike *NullableNumberInterval `json:"strike,omitempty"`
}

// CommonSearchMappingRequestOptionType defines model for CommonSearchMappingRequest.OptionType.
type CommonSearchMappingRequestOptionType string

// FigiResult defines model for FigiResult.
type FigiResult struct {
	// CompositeFIGI Example: BBG000B9XRY4
	CompositeFIGI *string `json:"compositeFIGI,omitempty"`

	// ExchCode Example: UN
	ExchCode *string `json:"exchCode,omitempty"`

	// Figi Example: BBG000B9XVV8
	Figi *string `json:"figi,omitempty"`

	// MarketSector Example: Equity
	MarketSector *string `json:"marketSector,omitempty"`

	// Metadata Exists when API is unable to show non-FIGI fields.
	Metadata *string `json:"metadata,omitempty"`

	// Name Example: APPLE INC
	Name *string `json:"name,omitempty"`

	// SecurityDescription Example: AAPL
	SecurityDescription *string `json:"securityDescription,omitempty"`

	// SecurityType Example: Common Stock
	SecurityType *string `json:"securityType,omitempty"`

	// SecurityType2 Example: Common Stock
	SecurityType2 *string `json:"securityType2,omitempty"`

	// ShareClassFIGI Example: BBG001S5N8V8
	ShareClassFIGI *string `json:"shareClassFIGI,omitempty"`

	// Ticker Example: AAPL
	Ticker *string `json:"ticker,omitempty"`
}

// FilterRequest At least one property in the request object must be populated.
type FilterRequest = SearchRequest

// FilterResponse defines model for FilterResponse.
type FilterResponse = []FilterResponseElement

// FilterResponseElement defines model for FilterResponseElement.
type FilterResponseElement struct {
	Data *[]FigiResult `json:"data,omitempty"`

	// Error Example: query must be a non-empty string.
	Error *string `json:"error,omitempty"`

	// Next Example: QW9JSVFhUkFkQ3hDUWtjd01EQkNPVmszVnprPSAx.zqwblbHbOpBKhinclIlmUiLeMkflobBlSuWyA1Q10Ac=
	Next *string `json:"next,omitempty"`

	// Total Example: 1255917
	Total *float32 `json:"total,omitempty"`
}

// MappingJob For V3: securityType2 is required when idType is BASE_TICKER or ID_EXCH_SYMBOL.  expiration is required when securityType2 is Option or Warrant.  maturity is required when securityType2 is Pool.
type MappingJob struct {
	// ContractSize At least one entry should be non-null.
	ContractSize *NullableNumberInterval `json:"contractSize,omitempty"`

	// Coupon At least one entry should be non-null.
	Coupon   *NullableNumberInterval `json:"coupon,omitempty"`
	Currency *string                 `json:"currency,omitempty"`

	// ExchCode Example: US
	ExchCode *string `json:"exchCode,omitempty"`

	// Expiration At least one entry should be non-null.
	Expiration              *NullableDateInterval `json:"expiration,omitempty"`
	IdType                  MappingJobIdType      `json:"idType"`
	IdValue                 MappingJob_IdValue    `json:"idValue"`
	IncludeUnlistedEquities *bool                 `json:"includeUnlistedEquities,omitempty"`
	MarketSecDes            *string               `json:"marketSecDes,omitempty"`

	// Maturity At least one entry should be non-null.
	Maturity   *NullableDateInterval `json:"maturity,omitempty"`
	MicCode    *string               `json:"micCode,omitempty"`
	OptionType *MappingJobOptionType `json:"optionType,omitempty"`

	// SecurityType Example: Equity Option
	SecurityType *string `json:"securityType,omitempty"`

	// SecurityType2 Example: Option
	SecurityType2 *string    `json:"securityType2,omitempty"`
	StateCode     *StateCode `json:"stateCode,omitempty"`

	// Strike At least one entry should be non-null.
	Strike *NullableNumberInterval `json:"strike,omitempty"`
}

// MappingJobIdType defines model for MappingJob.IdType.
type MappingJobIdType string

// MappingJobIdValue0 defines model for MappingJob.IdValue.0.
type MappingJobIdValue0 = string

// MappingJobIdValue1 defines model for MappingJob.IdValue.1.
type MappingJobIdValue1 = int

// MappingJob_IdValue defines model for MappingJob.IdValue.
type MappingJob_IdValue struct {
	union json.RawMessage
}

// MappingJobOptionType defines model for MappingJob.OptionType.
type MappingJobOptionType string

// MappingJobResult defines model for MappingJobResult.
type MappingJobResult struct {
	union json.RawMessage
}

// MappingJobResultFigiList defines model for MappingJobResultFigiList.
type MappingJobResultFigiList struct {
	Data *[]FigiResult `json:"data,omitempty"`
}

// MappingJobResultFigiNotFound defines model for MappingJobResultFigiNotFound.
type MappingJobResultFigiNotFound struct {
	Warning *string `json:"warning,omitempty"`
}

// NullableDateInterval At least one entry should be non-null.
type NullableDateInterval = []*openapi_types.Date

// NullableNumberInterval At least one entry should be non-null.
type NullableNumberInterval = []*float32

// SearchRequest At least one property in the request object must be populated.
type SearchRequest struct {
	// ContractSize At least one entry should be non-null.
	ContractSize *NullableNumberInterval `json:"contractSize,omitempty"`

	// Coupon At least one entry should be non-null.
	Coupon   *NullableNumberInterval `json:"coupon,omitempty"`
	Currency *string                 `json:"currency,omitempty"`

	// ExchCode Example: US
	ExchCode *string `json:"exchCode,omitempty"`

	// Expiration At least one entry should be non-null.
	Expiration              *NullableDateInterval `json:"expiration,omitempty"`
	IncludeUnlistedEquities *bool                 `json:"includeUnlistedEquities,omitempty"`
	MarketSecDes            *string               `json:"marketSecDes,omitempty"`

	// Maturity At least one entry should be non-null.
	Maturity   *NullableDateInterval    `json:"maturity,omitempty"`
	MicCode    *string                  `json:"micCode,omitempty"`
	OptionType *SearchRequestOptionType `json:"optionType,omitempty"`

	// Query Example: Apple
	Query *string `json:"query,omitempty"`

	// SecurityType Example: Equity Option
	SecurityType *string `json:"securityType,omitempty"`

	// SecurityType2 Example: Option
	SecurityType2 *string `json:"securityType2,omitempty"`

	// Start The number of results returned for any given request is fixed. When more results are accessible, the response will contain a next property whose value should be sent in succeeding requests as the value of the start property. This will notify the API to return the next "page" of results.
	//
	// Example: QW9Fc1FrSkhNREF3TVZKWVJrUTAgMQ==.dannV9BsO7PRuiC2NdA2wVaJLH3fRpeeWnu3HNM73t0=
	Start     *string    `json:"start,omitempty"`
	StateCode *StateCode `json:"stateCode,omitempty"`

	// Strike At least one entry should be non-null.
	Strike *NullableNumberInterval `json:"strike,omitempty"`
}

// SearchRequestOptionType defines model for SearchRequest.OptionType.
type SearchRequestOptionType string

// SearchResponseElement defines model for SearchResponseElement.
type SearchResponseElement struct {
	Data *[]FigiResult `json:"data,omitempty"`

	// Error Example: query must be a non-empty string.
	Error *string `json:"error,omitempty"`

	// Next Example: QW9JSVFhUkFkQ3hDUWtjd01EQkNPVmszVnprPSAx.zqwblbHbOpBKhinclIlmUiLeMkflobBlSuWyA1Q10Ac=
	Next *string `json:"next,omitempty"`
}

// StateCode defines model for StateCode.
type StateCode string

// InlineResponse200 defines model for inline_response_200.
type InlineResponse200 struct {
	Values *[]string `json:"values,omitempty"`
}

// GetMappingValuesKeyParamsKey defines parameters for GetMappingValuesKey.
type GetMappingValuesKeyParamsKey string

// PostFilterJSONRequestBody defines body for PostFilter for application/json ContentType.
type PostFilterJSONRequestBody = FilterRequest

// PostMappingJSONRequestBody defines body for PostMapping for application/json ContentType.
type PostMappingJSONRequestBody = BulkMappingJob

// PostSearchJSONRequestBody defines body for PostSearch for application/json ContentType.
type PostSearchJSONRequestBody = SearchRequest

// AsMappingJobIdValue0 returns the union data inside the MappingJob_IdValue as a MappingJobIdValue0
func (t MappingJob_IdValue) AsMappingJobIdValue0() (MappingJobIdValue0, error) {
	var body MappingJobIdValue0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMappingJobIdValue0 overwrites any union data inside the MappingJob_IdValue as the provided MappingJobIdValue0
func (t *MappingJob_IdValue) FromMappingJobIdValue0(v MappingJobIdValue0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMappingJobIdValue0 performs a merge with any union data inside the MappingJob_IdValue, using the provided MappingJobIdValue0
func (t *MappingJob_IdValue) MergeMappingJobIdValue0(v MappingJobIdValue0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMappingJobIdValue1 returns the union data inside the MappingJob_IdValue as a MappingJobIdValue1
func (t MappingJob_IdValue) AsMappingJobIdValue1() (MappingJobIdValue1, error) {
	var body MappingJobIdValue1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMappingJobIdValue1 overwrites any union data inside the MappingJob_IdValue as the provided MappingJobIdValue1
func (t *MappingJob_IdValue) FromMappingJobIdValue1(v MappingJobIdValue1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMappingJobIdValue1 performs a merge with any union data inside the MappingJob_IdValue, using the provided MappingJobIdValue1
func (t *MappingJob_IdValue) MergeMappingJobIdValue1(v MappingJobIdValue1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t MappingJob_IdValue) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *MappingJob_IdValue) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsMappingJobResultFigiList returns the union data inside the MappingJobResult as a MappingJobResultFigiList
func (t MappingJobResult) AsMappingJobResultFigiList() (MappingJobResultFigiList, error) {
	var body MappingJobResultFigiList
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMappingJobResultFigiList overwrites any union data inside the MappingJobResult as the provided MappingJobResultFigiList
func (t *MappingJobResult) FromMappingJobResultFigiList(v MappingJobResultFigiList) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMappingJobResultFigiList performs a merge with any union data inside the MappingJobResult, using the provided MappingJobResultFigiList
func (t *MappingJobResult) MergeMappingJobResultFigiList(v MappingJobResultFigiList) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMappingJobResultFigiNotFound returns the union data inside the MappingJobResult as a MappingJobResultFigiNotFound
func (t MappingJobResult) AsMappingJobResultFigiNotFound() (MappingJobResultFigiNotFound, error) {
	var body MappingJobResultFigiNotFound
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMappingJobResultFigiNotFound overwrites any union data inside the MappingJobResult as the provided MappingJobResultFigiNotFound
func (t *MappingJobResult) FromMappingJobResultFigiNotFound(v MappingJobResultFigiNotFound) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMappingJobResultFigiNotFound performs a merge with any union data inside the MappingJobResult, using the provided MappingJobResultFigiNotFound
func (t *MappingJobResult) MergeMappingJobResultFigiNotFound(v MappingJobResultFigiNotFound) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t MappingJobResult) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *MappingJobResult) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// PostFilterWithBody performs a POST /filter (the `PostFilter` operationId) request,
	// with any type of body and a specified content type.
	//
	// Search for FIGIs using key words and other filters. The results are listed alphabetically by FIGI and include the number of results.
	PostFilterWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostFilter performs a POST /filter (the `PostFilter` operationId) request.
	// Takes a body of the `application/json` content type.
	//
	// Search for FIGIs using key words and other filters. The results are listed alphabetically by FIGI and include the number of results.
	PostFilter(ctx context.Context, body PostFilterJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostMappingWithBody performs a POST /mapping (the `PostMapping` operationId) request,
	// with any type of body and a specified content type.
	//
	// Allows mapping from third-party identifiers to FIGIs.
	PostMappingWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostMapping performs a POST /mapping (the `PostMapping` operationId) request.
	// Takes a body of the `application/json` content type.
	//
	// Allows mapping from third-party identifiers to FIGIs.
	PostMapping(ctx context.Context, body PostMappingJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMappingValuesKey performs a GET /mapping/values/{key} (the `GetMappingValuesKey` operationId) request.
	//
	// Get values for enum-like fields.
	GetMappingValuesKey(ctx context.Context, key GetMappingValuesKeyParamsKey, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostSearchWithBody performs a POST /search (the `PostSearch` operationId) request,
	// with any type of body and a specified content type.
	//
	// Search for FIGIs using key words and other filters.
	PostSearchWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostSearch performs a POST /search (the `PostSearch` operationId) request.
	// Takes a body of the `application/json` content type.
	//
	// Search for FIGIs using key words and other filters.
	PostSearch(ctx context.Context, body PostSearchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// PostFilterWithBody performs a POST /filter (the `PostFilter` operationId) request,
// with any type of body and a specified content type.
//
// Search for FIGIs using key words and other filters. The results are listed alphabetically by FIGI and include the number of results.
func (c *Client) PostFilterWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostFilterRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostFilter performs a POST /filter (the `PostFilter` operationId) request.
// Takes a body of the `application/json` content type.
//
// Search for FIGIs using key words and other filters. The results are listed alphabetically by FIGI and include the number of results.
func (c *Client) PostFilter(ctx context.Context, body PostFilterJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostFilterRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostMappingWithBody performs a POST /mapping (the `PostMapping` operationId) request,
// with any type of body and a specified content type.
//
// Allows mapping from third-party identifiers to FIGIs.
func (c *Client) PostMappingWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostMappingRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostMapping performs a POST /mapping (the `PostMapping` operationId) request.
// Takes a body of the `application/json` content type.
//
// Allows mapping from third-party identifiers to FIGIs.
func (c *Client) PostMapping(ctx context.Context, body PostMappingJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostMappingRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetMappingValuesKey performs a GET /mapping/values/{key} (the `GetMappingValuesKey` operationId) request.
//
// Get values for enum-like fields.
func (c *Client) GetMappingValuesKey(ctx context.Context, key GetMappingValuesKeyParamsKey, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMappingValuesKeyRequest(c.Server, key)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostSearchWithBody performs a POST /search (the `PostSearch` operationId) request,
// with any type of body and a specified content type.
//
// Search for FIGIs using key words and other filters.
func (c *Client) PostSearchWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSearchRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostSearch performs a POST /search (the `PostSearch` operationId) request.
// Takes a body of the `application/json` content type.
//
// Search for FIGIs using key words and other filters.
func (c *Client) PostSearch(ctx context.Context, body PostSearchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSearchRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostFilterRequest calls the generic PostFilter builder with application/json body
func NewPostFilterRequest(server string, body PostFilterJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostFilterRequestWithBody(server, "application/json", bodyReader)
}

// NewPostFilterRequestWithBody constructs an http.Request for the PostFilter method, with any body, and a specified content type
func NewPostFilterRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/filter")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostMappingRequest calls the generic PostMapping builder with application/json body
func NewPostMappingRequest(server string, body PostMappingJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostMappingRequestWithBody(server, "application/json", bodyReader)
}

// NewPostMappingRequestWithBody constructs an http.Request for the PostMapping method, with any body, and a specified content type
func NewPostMappingRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/mapping")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetMappingValuesKeyRequest constructs an http.Request for the GetMappingValuesKey method
func NewGetMappingValuesKeyRequest(server string, key GetMappingValuesKeyParamsKey) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "key", key, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/mapping/values/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostSearchRequest calls the generic PostSearch builder with application/json body
func NewPostSearchRequest(server string, body PostSearchJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostSearchRequestWithBody(server, "application/json", bodyReader)
}

// NewPostSearchRequestWithBody constructs an http.Request for the PostSearch method, with any body, and a specified content type
func NewPostSearchRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/search")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// PostFilterWithBodyWithResponse performs a POST /filter (the `PostFilter` operationId) request,
	// with any type of body and a specified content type.
	//
	// Search for FIGIs using key words and other filters. The results are listed alphabetically by FIGI and include the number of results.
	//
	// Returns a wrapper object for the known response body format(s).
	PostFilterWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostFilterResponse, error)

	// PostFilterWithResponse performs a POST /filter (the `PostFilter` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Search for FIGIs using key words and other filters. The results are listed alphabetically by FIGI and include the number of results.
	PostFilterWithResponse(ctx context.Context, body PostFilterJSONRequestBody, reqEditors ...RequestEditorFn) (*PostFilterResponse, error)

	// PostMappingWithBodyWithResponse performs a POST /mapping (the `PostMapping` operationId) request,
	// with any type of body and a specified content type.
	//
	// Allows mapping from third-party identifiers to FIGIs.
	//
	// Returns a wrapper object for the known response body format(s).
	PostMappingWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostMappingResponse, error)

	// PostMappingWithResponse performs a POST /mapping (the `PostMapping` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Allows mapping from third-party identifiers to FIGIs.
	PostMappingWithResponse(ctx context.Context, body PostMappingJSONRequestBody, reqEditors ...RequestEditorFn) (*PostMappingResponse, error)

	// GetMappingValuesKeyWithResponse performs a GET /mapping/values/{key} (the `GetMappingValuesKey` operationId) request.
	//
	// Get values for enum-like fields.
	//
	// Returns a wrapper object for the known response body format(s).
	GetMappingValuesKeyWithResponse(ctx context.Context, key GetMappingValuesKeyParamsKey, reqEditors ...RequestEditorFn) (*GetMappingValuesKeyResponse, error)

	// PostSearchWithBodyWithResponse performs a POST /search (the `PostSearch` operationId) request,
	// with any type of body and a specified content type.
	//
	// Search for FIGIs using key words and other filters.
	//
	// Returns a wrapper object for the known response body format(s).
	PostSearchWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSearchResponse, error)

	// PostSearchWithResponse performs a POST /search (the `PostSearch` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Search for FIGIs using key words and other filters.
	PostSearchWithResponse(ctx context.Context, body PostSearchJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSearchResponse, error)
}

type PostFilterResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *FilterResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PostFilterResponse) GetJSON200() *FilterResponse {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r PostFilterResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostFilterResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostFilterResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostFilterResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostMappingResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *BulkMappingJobResult
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PostMappingResponse) GetJSON200() *BulkMappingJobResult {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r PostMappingResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostMappingResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostMappingResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostMappingResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetMappingValuesKeyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *InlineResponse200
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetMappingValuesKeyResponse) GetJSON200() *InlineResponse200 {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetMappingValuesKeyResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetMappingValuesKeyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMappingValuesKeyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetMappingValuesKeyResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostSearchResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *SearchResponseElement
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PostSearchResponse) GetJSON200() *SearchResponseElement {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r PostSearchResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostSearchResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostSearchResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostSearchResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// PostFilterWithBodyWithResponse performs a POST /filter (the `PostFilter` operationId) request,
// with any type of body and a specified content type.
//
// Search for FIGIs using key words and other filters. The results are listed alphabetically by FIGI and include the number of results.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) PostFilterWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostFilterResponse, error) {
	rsp, err := c.PostFilterWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostFilterResponse(rsp)
}

// PostFilterWithResponse performs a POST /filter (the `PostFilter` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Search for FIGIs using key words and other filters. The results are listed alphabetically by FIGI and include the number of results.
func (c *ClientWithResponses) PostFilterWithResponse(ctx context.Context, body PostFilterJSONRequestBody, reqEditors ...RequestEditorFn) (*PostFilterResponse, error) {
	rsp, err := c.PostFilter(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostFilterResponse(rsp)
}

// PostMappingWithBodyWithResponse performs a POST /mapping (the `PostMapping` operationId) request,
// with any type of body and a specified content type.
//
// Allows mapping from third-party identifiers to FIGIs.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) PostMappingWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostMappingResponse, error) {
	rsp, err := c.PostMappingWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostMappingResponse(rsp)
}

// PostMappingWithResponse performs a POST /mapping (the `PostMapping` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Allows mapping from third-party identifiers to FIGIs.
func (c *ClientWithResponses) PostMappingWithResponse(ctx context.Context, body PostMappingJSONRequestBody, reqEditors ...RequestEditorFn) (*PostMappingResponse, error) {
	rsp, err := c.PostMapping(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostMappingResponse(rsp)
}

// GetMappingValuesKeyWithResponse performs a GET /mapping/values/{key} (the `GetMappingValuesKey` operationId) request.
//
// Get values for enum-like fields.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) GetMappingValuesKeyWithResponse(ctx context.Context, key GetMappingValuesKeyParamsKey, reqEditors ...RequestEditorFn) (*GetMappingValuesKeyResponse, error) {
	rsp, err := c.GetMappingValuesKey(ctx, key, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMappingValuesKeyResponse(rsp)
}

// PostSearchWithBodyWithResponse performs a POST /search (the `PostSearch` operationId) request,
// with any type of body and a specified content type.
//
// Search for FIGIs using key words and other filters.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) PostSearchWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSearchResponse, error) {
	rsp, err := c.PostSearchWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSearchResponse(rsp)
}

// PostSearchWithResponse performs a POST /search (the `PostSearch` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Search for FIGIs using key words and other filters.
func (c *ClientWithResponses) PostSearchWithResponse(ctx context.Context, body PostSearchJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSearchResponse, error) {
	rsp, err := c.PostSearch(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSearchResponse(rsp)
}

// ParsePostFilterResponse parses an HTTP response from a PostFilterWithResponse call
func ParsePostFilterResponse(rsp *http.Response) (*PostFilterResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostFilterResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FilterResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostMappingResponse parses an HTTP response from a PostMappingWithResponse call
func ParsePostMappingResponse(rsp *http.Response) (*PostMappingResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostMappingResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BulkMappingJobResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetMappingValuesKeyResponse parses an HTTP response from a GetMappingValuesKeyWithResponse call
func ParseGetMappingValuesKeyResponse(rsp *http.Response) (*GetMappingValuesKeyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMappingValuesKeyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest InlineResponse200
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostSearchResponse parses an HTTP response from a PostSearchWithResponse call
func ParsePostSearchResponse(rsp *http.Response) (*PostSearchResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostSearchResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SearchResponseElement
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /filter)
	PostFilter(w http.ResponseWriter, r *http.Request)

	// (POST /mapping)
	PostMapping(w http.ResponseWriter, r *http.Request)

	// (GET /mapping/values/{key})
	GetMappingValuesKey(w http.ResponseWriter, r *http.Request, key GetMappingValuesKeyParamsKey)

	// (POST /search)
	PostSearch(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostFilter operation middleware
func (siw *ServerInterfaceWrapper) PostFilter(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostFilter(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostMapping operation middleware
func (siw *ServerInterfaceWrapper) PostMapping(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostMapping(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMappingValuesKey operation middleware
func (siw *ServerInterfaceWrapper) GetMappingValuesKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key" -------------
	var key GetMappingValuesKeyParamsKey

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMappingValuesKey(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostSearch operation middleware
func (siw *ServerInterfaceWrapper) PostSearch(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostSearch(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/filter", wrapper.PostFilter)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/mapping", wrapper.PostMapping)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/mapping/values/{key}", wrapper.GetMappingValuesKey)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/search", wrapper.PostSearch)

	return m
}

type PostFilterRequestObject struct {
	Body *PostFilterJSONRequestBody
}

type PostFilterResponseObject interface {
	VisitPostFilterResponse(w http.ResponseWriter) error
}

type PostFilter200JSONResponse FilterResponse

func (response PostFilter200JSONResponse) VisitPostFilterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostFilter400TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response PostFilter400TexthtmlCharsetUtf8Response) VisitPostFilterResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(400)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostFilter401TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response PostFilter401TexthtmlCharsetUtf8Response) VisitPostFilterResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(401)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostFilter405TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response PostFilter405TexthtmlCharsetUtf8Response) VisitPostFilterResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(405)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostFilter406TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response PostFilter406TexthtmlCharsetUtf8Response) VisitPostFilterResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(406)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostFilter415TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response PostFilter415TexthtmlCharsetUtf8Response) VisitPostFilterResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(415)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostFilter429TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response PostFilter429TexthtmlCharsetUtf8Response) VisitPostFilterResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(429)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostFilter500TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response PostFilter500TexthtmlCharsetUtf8Response) VisitPostFilterResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(500)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostFilter503TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response PostFilter503TexthtmlCharsetUtf8Response) VisitPostFilterResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(503)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostMappingRequestObject struct {
	Body *PostMappingJSONRequestBody
}

type PostMappingResponseObject interface {
	VisitPostMappingResponse(w http.ResponseWriter) error
}

type PostMapping200JSONResponse BulkMappingJobResult

func (response PostMapping200JSONResponse) VisitPostMappingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostMapping400TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response PostMapping400TexthtmlCharsetUtf8Response) VisitPostMappingResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(400)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostMapping401TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response PostMapping401TexthtmlCharsetUtf8Response) VisitPostMappingResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(401)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostMapping405TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response PostMapping405TexthtmlCharsetUtf8Response) VisitPostMappingResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(405)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostMapping406TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response PostMapping406TexthtmlCharsetUtf8Response) VisitPostMappingResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(406)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostMapping415TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response PostMapping415TexthtmlCharsetUtf8Response) VisitPostMappingResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(415)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostMapping429TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response PostMapping429TexthtmlCharsetUtf8Response) VisitPostMappingResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(429)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostMapping500TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response PostMapping500TexthtmlCharsetUtf8Response) VisitPostMappingResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(500)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostMapping503TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response PostMapping503TexthtmlCharsetUtf8Response) VisitPostMappingResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(503)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetMappingValuesKeyRequestObject struct {
	Key GetMappingValuesKeyParamsKey `json:"key"`
}

type GetMappingValuesKeyResponseObject interface {
	VisitGetMappingValuesKeyResponse(w http.ResponseWriter) error
}

type GetMappingValuesKey200JSONResponse InlineResponse200

func (response GetMappingValuesKey200JSONResponse) VisitGetMappingValuesKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMappingValuesKey400TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetMappingValuesKey400TexthtmlCharsetUtf8Response) VisitGetMappingValuesKeyResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(400)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetMappingValuesKey401TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetMappingValuesKey401TexthtmlCharsetUtf8Response) VisitGetMappingValuesKeyResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(401)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetMappingValuesKey405TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetMappingValuesKey405TexthtmlCharsetUtf8Response) VisitGetMappingValuesKeyResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(405)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetMappingValuesKey406TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetMappingValuesKey406TexthtmlCharsetUtf8Response) VisitGetMappingValuesKeyResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(406)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetMappingValuesKey415TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetMappingValuesKey415TexthtmlCharsetUtf8Response) VisitGetMappingValuesKeyResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(415)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetMappingValuesKey429TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetMappingValuesKey429TexthtmlCharsetUtf8Response) VisitGetMappingValuesKeyResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(429)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetMappingValuesKey500TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetMappingValuesKey500TexthtmlCharsetUtf8Response) VisitGetMappingValuesKeyResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(500)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetMappingValuesKey503TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetMappingValuesKey503TexthtmlCharsetUtf8Response) VisitGetMappingValuesKeyResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(503)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostSearchRequestObject struct {
	Body *PostSearchJSONRequestBody
}

type PostSearchResponseObject interface {
	VisitPostSearchResponse(w http.ResponseWriter) error
}

type PostSearch200JSONResponse SearchResponseElement

func (response PostSearch200JSONResponse) VisitPostSearchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostSearch400TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response PostSearch400TexthtmlCharsetUtf8Response) VisitPostSearchResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(400)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostSearch401TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response PostSearch401TexthtmlCharsetUtf8Response) VisitPostSearchResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(401)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostSearch405TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response PostSearch405TexthtmlCharsetUtf8Response) VisitPostSearchResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(405)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostSearch406TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response PostSearch406TexthtmlCharsetUtf8Response) VisitPostSearchResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(406)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostSearch415TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response PostSearch415TexthtmlCharsetUtf8Response) VisitPostSearchResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(415)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostSearch429TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response PostSearch429TexthtmlCharsetUtf8Response) VisitPostSearchResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(429)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostSearch500TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response PostSearch500TexthtmlCharsetUtf8Response) VisitPostSearchResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(500)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostSearch503TexthtmlCharsetUtf8Response struct {
	Body          io.Reader
	ContentLength int64
}

func (response PostSearch503TexthtmlCharsetUtf8Response) VisitPostSearchResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(503)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /filter)
	PostFilter(ctx context.Context, request PostFilterRequestObject) (PostFilterResponseObject, error)

	// (POST /mapping)
	PostMapping(ctx context.Context, request PostMappingRequestObject) (PostMappingResponseObject, error)

	// (GET /mapping/values/{key})
	GetMappingValuesKey(ctx context.Context, request GetMappingValuesKeyRequestObject) (GetMappingValuesKeyResponseObject, error)

	// (POST /search)
	PostSearch(ctx context.Context, request PostSearchRequestObject) (PostSearchResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PostFilter operation middleware
func (sh *strictHandler) PostFilter(w http.ResponseWriter, r *http.Request) {
	var request PostFilterRequestObject

	var body PostFilterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostFilter(ctx, request.(PostFilterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostFilter")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostFilterResponseObject); ok {
		if err := validResponse.VisitPostFilterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostMapping operation middleware
func (sh *strictHandler) PostMapping(w http.ResponseWriter, r *http.Request) {
	var request PostMappingRequestObject

	var body PostMappingJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostMapping(ctx, request.(PostMappingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostMapping")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostMappingResponseObject); ok {
		if err := validResponse.VisitPostMappingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMappingValuesKey operation middleware
func (sh *strictHandler) GetMappingValuesKey(w http.ResponseWriter, r *http.Request, key GetMappingValuesKeyParamsKey) {
	var request GetMappingValuesKeyRequestObject

	request.Key = key

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMappingValuesKey(ctx, request.(GetMappingValuesKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMappingValuesKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMappingValuesKeyResponseObject); ok {
		if err := validResponse.VisitGetMappingValuesKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostSearch operation middleware
func (sh *strictHandler) PostSearch(w http.ResponseWriter, r *http.Request) {
	var request PostSearchRequestObject

	var body PostSearchJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostSearch(ctx, request.(PostSearchRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSearch")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostSearchResponseObject); ok {
		if err := validResponse.VisitPostSearchResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
