//
// Copyright 2018, Trading-API, Consorsbank.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: AccessService.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Login request provides data for initial access to the TAPI
type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Secret is user defined access string.
	// It's not possible to restore this secret directly. See double MD5 hash logic + salt
	Secret        string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_AccessService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AccessService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_AccessService_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

// *
// Login reply provides information that need for the access to the TAPI
type LoginReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Access token is used in each request by the access to the TAPI.
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// *
	// Error information if occuirs
	Error         *Error `protobuf:"bytes,1000,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_AccessService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_AccessService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_AccessService_proto_rawDescGZIP(), []int{1}
}

func (x *LoginReply) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginReply) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type LogoutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Access token to invalidate.
	AccessToken   string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_AccessService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AccessService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_AccessService_proto_rawDescGZIP(), []int{2}
}

func (x *LogoutRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type LogoutReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Error information if occuirs
	Error         *Error `protobuf:"bytes,1000,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReply) Reset() {
	*x = LogoutReply{}
	mi := &file_AccessService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReply) ProtoMessage() {}

func (x *LogoutReply) ProtoReflect() protoreflect.Message {
	mi := &file_AccessService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReply.ProtoReflect.Descriptor instead.
func (*LogoutReply) Descriptor() ([]byte, []int) {
	return file_AccessService_proto_rawDescGZIP(), []int{3}
}

func (x *LogoutReply) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_AccessService_proto protoreflect.FileDescriptor

const file_AccessService_proto_rawDesc = "" +
	"\n" +
	"\x13AccessService.proto\x12 com.consorsbank.module.tapi.grpc\x1a\fCommon.proto\"&\n" +
	"\fLoginRequest\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\"o\n" +
	"\n" +
	"LoginReply\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12>\n" +
	"\x05error\x18\xe8\a \x01(\v2'.com.consorsbank.module.tapi.grpc.ErrorR\x05error\"2\n" +
	"\rLogoutRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"M\n" +
	"\vLogoutReply\x12>\n" +
	"\x05error\x18\xe8\a \x01(\v2'.com.consorsbank.module.tapi.grpc.ErrorR\x05errorB+\n" +
	"'com.consorsbank.module.tapi.grpc.accessP\x01b\x06proto3"

var (
	file_AccessService_proto_rawDescOnce sync.Once
	file_AccessService_proto_rawDescData []byte
)

func file_AccessService_proto_rawDescGZIP() []byte {
	file_AccessService_proto_rawDescOnce.Do(func() {
		file_AccessService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AccessService_proto_rawDesc), len(file_AccessService_proto_rawDesc)))
	})
	return file_AccessService_proto_rawDescData
}

var file_AccessService_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_AccessService_proto_goTypes = []any{
	(*LoginRequest)(nil),  // 0: com.consorsbank.module.tapi.grpc.LoginRequest
	(*LoginReply)(nil),    // 1: com.consorsbank.module.tapi.grpc.LoginReply
	(*LogoutRequest)(nil), // 2: com.consorsbank.module.tapi.grpc.LogoutRequest
	(*LogoutReply)(nil),   // 3: com.consorsbank.module.tapi.grpc.LogoutReply
	(*Error)(nil),         // 4: com.consorsbank.module.tapi.grpc.Error
}
var file_AccessService_proto_depIdxs = []int32{
	4, // 0: com.consorsbank.module.tapi.grpc.LoginReply.error:type_name -> com.consorsbank.module.tapi.grpc.Error
	4, // 1: com.consorsbank.module.tapi.grpc.LogoutReply.error:type_name -> com.consorsbank.module.tapi.grpc.Error
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_AccessService_proto_init() }
func file_AccessService_proto_init() {
	if File_AccessService_proto != nil {
		return
	}
	file_Common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AccessService_proto_rawDesc), len(file_AccessService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AccessService_proto_goTypes,
		DependencyIndexes: file_AccessService_proto_depIdxs,
		MessageInfos:      file_AccessService_proto_msgTypes,
	}.Build()
	File_AccessService_proto = out.File
	file_AccessService_proto_goTypes = nil
	file_AccessService_proto_depIdxs = nil
}
