//
// Copyright 2018, Trading-API, Consorsbank.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: AccountService.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// TradingAccount is trading account connected to the
// depot
type TradingAccount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Account number
	AccountNumber string `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	// *
	// Depot number
	DepotNumber string `protobuf:"bytes,2,opt,name=depot_number,json=depotNumber,proto3" json:"depot_number,omitempty"`
	// *
	// Name of the account owners
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// *
	//
	//	If account is tradable then true or false otherwise
	Tradable      bool `protobuf:"varint,4,opt,name=tradable,proto3" json:"tradable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradingAccount) Reset() {
	*x = TradingAccount{}
	mi := &file_AccountService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradingAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradingAccount) ProtoMessage() {}

func (x *TradingAccount) ProtoReflect() protoreflect.Message {
	mi := &file_AccountService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradingAccount.ProtoReflect.Descriptor instead.
func (*TradingAccount) Descriptor() ([]byte, []int) {
	return file_AccountService_proto_rawDescGZIP(), []int{0}
}

func (x *TradingAccount) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *TradingAccount) GetDepotNumber() string {
	if x != nil {
		return x.DepotNumber
	}
	return ""
}

func (x *TradingAccount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TradingAccount) GetTradable() bool {
	if x != nil {
		return x.Tradable
	}
	return false
}

// *
// Trading account request contains trading account related data
type TradingAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Access token
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// *
	// Trading account
	TradingAccount *TradingAccount `protobuf:"bytes,2,opt,name=trading_account,json=tradingAccount,proto3" json:"trading_account,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TradingAccountRequest) Reset() {
	*x = TradingAccountRequest{}
	mi := &file_AccountService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradingAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradingAccountRequest) ProtoMessage() {}

func (x *TradingAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AccountService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradingAccountRequest.ProtoReflect.Descriptor instead.
func (*TradingAccountRequest) Descriptor() ([]byte, []int) {
	return file_AccountService_proto_rawDescGZIP(), []int{1}
}

func (x *TradingAccountRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TradingAccountRequest) GetTradingAccount() *TradingAccount {
	if x != nil {
		return x.TradingAccount
	}
	return nil
}

// *
// TradingAccounts contains account information
// from current session
type TradingAccounts struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// List of trading accounts
	Accounts []*TradingAccount `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	// *
	// Error information if occuirs
	Error         *Error `protobuf:"bytes,1000,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradingAccounts) Reset() {
	*x = TradingAccounts{}
	mi := &file_AccountService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradingAccounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradingAccounts) ProtoMessage() {}

func (x *TradingAccounts) ProtoReflect() protoreflect.Message {
	mi := &file_AccountService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradingAccounts.ProtoReflect.Descriptor instead.
func (*TradingAccounts) Descriptor() ([]byte, []int) {
	return file_AccountService_proto_rawDescGZIP(), []int{2}
}

func (x *TradingAccounts) GetAccounts() []*TradingAccount {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *TradingAccounts) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// *
// TradingAccountTransactions contains account transactions
type TradingAccountTransactions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Trading account
	Account *TradingAccount `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// *
	// List of transactions
	Transactions []*TradingAccountTransactions_Transaction `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	// *
	// Error information if happened
	Error         *Error `protobuf:"bytes,1000,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradingAccountTransactions) Reset() {
	*x = TradingAccountTransactions{}
	mi := &file_AccountService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradingAccountTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradingAccountTransactions) ProtoMessage() {}

func (x *TradingAccountTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_AccountService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradingAccountTransactions.ProtoReflect.Descriptor instead.
func (*TradingAccountTransactions) Descriptor() ([]byte, []int) {
	return file_AccountService_proto_rawDescGZIP(), []int{3}
}

func (x *TradingAccountTransactions) GetAccount() *TradingAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *TradingAccountTransactions) GetTransactions() []*TradingAccountTransactions_Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *TradingAccountTransactions) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// *
// TradingAccountInformation contains specific for this account information
type TradingAccountInformation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Trading account
	Account *TradingAccount `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// *
	// Account balance
	Balance float64 `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	// *
	// Credit limit information
	CreditLimit float64 `protobuf:"fixed64,3,opt,name=credit_limit,json=creditLimit,proto3" json:"credit_limit,omitempty"`
	// *
	// Buying power
	BuyingPower float64 `protobuf:"fixed64,4,opt,name=buying_power,json=buyingPower,proto3" json:"buying_power,omitempty"`
	// *
	// Credit limit intraday information, #pro# only
	CreditLimitIntraday float64 `protobuf:"fixed64,9,opt,name=credit_limit_intraday,json=creditLimitIntraday,proto3" json:"credit_limit_intraday,omitempty"`
	// *
	// Buyng power intraday, #pro# only
	BuyingPowerIntraday float64 `protobuf:"fixed64,10,opt,name=buying_power_intraday,json=buyingPowerIntraday,proto3" json:"buying_power_intraday,omitempty"`
	// *
	// Error information if occuirs
	Error         *Error `protobuf:"bytes,1000,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradingAccountInformation) Reset() {
	*x = TradingAccountInformation{}
	mi := &file_AccountService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradingAccountInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradingAccountInformation) ProtoMessage() {}

func (x *TradingAccountInformation) ProtoReflect() protoreflect.Message {
	mi := &file_AccountService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradingAccountInformation.ProtoReflect.Descriptor instead.
func (*TradingAccountInformation) Descriptor() ([]byte, []int) {
	return file_AccountService_proto_rawDescGZIP(), []int{4}
}

func (x *TradingAccountInformation) GetAccount() *TradingAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *TradingAccountInformation) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *TradingAccountInformation) GetCreditLimit() float64 {
	if x != nil {
		return x.CreditLimit
	}
	return 0
}

func (x *TradingAccountInformation) GetBuyingPower() float64 {
	if x != nil {
		return x.BuyingPower
	}
	return 0
}

func (x *TradingAccountInformation) GetCreditLimitIntraday() float64 {
	if x != nil {
		return x.CreditLimitIntraday
	}
	return 0
}

func (x *TradingAccountInformation) GetBuyingPowerIntraday() float64 {
	if x != nil {
		return x.BuyingPowerIntraday
	}
	return 0
}

func (x *TradingAccountInformation) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// *
// Transaction contains onformation about one transaction
type TradingAccountTransactions_Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Transaction date
	TransactionDate *Date `protobuf:"bytes,1,opt,name=transaction_date,json=transactionDate,proto3" json:"transaction_date,omitempty"`
	// *
	// Amount value
	Amount float64 `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// *
	// Transaction opponent
	Opponent string `protobuf:"bytes,3,opt,name=opponent,proto3" json:"opponent,omitempty"`
	// *
	// Information about transaction
	Information string `protobuf:"bytes,4,opt,name=information,proto3" json:"information,omitempty"`
	// *
	// Value date
	ValueDate     *Date `protobuf:"bytes,5,opt,name=value_date,json=valueDate,proto3" json:"value_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradingAccountTransactions_Transaction) Reset() {
	*x = TradingAccountTransactions_Transaction{}
	mi := &file_AccountService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradingAccountTransactions_Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradingAccountTransactions_Transaction) ProtoMessage() {}

func (x *TradingAccountTransactions_Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_AccountService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradingAccountTransactions_Transaction.ProtoReflect.Descriptor instead.
func (*TradingAccountTransactions_Transaction) Descriptor() ([]byte, []int) {
	return file_AccountService_proto_rawDescGZIP(), []int{3, 0}
}

func (x *TradingAccountTransactions_Transaction) GetTransactionDate() *Date {
	if x != nil {
		return x.TransactionDate
	}
	return nil
}

func (x *TradingAccountTransactions_Transaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TradingAccountTransactions_Transaction) GetOpponent() string {
	if x != nil {
		return x.Opponent
	}
	return ""
}

func (x *TradingAccountTransactions_Transaction) GetInformation() string {
	if x != nil {
		return x.Information
	}
	return ""
}

func (x *TradingAccountTransactions_Transaction) GetValueDate() *Date {
	if x != nil {
		return x.ValueDate
	}
	return nil
}

var File_AccountService_proto protoreflect.FileDescriptor

const file_AccountService_proto_rawDesc = "" +
	"\n" +
	"\x14AccountService.proto\x12 com.consorsbank.module.tapi.grpc\x1a\fCommon.proto\"\x8a\x01\n" +
	"\x0eTradingAccount\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\raccountNumber\x12!\n" +
	"\fdepot_number\x18\x02 \x01(\tR\vdepotNumber\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\btradable\x18\x04 \x01(\bR\btradable\"\x95\x01\n" +
	"\x15TradingAccountRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12Y\n" +
	"\x0ftrading_account\x18\x02 \x01(\v20.com.consorsbank.module.tapi.grpc.TradingAccountR\x0etradingAccount\"\x9f\x01\n" +
	"\x0fTradingAccounts\x12L\n" +
	"\baccounts\x18\x01 \x03(\v20.com.consorsbank.module.tapi.grpc.TradingAccountR\baccounts\x12>\n" +
	"\x05error\x18\xe8\a \x01(\v2'.com.consorsbank.module.tapi.grpc.ErrorR\x05error\"\x96\x04\n" +
	"\x1aTradingAccountTransactions\x12J\n" +
	"\aaccount\x18\x01 \x01(\v20.com.consorsbank.module.tapi.grpc.TradingAccountR\aaccount\x12l\n" +
	"\ftransactions\x18\x02 \x03(\v2H.com.consorsbank.module.tapi.grpc.TradingAccountTransactions.TransactionR\ftransactions\x12>\n" +
	"\x05error\x18\xe8\a \x01(\v2'.com.consorsbank.module.tapi.grpc.ErrorR\x05error\x1a\xfd\x01\n" +
	"\vTransaction\x12Q\n" +
	"\x10transaction_date\x18\x01 \x01(\v2&.com.consorsbank.module.tapi.grpc.DateR\x0ftransactionDate\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bopponent\x18\x03 \x01(\tR\bopponent\x12 \n" +
	"\vinformation\x18\x04 \x01(\tR\vinformation\x12E\n" +
	"\n" +
	"value_date\x18\x05 \x01(\v2&.com.consorsbank.module.tapi.grpc.DateR\tvalueDate\"\xef\x02\n" +
	"\x19TradingAccountInformation\x12J\n" +
	"\aaccount\x18\x01 \x01(\v20.com.consorsbank.module.tapi.grpc.TradingAccountR\aaccount\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\x12!\n" +
	"\fcredit_limit\x18\x03 \x01(\x01R\vcreditLimit\x12!\n" +
	"\fbuying_power\x18\x04 \x01(\x01R\vbuyingPower\x122\n" +
	"\x15credit_limit_intraday\x18\t \x01(\x01R\x13creditLimitIntraday\x122\n" +
	"\x15buying_power_intraday\x18\n" +
	" \x01(\x01R\x13buyingPowerIntraday\x12>\n" +
	"\x05error\x18\xe8\a \x01(\v2'.com.consorsbank.module.tapi.grpc.ErrorR\x05errorB,\n" +
	"(com.consorsbank.module.tapi.grpc.accountP\x01b\x06proto3"

var (
	file_AccountService_proto_rawDescOnce sync.Once
	file_AccountService_proto_rawDescData []byte
)

func file_AccountService_proto_rawDescGZIP() []byte {
	file_AccountService_proto_rawDescOnce.Do(func() {
		file_AccountService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AccountService_proto_rawDesc), len(file_AccountService_proto_rawDesc)))
	})
	return file_AccountService_proto_rawDescData
}

var file_AccountService_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_AccountService_proto_goTypes = []any{
	(*TradingAccount)(nil),                         // 0: com.consorsbank.module.tapi.grpc.TradingAccount
	(*TradingAccountRequest)(nil),                  // 1: com.consorsbank.module.tapi.grpc.TradingAccountRequest
	(*TradingAccounts)(nil),                        // 2: com.consorsbank.module.tapi.grpc.TradingAccounts
	(*TradingAccountTransactions)(nil),             // 3: com.consorsbank.module.tapi.grpc.TradingAccountTransactions
	(*TradingAccountInformation)(nil),              // 4: com.consorsbank.module.tapi.grpc.TradingAccountInformation
	(*TradingAccountTransactions_Transaction)(nil), // 5: com.consorsbank.module.tapi.grpc.TradingAccountTransactions.Transaction
	(*Error)(nil),                                  // 6: com.consorsbank.module.tapi.grpc.Error
	(*Date)(nil),                                   // 7: com.consorsbank.module.tapi.grpc.Date
}
var file_AccountService_proto_depIdxs = []int32{
	0,  // 0: com.consorsbank.module.tapi.grpc.TradingAccountRequest.trading_account:type_name -> com.consorsbank.module.tapi.grpc.TradingAccount
	0,  // 1: com.consorsbank.module.tapi.grpc.TradingAccounts.accounts:type_name -> com.consorsbank.module.tapi.grpc.TradingAccount
	6,  // 2: com.consorsbank.module.tapi.grpc.TradingAccounts.error:type_name -> com.consorsbank.module.tapi.grpc.Error
	0,  // 3: com.consorsbank.module.tapi.grpc.TradingAccountTransactions.account:type_name -> com.consorsbank.module.tapi.grpc.TradingAccount
	5,  // 4: com.consorsbank.module.tapi.grpc.TradingAccountTransactions.transactions:type_name -> com.consorsbank.module.tapi.grpc.TradingAccountTransactions.Transaction
	6,  // 5: com.consorsbank.module.tapi.grpc.TradingAccountTransactions.error:type_name -> com.consorsbank.module.tapi.grpc.Error
	0,  // 6: com.consorsbank.module.tapi.grpc.TradingAccountInformation.account:type_name -> com.consorsbank.module.tapi.grpc.TradingAccount
	6,  // 7: com.consorsbank.module.tapi.grpc.TradingAccountInformation.error:type_name -> com.consorsbank.module.tapi.grpc.Error
	7,  // 8: com.consorsbank.module.tapi.grpc.TradingAccountTransactions.Transaction.transaction_date:type_name -> com.consorsbank.module.tapi.grpc.Date
	7,  // 9: com.consorsbank.module.tapi.grpc.TradingAccountTransactions.Transaction.value_date:type_name -> com.consorsbank.module.tapi.grpc.Date
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_AccountService_proto_init() }
func file_AccountService_proto_init() {
	if File_AccountService_proto != nil {
		return
	}
	file_Common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AccountService_proto_rawDesc), len(file_AccountService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AccountService_proto_goTypes,
		DependencyIndexes: file_AccountService_proto_depIdxs,
		MessageInfos:      file_AccountService_proto_msgTypes,
	}.Build()
	File_AccountService_proto = out.File
	file_AccountService_proto_goTypes = nil
	file_AccountService_proto_depIdxs = nil
}
