//
// Copyright 2018, Trading-API, Consorsbank.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: DepotService.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Depot posiotion contains information about
// one position in the depot
type DepotPosition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Ammount of the securities
	Amount float64 `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// *
	// Position identification
	PositionId string `protobuf:"bytes,2,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	// *
	// True if sell of the position is possible or false otherwise
	SellPossible bool `protobuf:"varint,3,opt,name=sell_possible,json=sellPossible,proto3" json:"sell_possible,omitempty"`
	// *
	// Unit note
	UnitNote UnitNote `protobuf:"varint,4,opt,name=unit_note,json=unitNote,proto3,enum=com.consorsbank.module.tapi.grpc.UnitNote" json:"unit_note,omitempty"`
	// *
	// True if entry is blocked or false otherwise
	Blocked bool `protobuf:"varint,5,opt,name=blocked,proto3" json:"blocked,omitempty"`
	// *
	// Purchase quotation or NaN if not defined.
	// Currently this field ALWAYS undefined, reserved for future use
	PurchaseQuotation float64 `protobuf:"fixed64,6,opt,name=purchase_quotation,json=purchaseQuotation,proto3" json:"purchase_quotation,omitempty"`
	// *
	// Purchase currency or empty value if not defined
	PurchaseCurrency string `protobuf:"bytes,7,opt,name=purchase_currency,json=purchaseCurrency,proto3" json:"purchase_currency,omitempty"`
	// *
	// Purchase currency rate or NaN if not defined
	PurchaseCurrencyRate float64 `protobuf:"fixed64,8,opt,name=purchase_currency_rate,json=purchaseCurrencyRate,proto3" json:"purchase_currency_rate,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DepotPosition) Reset() {
	*x = DepotPosition{}
	mi := &file_DepotService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepotPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepotPosition) ProtoMessage() {}

func (x *DepotPosition) ProtoReflect() protoreflect.Message {
	mi := &file_DepotService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepotPosition.ProtoReflect.Descriptor instead.
func (*DepotPosition) Descriptor() ([]byte, []int) {
	return file_DepotService_proto_rawDescGZIP(), []int{0}
}

func (x *DepotPosition) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DepotPosition) GetPositionId() string {
	if x != nil {
		return x.PositionId
	}
	return ""
}

func (x *DepotPosition) GetSellPossible() bool {
	if x != nil {
		return x.SellPossible
	}
	return false
}

func (x *DepotPosition) GetUnitNote() UnitNote {
	if x != nil {
		return x.UnitNote
	}
	return UnitNote_NO_UNIT_NOTE
}

func (x *DepotPosition) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

func (x *DepotPosition) GetPurchaseQuotation() float64 {
	if x != nil {
		return x.PurchaseQuotation
	}
	return 0
}

func (x *DepotPosition) GetPurchaseCurrency() string {
	if x != nil {
		return x.PurchaseCurrency
	}
	return ""
}

func (x *DepotPosition) GetPurchaseCurrencyRate() float64 {
	if x != nil {
		return x.PurchaseCurrencyRate
	}
	return 0
}

// *
// Depot entry contains information about one security in the depot.
// This entry combines data from one or more depot positions
type DepotEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Security code
	SecurityCode *SecurityCode `protobuf:"bytes,1,opt,name=security_code,json=securityCode,proto3" json:"security_code,omitempty"`
	// *
	// List of linked depot positions. This list contains at least one element
	Positions []*DepotPosition `protobuf:"bytes,2,rep,name=positions,proto3" json:"positions,omitempty"`
	// *
	// Effective amount
	EffectiveAmount float64 `protobuf:"fixed64,3,opt,name=effective_amount,json=effectiveAmount,proto3" json:"effective_amount,omitempty"`
	// *
	// Scheduled amount
	ScheduledAmount float64 `protobuf:"fixed64,4,opt,name=scheduled_amount,json=scheduledAmount,proto3" json:"scheduled_amount,omitempty"`
	// *
	// Total amount of the securities
	TotalAmount float64 `protobuf:"fixed64,5,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	// *
	// True if sell possible for this entry or false otherwise. This value
	// can be true only if all child positions have sell_possible = true
	SellPossible bool `protobuf:"varint,6,opt,name=sell_possible,json=sellPossible,proto3" json:"sell_possible,omitempty"`
	// *
	// Unit note
	UnitNote UnitNote `protobuf:"varint,7,opt,name=unit_note,json=unitNote,proto3,enum=com.consorsbank.module.tapi.grpc.UnitNote" json:"unit_note,omitempty"`
	// *
	// True if entry is blocked or false otherwise
	Blocked bool `protobuf:"varint,10,opt,name=blocked,proto3" json:"blocked,omitempty"`
	// *
	// Purchase quotation or NaN if not defined
	PurchaseQuotation float64 `protobuf:"fixed64,11,opt,name=purchase_quotation,json=purchaseQuotation,proto3" json:"purchase_quotation,omitempty"`
	// *
	// Purchase currency or empty value if not defined
	PurchaseCurrency string `protobuf:"bytes,12,opt,name=purchase_currency,json=purchaseCurrency,proto3" json:"purchase_currency,omitempty"`
	// *
	// Purchase currency rate or NaN if not defined
	PurchaseCurrencyRate float64 `protobuf:"fixed64,13,opt,name=purchase_currency_rate,json=purchaseCurrencyRate,proto3" json:"purchase_currency_rate,omitempty"`
	// *
	// Open sales
	OpenSales     float64 `protobuf:"fixed64,14,opt,name=open_sales,json=openSales,proto3" json:"open_sales,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepotEntry) Reset() {
	*x = DepotEntry{}
	mi := &file_DepotService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepotEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepotEntry) ProtoMessage() {}

func (x *DepotEntry) ProtoReflect() protoreflect.Message {
	mi := &file_DepotService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepotEntry.ProtoReflect.Descriptor instead.
func (*DepotEntry) Descriptor() ([]byte, []int) {
	return file_DepotService_proto_rawDescGZIP(), []int{1}
}

func (x *DepotEntry) GetSecurityCode() *SecurityCode {
	if x != nil {
		return x.SecurityCode
	}
	return nil
}

func (x *DepotEntry) GetPositions() []*DepotPosition {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *DepotEntry) GetEffectiveAmount() float64 {
	if x != nil {
		return x.EffectiveAmount
	}
	return 0
}

func (x *DepotEntry) GetScheduledAmount() float64 {
	if x != nil {
		return x.ScheduledAmount
	}
	return 0
}

func (x *DepotEntry) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *DepotEntry) GetSellPossible() bool {
	if x != nil {
		return x.SellPossible
	}
	return false
}

func (x *DepotEntry) GetUnitNote() UnitNote {
	if x != nil {
		return x.UnitNote
	}
	return UnitNote_NO_UNIT_NOTE
}

func (x *DepotEntry) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

func (x *DepotEntry) GetPurchaseQuotation() float64 {
	if x != nil {
		return x.PurchaseQuotation
	}
	return 0
}

func (x *DepotEntry) GetPurchaseCurrency() string {
	if x != nil {
		return x.PurchaseCurrency
	}
	return ""
}

func (x *DepotEntry) GetPurchaseCurrencyRate() float64 {
	if x != nil {
		return x.PurchaseCurrencyRate
	}
	return 0
}

func (x *DepotEntry) GetOpenSales() float64 {
	if x != nil {
		return x.OpenSales
	}
	return 0
}

type DepotEntries struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Trading account
	Account *TradingAccount `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// *
	// Depot entries list
	Entries []*DepotEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	// *
	// Error information if occuirs
	Error         *Error `protobuf:"bytes,1000,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepotEntries) Reset() {
	*x = DepotEntries{}
	mi := &file_DepotService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepotEntries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepotEntries) ProtoMessage() {}

func (x *DepotEntries) ProtoReflect() protoreflect.Message {
	mi := &file_DepotService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepotEntries.ProtoReflect.Descriptor instead.
func (*DepotEntries) Descriptor() ([]byte, []int) {
	return file_DepotService_proto_rawDescGZIP(), []int{2}
}

func (x *DepotEntries) GetAccount() *TradingAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *DepotEntries) GetEntries() []*DepotEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *DepotEntries) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_DepotService_proto protoreflect.FileDescriptor

const file_DepotService_proto_rawDesc = "" +
	"\n" +
	"\x12DepotService.proto\x12 com.consorsbank.module.tapi.grpc\x1a\fCommon.proto\x1a\x15SecurityService.proto\x1a\x14AccountService.proto\"\xe2\x02\n" +
	"\rDepotPosition\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12\x1f\n" +
	"\vposition_id\x18\x02 \x01(\tR\n" +
	"positionId\x12#\n" +
	"\rsell_possible\x18\x03 \x01(\bR\fsellPossible\x12G\n" +
	"\tunit_note\x18\x04 \x01(\x0e2*.com.consorsbank.module.tapi.grpc.UnitNoteR\bunitNote\x12\x18\n" +
	"\ablocked\x18\x05 \x01(\bR\ablocked\x12-\n" +
	"\x12purchase_quotation\x18\x06 \x01(\x01R\x11purchaseQuotation\x12+\n" +
	"\x11purchase_currency\x18\a \x01(\tR\x10purchaseCurrency\x124\n" +
	"\x16purchase_currency_rate\x18\b \x01(\x01R\x14purchaseCurrencyRate\"\xe2\x04\n" +
	"\n" +
	"DepotEntry\x12S\n" +
	"\rsecurity_code\x18\x01 \x01(\v2..com.consorsbank.module.tapi.grpc.SecurityCodeR\fsecurityCode\x12M\n" +
	"\tpositions\x18\x02 \x03(\v2/.com.consorsbank.module.tapi.grpc.DepotPositionR\tpositions\x12)\n" +
	"\x10effective_amount\x18\x03 \x01(\x01R\x0feffectiveAmount\x12)\n" +
	"\x10scheduled_amount\x18\x04 \x01(\x01R\x0fscheduledAmount\x12!\n" +
	"\ftotal_amount\x18\x05 \x01(\x01R\vtotalAmount\x12#\n" +
	"\rsell_possible\x18\x06 \x01(\bR\fsellPossible\x12G\n" +
	"\tunit_note\x18\a \x01(\x0e2*.com.consorsbank.module.tapi.grpc.UnitNoteR\bunitNote\x12\x18\n" +
	"\ablocked\x18\n" +
	" \x01(\bR\ablocked\x12-\n" +
	"\x12purchase_quotation\x18\v \x01(\x01R\x11purchaseQuotation\x12+\n" +
	"\x11purchase_currency\x18\f \x01(\tR\x10purchaseCurrency\x124\n" +
	"\x16purchase_currency_rate\x18\r \x01(\x01R\x14purchaseCurrencyRate\x12\x1d\n" +
	"\n" +
	"open_sales\x18\x0e \x01(\x01R\topenSales\"\xe2\x01\n" +
	"\fDepotEntries\x12J\n" +
	"\aaccount\x18\x01 \x01(\v20.com.consorsbank.module.tapi.grpc.TradingAccountR\aaccount\x12F\n" +
	"\aentries\x18\x02 \x03(\v2,.com.consorsbank.module.tapi.grpc.DepotEntryR\aentries\x12>\n" +
	"\x05error\x18\xe8\a \x01(\v2'.com.consorsbank.module.tapi.grpc.ErrorR\x05errorB*\n" +
	"&com.consorsbank.module.tapi.grpc.depotP\x01b\x06proto3"

var (
	file_DepotService_proto_rawDescOnce sync.Once
	file_DepotService_proto_rawDescData []byte
)

func file_DepotService_proto_rawDescGZIP() []byte {
	file_DepotService_proto_rawDescOnce.Do(func() {
		file_DepotService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_DepotService_proto_rawDesc), len(file_DepotService_proto_rawDesc)))
	})
	return file_DepotService_proto_rawDescData
}

var file_DepotService_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_DepotService_proto_goTypes = []any{
	(*DepotPosition)(nil),  // 0: com.consorsbank.module.tapi.grpc.DepotPosition
	(*DepotEntry)(nil),     // 1: com.consorsbank.module.tapi.grpc.DepotEntry
	(*DepotEntries)(nil),   // 2: com.consorsbank.module.tapi.grpc.DepotEntries
	(UnitNote)(0),          // 3: com.consorsbank.module.tapi.grpc.UnitNote
	(*SecurityCode)(nil),   // 4: com.consorsbank.module.tapi.grpc.SecurityCode
	(*TradingAccount)(nil), // 5: com.consorsbank.module.tapi.grpc.TradingAccount
	(*Error)(nil),          // 6: com.consorsbank.module.tapi.grpc.Error
}
var file_DepotService_proto_depIdxs = []int32{
	3, // 0: com.consorsbank.module.tapi.grpc.DepotPosition.unit_note:type_name -> com.consorsbank.module.tapi.grpc.UnitNote
	4, // 1: com.consorsbank.module.tapi.grpc.DepotEntry.security_code:type_name -> com.consorsbank.module.tapi.grpc.SecurityCode
	0, // 2: com.consorsbank.module.tapi.grpc.DepotEntry.positions:type_name -> com.consorsbank.module.tapi.grpc.DepotPosition
	3, // 3: com.consorsbank.module.tapi.grpc.DepotEntry.unit_note:type_name -> com.consorsbank.module.tapi.grpc.UnitNote
	5, // 4: com.consorsbank.module.tapi.grpc.DepotEntries.account:type_name -> com.consorsbank.module.tapi.grpc.TradingAccount
	1, // 5: com.consorsbank.module.tapi.grpc.DepotEntries.entries:type_name -> com.consorsbank.module.tapi.grpc.DepotEntry
	6, // 6: com.consorsbank.module.tapi.grpc.DepotEntries.error:type_name -> com.consorsbank.module.tapi.grpc.Error
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_DepotService_proto_init() }
func file_DepotService_proto_init() {
	if File_DepotService_proto != nil {
		return
	}
	file_Common_proto_init()
	file_SecurityService_proto_init()
	file_AccountService_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_DepotService_proto_rawDesc), len(file_DepotService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_DepotService_proto_goTypes,
		DependencyIndexes: file_DepotService_proto_depIdxs,
		MessageInfos:      file_DepotService_proto_msgTypes,
	}.Build()
	File_DepotService_proto = out.File
	file_DepotService_proto_goTypes = nil
	file_DepotService_proto_depIdxs = nil
}
