//
// Copyright 2018, Trading-API, Consorsbank.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: OrderService.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Order status represents status of the order
type OrderStatus int32

const (
	// * Status is not defined
	OrderStatus_NO_ORDER_STATUS OrderStatus = 0
	// * New order
	OrderStatus_NEW OrderStatus = 1
	// * Open order
	OrderStatus_OPEN OrderStatus = 2
	// * Fully executed order
	OrderStatus_EXECUTED OrderStatus = 3
	// * Partially executed order
	OrderStatus_PARTIALLY_EXECUTED OrderStatus = 4
	// * Canceled order
	OrderStatus_CANCELED OrderStatus = 5
	// * Canceled forced order
	OrderStatus_CANCELED_FORCED OrderStatus = 6
	// * Canceling noted order
	OrderStatus_CANCELED_NOTED OrderStatus = 7
	// * Canceling timeout order
	OrderStatus_CANCELED_TIMEOUT OrderStatus = 8
	// * Changed order
	OrderStatus_CHANGED OrderStatus = 9
	// * Changing noted order
	OrderStatus_CHANGED_NOTED OrderStatus = 10
	// * Inactive order #pro# only
	OrderStatus_INACTIVE OrderStatus = 11
	// * Inactivation noted order #pro# only
	OrderStatus_INACTIVE_NOTED OrderStatus = 12
	// * Storno order
	OrderStatus_STORNO OrderStatus = 13
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0:  "NO_ORDER_STATUS",
		1:  "NEW",
		2:  "OPEN",
		3:  "EXECUTED",
		4:  "PARTIALLY_EXECUTED",
		5:  "CANCELED",
		6:  "CANCELED_FORCED",
		7:  "CANCELED_NOTED",
		8:  "CANCELED_TIMEOUT",
		9:  "CHANGED",
		10: "CHANGED_NOTED",
		11: "INACTIVE",
		12: "INACTIVE_NOTED",
		13: "STORNO",
	}
	OrderStatus_value = map[string]int32{
		"NO_ORDER_STATUS":    0,
		"NEW":                1,
		"OPEN":               2,
		"EXECUTED":           3,
		"PARTIALLY_EXECUTED": 4,
		"CANCELED":           5,
		"CANCELED_FORCED":    6,
		"CANCELED_NOTED":     7,
		"CANCELED_TIMEOUT":   8,
		"CHANGED":            9,
		"CHANGED_NOTED":      10,
		"INACTIVE":           11,
		"INACTIVE_NOTED":     12,
		"STORNO":             13,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_OrderService_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_OrderService_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_OrderService_proto_rawDescGZIP(), []int{0}
}

// *
// Validation type for the order actions
type Validation int32

const (
	// *
	// Order action will routed directly to the market.
	Validation_WITHOUT_VALIDATION Validation = 0
	// *
	// Order will checked by the backend system, but not will be routed to market
	Validation_VALIDATE_ONLY Validation = 1
	// *
	// Order will checked by the backend system, but not will be routed to market.
	// Additionally will be requested estimated order action total costs.
	Validation_VALIDATE_WITH_TOTAL_COSTS Validation = 2
	// *
	// Order will checked by the backend system, but not will be routed to market.
	// Additionally will be requested estimated order action detail costs.
	Validation_VALIDATE_WITH_DETAIL_COSTS Validation = 3
	// *
	// For the order will be requested estimated order action total costs.
	// No backend system validation is processed.
	Validation_TOTAL_COSTS_ONLY Validation = 4
)

// Enum value maps for Validation.
var (
	Validation_name = map[int32]string{
		0: "WITHOUT_VALIDATION",
		1: "VALIDATE_ONLY",
		2: "VALIDATE_WITH_TOTAL_COSTS",
		3: "VALIDATE_WITH_DETAIL_COSTS",
		4: "TOTAL_COSTS_ONLY",
	}
	Validation_value = map[string]int32{
		"WITHOUT_VALIDATION":         0,
		"VALIDATE_ONLY":              1,
		"VALIDATE_WITH_TOTAL_COSTS":  2,
		"VALIDATE_WITH_DETAIL_COSTS": 3,
		"TOTAL_COSTS_ONLY":           4,
	}
)

func (x Validation) Enum() *Validation {
	p := new(Validation)
	*p = x
	return p
}

func (x Validation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Validation) Descriptor() protoreflect.EnumDescriptor {
	return file_OrderService_proto_enumTypes[1].Descriptor()
}

func (Validation) Type() protoreflect.EnumType {
	return &file_OrderService_proto_enumTypes[1]
}

func (x Validation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Validation.Descriptor instead.
func (Validation) EnumDescriptor() ([]byte, []int) {
	return file_OrderService_proto_rawDescGZIP(), []int{1}
}

// *
// Order represent one order object
type Order struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Security with stock echange
	SecurityWithStockexchange *SecurityWithStockExchange `protobuf:"bytes,1,opt,name=security_with_stockexchange,json=securityWithStockexchange,proto3" json:"security_with_stockexchange,omitempty"`
	// * Order type
	OrderType OrderType `protobuf:"varint,2,opt,name=order_type,json=orderType,proto3,enum=com.consorsbank.module.tapi.grpc.OrderType" json:"order_type,omitempty"`
	// * Order number
	OrderNumber string `protobuf:"bytes,3,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	// * Amount of the securities
	Amount float64 `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// * Order model
	OrderModel OrderModel `protobuf:"varint,5,opt,name=order_model,json=orderModel,proto3,enum=com.consorsbank.module.tapi.grpc.OrderModel" json:"order_model,omitempty"`
	// * Order supplement
	OrderSupplement OrderSupplement `protobuf:"varint,6,opt,name=order_supplement,json=orderSupplement,proto3,enum=com.consorsbank.module.tapi.grpc.OrderSupplement" json:"order_supplement,omitempty"`
	// * Cache quotation
	CashQuotation CashQuotation `protobuf:"varint,7,opt,name=cash_quotation,json=cashQuotation,proto3,enum=com.consorsbank.module.tapi.grpc.CashQuotation" json:"cash_quotation,omitempty"`
	// * Executed amount
	ExecutedAmount float64 `protobuf:"fixed64,8,opt,name=executed_amount,json=executedAmount,proto3" json:"executed_amount,omitempty"`
	// * Order status
	OrderStatus OrderStatus `protobuf:"varint,9,opt,name=order_status,json=orderStatus,proto3,enum=com.consorsbank.module.tapi.grpc.OrderStatus" json:"order_status,omitempty"`
	// * Date and time of the order status
	StatusTimestamp *Timestamp `protobuf:"bytes,10,opt,name=status_timestamp,json=statusTimestamp,proto3" json:"status_timestamp,omitempty"`
	// * Validity date of the order
	ValidityDate *Date `protobuf:"bytes,11,opt,name=validity_date,json=validityDate,proto3" json:"validity_date,omitempty"`
	// *
	// Limit value. Used as the order limit for all Limit order model with exception of the
	// StopLimit order model. For this order model please use stop limit field.
	Limit float64 `protobuf:"fixed64,12,opt,name=limit,proto3" json:"limit,omitempty"`
	// *
	// Stop value. This value can be used only together with StopMarket, StopLimit and OneCancelOter order models.
	Stop float64 `protobuf:"fixed64,13,opt,name=stop,proto3" json:"stop,omitempty"`
	// *
	// Stop limit value
	// Can be used only tigether with the StopLimit order model.
	// The meaning of the value is limit of the order after stop.
	StopLimit float64 `protobuf:"fixed64,14,opt,name=stop_limit,json=stopLimit,proto3" json:"stop_limit,omitempty"`
	// * Traling distance in traling notation units or empty value
	TrailingDistance float64 `protobuf:"fixed64,15,opt,name=trailing_distance,json=trailingDistance,proto3" json:"trailing_distance,omitempty"`
	// * Trailing notation for the trailing orders
	TrailingNotation TrailingNotation `protobuf:"varint,16,opt,name=trailing_notation,json=trailingNotation,proto3,enum=com.consorsbank.module.tapi.grpc.TrailingNotation" json:"trailing_notation,omitempty"`
	// * Trailing limit tolerance for the trailing orders
	TrailingLimitTolerance float64 `protobuf:"fixed64,17,opt,name=trailing_limit_tolerance,json=trailingLimitTolerance,proto3" json:"trailing_limit_tolerance,omitempty"`
	// * Dripping quantity #pro# only
	DrippingQuantity float64 `protobuf:"fixed64,18,opt,name=dripping_quantity,json=drippingQuantity,proto3" json:"dripping_quantity,omitempty"`
	// * Trading partner name
	TradingPartnerName string `protobuf:"bytes,19,opt,name=trading_partner_name,json=tradingPartnerName,proto3" json:"trading_partner_name,omitempty"`
	// * Execution quote for the executed amount
	ExecutionQuote float64 `protobuf:"fixed64,20,opt,name=execution_quote,json=executionQuote,proto3" json:"execution_quote,omitempty"`
	// *
	// Unique id of the order. Used for the order matching.
	// In the #pro# version of the ActiveTrader order_number can be changed after activation / deactivation.
	// All order activities need actual or delivered form the system order_number.
	// Typical scenario is to map and update unique id to the order number delivered from the API.
	UniqueId      string `protobuf:"bytes,21,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_OrderService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_OrderService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_OrderService_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetSecurityWithStockexchange() *SecurityWithStockExchange {
	if x != nil {
		return x.SecurityWithStockexchange
	}
	return nil
}

func (x *Order) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_NO_ORDER_TYPE
}

func (x *Order) GetOrderNumber() string {
	if x != nil {
		return x.OrderNumber
	}
	return ""
}

func (x *Order) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Order) GetOrderModel() OrderModel {
	if x != nil {
		return x.OrderModel
	}
	return OrderModel_NO_ORDER_MODEL
}

func (x *Order) GetOrderSupplement() OrderSupplement {
	if x != nil {
		return x.OrderSupplement
	}
	return OrderSupplement_NORMAL
}

func (x *Order) GetCashQuotation() CashQuotation {
	if x != nil {
		return x.CashQuotation
	}
	return CashQuotation_NOTHING
}

func (x *Order) GetExecutedAmount() float64 {
	if x != nil {
		return x.ExecutedAmount
	}
	return 0
}

func (x *Order) GetOrderStatus() OrderStatus {
	if x != nil {
		return x.OrderStatus
	}
	return OrderStatus_NO_ORDER_STATUS
}

func (x *Order) GetStatusTimestamp() *Timestamp {
	if x != nil {
		return x.StatusTimestamp
	}
	return nil
}

func (x *Order) GetValidityDate() *Date {
	if x != nil {
		return x.ValidityDate
	}
	return nil
}

func (x *Order) GetLimit() float64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Order) GetStop() float64 {
	if x != nil {
		return x.Stop
	}
	return 0
}

func (x *Order) GetStopLimit() float64 {
	if x != nil {
		return x.StopLimit
	}
	return 0
}

func (x *Order) GetTrailingDistance() float64 {
	if x != nil {
		return x.TrailingDistance
	}
	return 0
}

func (x *Order) GetTrailingNotation() TrailingNotation {
	if x != nil {
		return x.TrailingNotation
	}
	return TrailingNotation_NO_TRAILING_NOTATION
}

func (x *Order) GetTrailingLimitTolerance() float64 {
	if x != nil {
		return x.TrailingLimitTolerance
	}
	return 0
}

func (x *Order) GetDrippingQuantity() float64 {
	if x != nil {
		return x.DrippingQuantity
	}
	return 0
}

func (x *Order) GetTradingPartnerName() string {
	if x != nil {
		return x.TradingPartnerName
	}
	return ""
}

func (x *Order) GetExecutionQuote() float64 {
	if x != nil {
		return x.ExecutionQuote
	}
	return 0
}

func (x *Order) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

// *
// Add order request represents order data for the long term markets
type AddOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Access token
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// *
	// Trading account number which used for the execution
	AccountNumber string `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	// *
	// Security code with stock exchange
	SecurityWithStockexchange *SecurityWithStockExchange `protobuf:"bytes,3,opt,name=security_with_stockexchange,json=securityWithStockexchange,proto3" json:"security_with_stockexchange,omitempty"`
	// *
	// Order type
	OrderType OrderType `protobuf:"varint,4,opt,name=order_type,json=orderType,proto3,enum=com.consorsbank.module.tapi.grpc.OrderType" json:"order_type,omitempty"`
	// *
	// Amount of the securities
	Amount float64 `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	// *
	// Order model
	OrderModel OrderModel `protobuf:"varint,6,opt,name=order_model,json=orderModel,proto3,enum=com.consorsbank.module.tapi.grpc.OrderModel" json:"order_model,omitempty"`
	// *
	// Order supplement
	OrderSupplement OrderSupplement `protobuf:"varint,7,opt,name=order_supplement,json=orderSupplement,proto3,enum=com.consorsbank.module.tapi.grpc.OrderSupplement" json:"order_supplement,omitempty"`
	// *
	// Cach quotation
	CashQuotation CashQuotation `protobuf:"varint,8,opt,name=cash_quotation,json=cashQuotation,proto3,enum=com.consorsbank.module.tapi.grpc.CashQuotation" json:"cash_quotation,omitempty"`
	// *
	// Order validity date
	ValidityDate *Date `protobuf:"bytes,9,opt,name=validity_date,json=validityDate,proto3" json:"validity_date,omitempty"`
	// *
	// Limit value
	Limit float64 `protobuf:"fixed64,10,opt,name=limit,proto3" json:"limit,omitempty"`
	// *
	// Stop value. This value can be used only together with StopMarket, StopLimit and OneCancelOter order models.
	Stop float64 `protobuf:"fixed64,11,opt,name=stop,proto3" json:"stop,omitempty"`
	// *
	// Stop limit used in the StopLimit and OneCancelOther order models
	StopLimit float64 `protobuf:"fixed64,12,opt,name=stop_limit,json=stopLimit,proto3" json:"stop_limit,omitempty"`
	// *
	// Traling distance in traling notation units or empty value
	TrailingDistance float64 `protobuf:"fixed64,13,opt,name=trailing_distance,json=trailingDistance,proto3" json:"trailing_distance,omitempty"`
	// *
	// Trailing notation for the trailing orders
	TrailingNotation TrailingNotation `protobuf:"varint,14,opt,name=trailing_notation,json=trailingNotation,proto3,enum=com.consorsbank.module.tapi.grpc.TrailingNotation" json:"trailing_notation,omitempty"`
	// *
	// Trailing limit tolerance for the trailing orders
	TrailingLimitTolerance float64 `protobuf:"fixed64,15,opt,name=trailing_limit_tolerance,json=trailingLimitTolerance,proto3" json:"trailing_limit_tolerance,omitempty"`
	// *
	// Dripping quantity #pro# only
	DrippingQuantity float64 `protobuf:"fixed64,16,opt,name=dripping_quantity,json=drippingQuantity,proto3" json:"dripping_quantity,omitempty"`
	// *
	// Position id of the depot position.
	// It used only for sale certainly securities from depot
	PositionId string `protobuf:"bytes,17,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	// *
	// Validation flag.
	// If value is WITHOUT_VALIDATION then backend system sends order actions directly to the market. +
	// If value is VALIDATE_ONLY then backend system doesn't send order actions to the market, but validate order parameters. +
	// If value is VALIDATE_WITH_TOTAL_COSTS then order will validated by backend system and request total costs for the order. +
	// If value is VALIDATE_WITH_DETAIL_COSTS then order will validated by backend system and request detail costs for the order. +
	Validation Validation `protobuf:"varint,18,opt,name=validation,proto3,enum=com.consorsbank.module.tapi.grpc.Validation" json:"validation,omitempty"`
	// *
	// Risk class override flag. If true then allowes override user risk class
	RiskClassOverride bool `protobuf:"varint,19,opt,name=risk_class_override,json=riskClassOverride,proto3" json:"risk_class_override,omitempty"`
	// *
	// Target market override flag. If true then allowes override target market
	TargetMarketOverride bool `protobuf:"varint,20,opt,name=target_market_override,json=targetMarketOverride,proto3" json:"target_market_override,omitempty"`
	// *
	// Tax non trasparent override flag. If true then allowes override tax intransparesity
	TaxNontransparentOverride bool `protobuf:"varint,21,opt,name=tax_nontransparent_override,json=taxNontransparentOverride,proto3" json:"tax_nontransparent_override,omitempty"`
	// *
	// Accept additinal fees flag. If true then allowes accept non transparent fees
	AcceptAdditionalFees bool `protobuf:"varint,22,opt,name=accept_additional_fees,json=acceptAdditionalFees,proto3" json:"accept_additional_fees,omitempty"`
	// *
	// Closed realestate fond override. If true then allowes sell fonds over fds
	ClosedRealestateFondOverride bool `protobuf:"varint,23,opt,name=closed_realestate_fond_override,json=closedRealestateFondOverride,proto3" json:"closed_realestate_fond_override,omitempty"`
	// *
	// Inactive order flag, #pro# only. If true then order market as inactive and don't routed to the marker.
	// To activate order please use ActivateOrder function
	Inactive      bool `protobuf:"varint,24,opt,name=inactive,proto3" json:"inactive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrderRequest) Reset() {
	*x = AddOrderRequest{}
	mi := &file_OrderService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderRequest) ProtoMessage() {}

func (x *AddOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OrderService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderRequest.ProtoReflect.Descriptor instead.
func (*AddOrderRequest) Descriptor() ([]byte, []int) {
	return file_OrderService_proto_rawDescGZIP(), []int{1}
}

func (x *AddOrderRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AddOrderRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *AddOrderRequest) GetSecurityWithStockexchange() *SecurityWithStockExchange {
	if x != nil {
		return x.SecurityWithStockexchange
	}
	return nil
}

func (x *AddOrderRequest) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_NO_ORDER_TYPE
}

func (x *AddOrderRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AddOrderRequest) GetOrderModel() OrderModel {
	if x != nil {
		return x.OrderModel
	}
	return OrderModel_NO_ORDER_MODEL
}

func (x *AddOrderRequest) GetOrderSupplement() OrderSupplement {
	if x != nil {
		return x.OrderSupplement
	}
	return OrderSupplement_NORMAL
}

func (x *AddOrderRequest) GetCashQuotation() CashQuotation {
	if x != nil {
		return x.CashQuotation
	}
	return CashQuotation_NOTHING
}

func (x *AddOrderRequest) GetValidityDate() *Date {
	if x != nil {
		return x.ValidityDate
	}
	return nil
}

func (x *AddOrderRequest) GetLimit() float64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *AddOrderRequest) GetStop() float64 {
	if x != nil {
		return x.Stop
	}
	return 0
}

func (x *AddOrderRequest) GetStopLimit() float64 {
	if x != nil {
		return x.StopLimit
	}
	return 0
}

func (x *AddOrderRequest) GetTrailingDistance() float64 {
	if x != nil {
		return x.TrailingDistance
	}
	return 0
}

func (x *AddOrderRequest) GetTrailingNotation() TrailingNotation {
	if x != nil {
		return x.TrailingNotation
	}
	return TrailingNotation_NO_TRAILING_NOTATION
}

func (x *AddOrderRequest) GetTrailingLimitTolerance() float64 {
	if x != nil {
		return x.TrailingLimitTolerance
	}
	return 0
}

func (x *AddOrderRequest) GetDrippingQuantity() float64 {
	if x != nil {
		return x.DrippingQuantity
	}
	return 0
}

func (x *AddOrderRequest) GetPositionId() string {
	if x != nil {
		return x.PositionId
	}
	return ""
}

func (x *AddOrderRequest) GetValidation() Validation {
	if x != nil {
		return x.Validation
	}
	return Validation_WITHOUT_VALIDATION
}

func (x *AddOrderRequest) GetRiskClassOverride() bool {
	if x != nil {
		return x.RiskClassOverride
	}
	return false
}

func (x *AddOrderRequest) GetTargetMarketOverride() bool {
	if x != nil {
		return x.TargetMarketOverride
	}
	return false
}

func (x *AddOrderRequest) GetTaxNontransparentOverride() bool {
	if x != nil {
		return x.TaxNontransparentOverride
	}
	return false
}

func (x *AddOrderRequest) GetAcceptAdditionalFees() bool {
	if x != nil {
		return x.AcceptAdditionalFees
	}
	return false
}

func (x *AddOrderRequest) GetClosedRealestateFondOverride() bool {
	if x != nil {
		return x.ClosedRealestateFondOverride
	}
	return false
}

func (x *AddOrderRequest) GetInactive() bool {
	if x != nil {
		return x.Inactive
	}
	return false
}

// *
// Order reply represents result of the add order or accept quote requests
type OrderReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Trading account
	Account *TradingAccount `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// * Result order
	Order *Order `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	// *
	// Order costs. This field contains data if order costs are requested
	OrderCosts *OrderCosts `protobuf:"bytes,3,opt,name=order_costs,json=orderCosts,proto3" json:"order_costs,omitempty"`
	// *
	// Error information if occuirs
	Error         *Error `protobuf:"bytes,1000,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderReply) Reset() {
	*x = OrderReply{}
	mi := &file_OrderService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderReply) ProtoMessage() {}

func (x *OrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_OrderService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderReply.ProtoReflect.Descriptor instead.
func (*OrderReply) Descriptor() ([]byte, []int) {
	return file_OrderService_proto_rawDescGZIP(), []int{2}
}

func (x *OrderReply) GetAccount() *TradingAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *OrderReply) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *OrderReply) GetOrderCosts() *OrderCosts {
	if x != nil {
		return x.OrderCosts
	}
	return nil
}

func (x *OrderReply) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// *
// Order costs represents information about order action estimated costs.
// This information is only *estimated values* and is depended from real execution quotes, time, etc.
type OrderCosts struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Estimated total cost for order action
	EstimatedTotalCosts float64 `protobuf:"fixed64,1,opt,name=estimated_total_costs,json=estimatedTotalCosts,proto3" json:"estimated_total_costs,omitempty"`
	// *
	// Reference backend cost id
	CostId string `protobuf:"bytes,2,opt,name=cost_id,json=costId,proto3" json:"cost_id,omitempty"`
	// *
	// List of the cost categories.  Filled only by validation request with detailed information.
	CategorieCosts []*OrderCosts_CategoryCost `protobuf:"bytes,3,rep,name=categorie_costs,json=categorieCosts,proto3" json:"categorie_costs,omitempty"`
	// *
	// Aggregated costs for the order.  Filled only by validation request with validation information.
	AggregatedCosts *OrderCosts_AggregatedCosts `protobuf:"bytes,4,opt,name=aggregated_costs,json=aggregatedCosts,proto3" json:"aggregated_costs,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OrderCosts) Reset() {
	*x = OrderCosts{}
	mi := &file_OrderService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCosts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCosts) ProtoMessage() {}

func (x *OrderCosts) ProtoReflect() protoreflect.Message {
	mi := &file_OrderService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCosts.ProtoReflect.Descriptor instead.
func (*OrderCosts) Descriptor() ([]byte, []int) {
	return file_OrderService_proto_rawDescGZIP(), []int{3}
}

func (x *OrderCosts) GetEstimatedTotalCosts() float64 {
	if x != nil {
		return x.EstimatedTotalCosts
	}
	return 0
}

func (x *OrderCosts) GetCostId() string {
	if x != nil {
		return x.CostId
	}
	return ""
}

func (x *OrderCosts) GetCategorieCosts() []*OrderCosts_CategoryCost {
	if x != nil {
		return x.CategorieCosts
	}
	return nil
}

func (x *OrderCosts) GetAggregatedCosts() *OrderCosts_AggregatedCosts {
	if x != nil {
		return x.AggregatedCosts
	}
	return nil
}

// *
// Change order request contains parameters for the order change.
// Be careful: not all combinations are possible.
type ChangeOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Access token
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// *
	// Trading account number
	AccountNumber string `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	// *
	// Order number for that this changes should be accepted
	OrderNumber string `protobuf:"bytes,3,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	// *
	// New limit, shouldn't filled for market order
	Limit float64 `protobuf:"fixed64,4,opt,name=limit,proto3" json:"limit,omitempty"`
	// *
	// New stop value
	Stop float64 `protobuf:"fixed64,5,opt,name=stop,proto3" json:"stop,omitempty"`
	// *
	// New stop limit value
	StopLimit float64 `protobuf:"fixed64,6,opt,name=stop_limit,json=stopLimit,proto3" json:"stop_limit,omitempty"`
	// *
	// New amount
	Amount float64 `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	// *
	// New validity date
	ValidityDate *Date `protobuf:"bytes,8,opt,name=validity_date,json=validityDate,proto3" json:"validity_date,omitempty"`
	// *
	// New order model
	OrderModel OrderModel `protobuf:"varint,9,opt,name=order_model,json=orderModel,proto3,enum=com.consorsbank.module.tapi.grpc.OrderModel" json:"order_model,omitempty"`
	// *
	// New order supplement
	OrderSupplement OrderSupplement `protobuf:"varint,10,opt,name=order_supplement,json=orderSupplement,proto3,enum=com.consorsbank.module.tapi.grpc.OrderSupplement" json:"order_supplement,omitempty"`
	// *
	// Dripping quantity #pro# only
	DrippingQuantity float64 `protobuf:"fixed64,11,opt,name=dripping_quantity,json=drippingQuantity,proto3" json:"dripping_quantity,omitempty"`
	// *
	// Validation flag. This request allowes only *WITHOUT_VALIDATION*
	// and *VALIDATE_ONLY* values. +
	// If value is WITHOUT_VALIDATION then backend system sends order actions directly to the market. +
	// If value is VALIDATE_ONLY then backend system doesn't send order actions to the market, but validate order parameters.
	Validation Validation `protobuf:"varint,12,opt,name=validation,proto3,enum=com.consorsbank.module.tapi.grpc.Validation" json:"validation,omitempty"`
	// *
	// New trailing distance
	TrailingDistance float64 `protobuf:"fixed64,13,opt,name=trailing_distance,json=trailingDistance,proto3" json:"trailing_distance,omitempty"`
	// *
	// New traling limit tolerance
	TrailingLimitTolerance float64 `protobuf:"fixed64,14,opt,name=trailing_limit_tolerance,json=trailingLimitTolerance,proto3" json:"trailing_limit_tolerance,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ChangeOrderRequest) Reset() {
	*x = ChangeOrderRequest{}
	mi := &file_OrderService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeOrderRequest) ProtoMessage() {}

func (x *ChangeOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OrderService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeOrderRequest.ProtoReflect.Descriptor instead.
func (*ChangeOrderRequest) Descriptor() ([]byte, []int) {
	return file_OrderService_proto_rawDescGZIP(), []int{4}
}

func (x *ChangeOrderRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ChangeOrderRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *ChangeOrderRequest) GetOrderNumber() string {
	if x != nil {
		return x.OrderNumber
	}
	return ""
}

func (x *ChangeOrderRequest) GetLimit() float64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ChangeOrderRequest) GetStop() float64 {
	if x != nil {
		return x.Stop
	}
	return 0
}

func (x *ChangeOrderRequest) GetStopLimit() float64 {
	if x != nil {
		return x.StopLimit
	}
	return 0
}

func (x *ChangeOrderRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ChangeOrderRequest) GetValidityDate() *Date {
	if x != nil {
		return x.ValidityDate
	}
	return nil
}

func (x *ChangeOrderRequest) GetOrderModel() OrderModel {
	if x != nil {
		return x.OrderModel
	}
	return OrderModel_NO_ORDER_MODEL
}

func (x *ChangeOrderRequest) GetOrderSupplement() OrderSupplement {
	if x != nil {
		return x.OrderSupplement
	}
	return OrderSupplement_NORMAL
}

func (x *ChangeOrderRequest) GetDrippingQuantity() float64 {
	if x != nil {
		return x.DrippingQuantity
	}
	return 0
}

func (x *ChangeOrderRequest) GetValidation() Validation {
	if x != nil {
		return x.Validation
	}
	return Validation_WITHOUT_VALIDATION
}

func (x *ChangeOrderRequest) GetTrailingDistance() float64 {
	if x != nil {
		return x.TrailingDistance
	}
	return 0
}

func (x *ChangeOrderRequest) GetTrailingLimitTolerance() float64 {
	if x != nil {
		return x.TrailingLimitTolerance
	}
	return 0
}

// *
// Cancel order request represents canceling information for one order on the market or one inactive order
type CancelOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Access token
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// *
	// Trading account number
	AccountNumber string `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	// *
	// Order number for that this changes should be accepted
	OrderNumber string `protobuf:"bytes,3,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	// *
	// Validation flag. This request allowes only *WITHOUT_VALIDATION* value. +
	// If value is WITHOUT_VALIDATION then backend system sends order actions directly to the market. +
	// Otherwise request will fail.
	Validation    Validation `protobuf:"varint,4,opt,name=validation,proto3,enum=com.consorsbank.module.tapi.grpc.Validation" json:"validation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_OrderService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OrderService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_OrderService_proto_rawDescGZIP(), []int{5}
}

func (x *CancelOrderRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *CancelOrderRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *CancelOrderRequest) GetOrderNumber() string {
	if x != nil {
		return x.OrderNumber
	}
	return ""
}

func (x *CancelOrderRequest) GetValidation() Validation {
	if x != nil {
		return x.Validation
	}
	return Validation_WITHOUT_VALIDATION
}

// *
// Activate order request represents information for activation of one inactive order #pro# only
type ActivateOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Access token
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// *
	// Trading account number
	AccountNumber string `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	// *
	// Order number for that this changes should be accepted
	OrderNumber string `protobuf:"bytes,3,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	// *
	// Validation flag. This request allowes only *WITHOUT_VALIDATION*
	// and *VALIDATE_ONLY* values. +
	// If value is WITHOUT_VALIDATION then backend system sends order actions directly to the market. +
	// If value is VALIDATE_ONLY then backend system doesn't send order actions to the market, but validate order parameters.
	Validation    Validation `protobuf:"varint,4,opt,name=validation,proto3,enum=com.consorsbank.module.tapi.grpc.Validation" json:"validation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateOrderRequest) Reset() {
	*x = ActivateOrderRequest{}
	mi := &file_OrderService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateOrderRequest) ProtoMessage() {}

func (x *ActivateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OrderService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateOrderRequest.ProtoReflect.Descriptor instead.
func (*ActivateOrderRequest) Descriptor() ([]byte, []int) {
	return file_OrderService_proto_rawDescGZIP(), []int{6}
}

func (x *ActivateOrderRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ActivateOrderRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *ActivateOrderRequest) GetOrderNumber() string {
	if x != nil {
		return x.OrderNumber
	}
	return ""
}

func (x *ActivateOrderRequest) GetValidation() Validation {
	if x != nil {
		return x.Validation
	}
	return Validation_WITHOUT_VALIDATION
}

// *
// Deactivate order request represents information for deactivation of one active order #pro# only
type DeactivateOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Access token
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// *
	// Trading account number
	AccountNumber string `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	// *
	// Order number for that this changes should be accepted
	OrderNumber string `protobuf:"bytes,3,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	// *
	// Validation flag. This request allowes only *WITHOUT_VALIDATION*
	// and *VALIDATE_ONLY* values.
	// If value is WITHOUT_VALIDATION then backend system sends order actions directly to the market.
	// If value is VALIDATE_ONLY then backend system doesn't send order actions to the market, but validate order parameters
	Validation    Validation `protobuf:"varint,4,opt,name=validation,proto3,enum=com.consorsbank.module.tapi.grpc.Validation" json:"validation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateOrderRequest) Reset() {
	*x = DeactivateOrderRequest{}
	mi := &file_OrderService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateOrderRequest) ProtoMessage() {}

func (x *DeactivateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OrderService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateOrderRequest.ProtoReflect.Descriptor instead.
func (*DeactivateOrderRequest) Descriptor() ([]byte, []int) {
	return file_OrderService_proto_rawDescGZIP(), []int{7}
}

func (x *DeactivateOrderRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *DeactivateOrderRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *DeactivateOrderRequest) GetOrderNumber() string {
	if x != nil {
		return x.OrderNumber
	}
	return ""
}

func (x *DeactivateOrderRequest) GetValidation() Validation {
	if x != nil {
		return x.Validation
	}
	return Validation_WITHOUT_VALIDATION
}

// *
// Accept quote request represents information about one order that should be placed on the short term market
type AcceptQuoteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Access token
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// *
	// Trading account number
	AccountNumber string `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	// *
	// Security code with stock exchange
	SecurityWithStockexchange *SecurityWithStockExchange `protobuf:"bytes,3,opt,name=security_with_stockexchange,json=securityWithStockexchange,proto3" json:"security_with_stockexchange,omitempty"`
	// *
	// Order type. It should be relevant to the requested GetQuoteRequest
	OrderType OrderType `protobuf:"varint,4,opt,name=order_type,json=orderType,proto3,enum=com.consorsbank.module.tapi.grpc.OrderType" json:"order_type,omitempty"`
	// *
	// Amount, It should be relevant to the requested GetQuoteRequest
	Amount float64 `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	// *
	// Limit
	Limit float64 `protobuf:"fixed64,6,opt,name=limit,proto3" json:"limit,omitempty"`
	// *
	// Quote reference from GetQuoteRequest
	QuoteReference string `protobuf:"bytes,7,opt,name=quote_reference,json=quoteReference,proto3" json:"quote_reference,omitempty"`
	// *
	// Validation flag.
	// If value is WITHOUT_VALIDATION then backend system sends order actions directly to the market. +
	// If value is VALIDATE_ONLY then backend system doesn't send order actions to the market, but validate order parameters. +
	// If value is VALIDATE_WITH_TOTAL_COSTS then order will validated by backend system and request total costs for the order. +
	// If value is VALIDATE_WITH_DETAIL_COSTS then order will validated by backend system and request detail costs for the order. +
	Validation Validation `protobuf:"varint,8,opt,name=validation,proto3,enum=com.consorsbank.module.tapi.grpc.Validation" json:"validation,omitempty"`
	// *
	// Risk class override flag. If true then allowes override user risk class
	RiskClassOverride bool `protobuf:"varint,9,opt,name=risk_class_override,json=riskClassOverride,proto3" json:"risk_class_override,omitempty"`
	// *
	// Target market override flag. If true then allowes override target market
	TargetMarketOverride bool `protobuf:"varint,10,opt,name=target_market_override,json=targetMarketOverride,proto3" json:"target_market_override,omitempty"`
	// *
	// Tax non trasparent override flag. If true then allowes override tax intransparesity
	TaxNontransparentOverride bool `protobuf:"varint,11,opt,name=tax_nontransparent_override,json=taxNontransparentOverride,proto3" json:"tax_nontransparent_override,omitempty"`
	// *
	// Accept additinal fees flag. If true then allowes accept non transparent fees
	AcceptAdditionalFees bool `protobuf:"varint,12,opt,name=accept_additional_fees,json=acceptAdditionalFees,proto3" json:"accept_additional_fees,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AcceptQuoteRequest) Reset() {
	*x = AcceptQuoteRequest{}
	mi := &file_OrderService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptQuoteRequest) ProtoMessage() {}

func (x *AcceptQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OrderService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptQuoteRequest.ProtoReflect.Descriptor instead.
func (*AcceptQuoteRequest) Descriptor() ([]byte, []int) {
	return file_OrderService_proto_rawDescGZIP(), []int{8}
}

func (x *AcceptQuoteRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AcceptQuoteRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *AcceptQuoteRequest) GetSecurityWithStockexchange() *SecurityWithStockExchange {
	if x != nil {
		return x.SecurityWithStockexchange
	}
	return nil
}

func (x *AcceptQuoteRequest) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_NO_ORDER_TYPE
}

func (x *AcceptQuoteRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AcceptQuoteRequest) GetLimit() float64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *AcceptQuoteRequest) GetQuoteReference() string {
	if x != nil {
		return x.QuoteReference
	}
	return ""
}

func (x *AcceptQuoteRequest) GetValidation() Validation {
	if x != nil {
		return x.Validation
	}
	return Validation_WITHOUT_VALIDATION
}

func (x *AcceptQuoteRequest) GetRiskClassOverride() bool {
	if x != nil {
		return x.RiskClassOverride
	}
	return false
}

func (x *AcceptQuoteRequest) GetTargetMarketOverride() bool {
	if x != nil {
		return x.TargetMarketOverride
	}
	return false
}

func (x *AcceptQuoteRequest) GetTaxNontransparentOverride() bool {
	if x != nil {
		return x.TaxNontransparentOverride
	}
	return false
}

func (x *AcceptQuoteRequest) GetAcceptAdditionalFees() bool {
	if x != nil {
		return x.AcceptAdditionalFees
	}
	return false
}

// *
// Quote request represents data to get information about actual quotes on the selected makets
type QuoteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Access token
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// *
	// Security code
	SecurityCode *SecurityCode `protobuf:"bytes,2,opt,name=security_code,json=securityCode,proto3" json:"security_code,omitempty"`
	// *
	// Order type. Only BUY or SELL are allowed
	OrderType OrderType `protobuf:"varint,3,opt,name=order_type,json=orderType,proto3,enum=com.consorsbank.module.tapi.grpc.OrderType" json:"order_type,omitempty"`
	// *
	// Amount of securities. Relevant to the short term markets
	Amount float64 `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// *
	// List of stock exchanges
	StockExchanges []*StockExchange `protobuf:"bytes,5,rep,name=stock_exchanges,json=stockExchanges,proto3" json:"stock_exchanges,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QuoteRequest) Reset() {
	*x = QuoteRequest{}
	mi := &file_OrderService_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteRequest) ProtoMessage() {}

func (x *QuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OrderService_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteRequest.ProtoReflect.Descriptor instead.
func (*QuoteRequest) Descriptor() ([]byte, []int) {
	return file_OrderService_proto_rawDescGZIP(), []int{9}
}

func (x *QuoteRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *QuoteRequest) GetSecurityCode() *SecurityCode {
	if x != nil {
		return x.SecurityCode
	}
	return nil
}

func (x *QuoteRequest) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_NO_ORDER_TYPE
}

func (x *QuoteRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *QuoteRequest) GetStockExchanges() []*StockExchange {
	if x != nil {
		return x.StockExchanges
	}
	return nil
}

// *
// Quote reply represents data with quote answers from requested markets
type QuoteReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Security code
	SecurityCode *SecurityCode `protobuf:"bytes,1,opt,name=security_code,json=securityCode,proto3" json:"security_code,omitempty"`
	// * Order type
	OrderType OrderType `protobuf:"varint,2,opt,name=order_type,json=orderType,proto3,enum=com.consorsbank.module.tapi.grpc.OrderType" json:"order_type,omitempty"`
	// * List of the quites
	PriceEntries []*QuoteEntry `protobuf:"bytes,3,rep,name=price_entries,json=priceEntries,proto3" json:"price_entries,omitempty"`
	// *
	// Error information if occuirs
	Error         *Error `protobuf:"bytes,1000,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteReply) Reset() {
	*x = QuoteReply{}
	mi := &file_OrderService_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteReply) ProtoMessage() {}

func (x *QuoteReply) ProtoReflect() protoreflect.Message {
	mi := &file_OrderService_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteReply.ProtoReflect.Descriptor instead.
func (*QuoteReply) Descriptor() ([]byte, []int) {
	return file_OrderService_proto_rawDescGZIP(), []int{10}
}

func (x *QuoteReply) GetSecurityCode() *SecurityCode {
	if x != nil {
		return x.SecurityCode
	}
	return nil
}

func (x *QuoteReply) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_NO_ORDER_TYPE
}

func (x *QuoteReply) GetPriceEntries() []*QuoteEntry {
	if x != nil {
		return x.PriceEntries
	}
	return nil
}

func (x *QuoteReply) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// *
// Quote entry represents one answer with quote information from one stock exchange
// This reply contains both buy and sell price. The quote reference can be used only with requested order type.
//
//	Second value is present only for information goals.
//
//	     order type: BUY ->  quote reference for buy price and reference,
//	                         sell price and reference are informative only
//	     order type: SELL -> quote reference for sell price and reference,
//	                         buy price and reference are informative only
type QuoteEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Stock exchange where infomation was requested
	StockExchange *StockExchange `protobuf:"bytes,1,opt,name=stock_exchange,json=stockExchange,proto3" json:"stock_exchange,omitempty"`
	// * Buy price
	BuyPrice float64 `protobuf:"fixed64,2,opt,name=buy_price,json=buyPrice,proto3" json:"buy_price,omitempty"`
	// * Buy volume
	BuyVolume float64 `protobuf:"fixed64,3,opt,name=buy_volume,json=buyVolume,proto3" json:"buy_volume,omitempty"`
	// * Sell price
	SellPrice float64 `protobuf:"fixed64,4,opt,name=sell_price,json=sellPrice,proto3" json:"sell_price,omitempty"`
	// * Sell volume
	SellVolume float64 `protobuf:"fixed64,5,opt,name=sell_volume,json=sellVolume,proto3" json:"sell_volume,omitempty"`
	// * Last price
	LastPrice float64 `protobuf:"fixed64,6,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`
	// * Last volume
	LastVolume float64 `protobuf:"fixed64,7,opt,name=last_volume,json=lastVolume,proto3" json:"last_volume,omitempty"`
	// * Date and time of the last price
	LastTime *Timestamp `protobuf:"bytes,8,opt,name=last_time,json=lastTime,proto3" json:"last_time,omitempty"`
	// * Currency
	Currency string `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	// * Quote reference. Used for the accept quite request. Can be empty if accept quote is not possible.
	QuoteReference string `protobuf:"bytes,10,opt,name=quote_reference,json=quoteReference,proto3" json:"quote_reference,omitempty"`
	// * Used by call order type
	OrderType OrderType `protobuf:"varint,11,opt,name=order_type,json=orderType,proto3,enum=com.consorsbank.module.tapi.grpc.OrderType" json:"order_type,omitempty"`
	// *
	// Error information if occuirs
	Error         *Error `protobuf:"bytes,1000,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteEntry) Reset() {
	*x = QuoteEntry{}
	mi := &file_OrderService_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteEntry) ProtoMessage() {}

func (x *QuoteEntry) ProtoReflect() protoreflect.Message {
	mi := &file_OrderService_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteEntry.ProtoReflect.Descriptor instead.
func (*QuoteEntry) Descriptor() ([]byte, []int) {
	return file_OrderService_proto_rawDescGZIP(), []int{11}
}

func (x *QuoteEntry) GetStockExchange() *StockExchange {
	if x != nil {
		return x.StockExchange
	}
	return nil
}

func (x *QuoteEntry) GetBuyPrice() float64 {
	if x != nil {
		return x.BuyPrice
	}
	return 0
}

func (x *QuoteEntry) GetBuyVolume() float64 {
	if x != nil {
		return x.BuyVolume
	}
	return 0
}

func (x *QuoteEntry) GetSellPrice() float64 {
	if x != nil {
		return x.SellPrice
	}
	return 0
}

func (x *QuoteEntry) GetSellVolume() float64 {
	if x != nil {
		return x.SellVolume
	}
	return 0
}

func (x *QuoteEntry) GetLastPrice() float64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

func (x *QuoteEntry) GetLastVolume() float64 {
	if x != nil {
		return x.LastVolume
	}
	return 0
}

func (x *QuoteEntry) GetLastTime() *Timestamp {
	if x != nil {
		return x.LastTime
	}
	return nil
}

func (x *QuoteEntry) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *QuoteEntry) GetQuoteReference() string {
	if x != nil {
		return x.QuoteReference
	}
	return ""
}

func (x *QuoteEntry) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_NO_ORDER_TYPE
}

func (x *QuoteEntry) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// *
// Orders represent pushed information about orders from one trading accounts
type Orders struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Trading account
	Account *TradingAccount `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// * List of the orders
	Orders []*Order `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	// *
	// Error information if occuirs
	Error         *Error `protobuf:"bytes,9000,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Orders) Reset() {
	*x = Orders{}
	mi := &file_OrderService_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Orders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Orders) ProtoMessage() {}

func (x *Orders) ProtoReflect() protoreflect.Message {
	mi := &file_OrderService_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Orders.ProtoReflect.Descriptor instead.
func (*Orders) Descriptor() ([]byte, []int) {
	return file_OrderService_proto_rawDescGZIP(), []int{12}
}

func (x *Orders) GetAccount() *TradingAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *Orders) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *Orders) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// *
// Represents one category cost.
type OrderCosts_CategoryCost struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Category id
	CategoryId string `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	// *
	// Human redable category label
	CategoryLabel string `protobuf:"bytes,2,opt,name=category_label,json=categoryLabel,proto3" json:"category_label,omitempty"`
	// *
	// Total absolute sum of the children values
	TotalSumAbsolute float64 `protobuf:"fixed64,3,opt,name=total_sum_absolute,json=totalSumAbsolute,proto3" json:"total_sum_absolute,omitempty"`
	// *
	// Total relative sum of the children values
	TotalSumRelative float64 `protobuf:"fixed64,4,opt,name=total_sum_relative,json=totalSumRelative,proto3" json:"total_sum_relative,omitempty"`
	// *
	// Currency for absolute sum
	Currency string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	// *
	// List of child values or detailed information.
	DetailCosts   []*OrderCosts_DetailCost `protobuf:"bytes,6,rep,name=detail_costs,json=detailCosts,proto3" json:"detail_costs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCosts_CategoryCost) Reset() {
	*x = OrderCosts_CategoryCost{}
	mi := &file_OrderService_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCosts_CategoryCost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCosts_CategoryCost) ProtoMessage() {}

func (x *OrderCosts_CategoryCost) ProtoReflect() protoreflect.Message {
	mi := &file_OrderService_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCosts_CategoryCost.ProtoReflect.Descriptor instead.
func (*OrderCosts_CategoryCost) Descriptor() ([]byte, []int) {
	return file_OrderService_proto_rawDescGZIP(), []int{3, 0}
}

func (x *OrderCosts_CategoryCost) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *OrderCosts_CategoryCost) GetCategoryLabel() string {
	if x != nil {
		return x.CategoryLabel
	}
	return ""
}

func (x *OrderCosts_CategoryCost) GetTotalSumAbsolute() float64 {
	if x != nil {
		return x.TotalSumAbsolute
	}
	return 0
}

func (x *OrderCosts_CategoryCost) GetTotalSumRelative() float64 {
	if x != nil {
		return x.TotalSumRelative
	}
	return 0
}

func (x *OrderCosts_CategoryCost) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *OrderCosts_CategoryCost) GetDetailCosts() []*OrderCosts_DetailCost {
	if x != nil {
		return x.DetailCosts
	}
	return nil
}

// *
// Aggregated costs contain an information about estimated costs for the selected order
type OrderCosts_AggregatedCosts struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// In costs for the order
	InCostsAbsolute float64 `protobuf:"fixed64,1,opt,name=in_costs_absolute,json=inCostsAbsolute,proto3" json:"in_costs_absolute,omitempty"`
	// *
	// Percentage part of the in costs
	InCostsRelative float64 `protobuf:"fixed64,2,opt,name=in_costs_relative,json=inCostsRelative,proto3" json:"in_costs_relative,omitempty"`
	// *
	// Currency for the in costs
	InCostsCurrency string `protobuf:"bytes,3,opt,name=in_costs_currency,json=inCostsCurrency,proto3" json:"in_costs_currency,omitempty"`
	// *
	// Out costs for the order
	OutCostsAbsolute float64 `protobuf:"fixed64,4,opt,name=out_costs_absolute,json=outCostsAbsolute,proto3" json:"out_costs_absolute,omitempty"`
	// *
	// Percentage part of the out costs
	OutCostsRelative float64 `protobuf:"fixed64,5,opt,name=out_costs_relative,json=outCostsRelative,proto3" json:"out_costs_relative,omitempty"`
	// *
	// Currency for the out costs
	OutCostsCurrency string `protobuf:"bytes,6,opt,name=out_costs_currency,json=outCostsCurrency,proto3" json:"out_costs_currency,omitempty"`
	// *
	// Instrument costs for the order
	InstrumentCostsAbsolute float64 `protobuf:"fixed64,7,opt,name=instrument_costs_absolute,json=instrumentCostsAbsolute,proto3" json:"instrument_costs_absolute,omitempty"`
	// *
	// Percentage part of the instrument costs
	InstrumentCostsRelative float64 `protobuf:"fixed64,8,opt,name=instrument_costs_relative,json=instrumentCostsRelative,proto3" json:"instrument_costs_relative,omitempty"`
	// *
	// Currency for the instrument costs
	InstrumentCostsCurrency string `protobuf:"bytes,9,opt,name=instrument_costs_currency,json=instrumentCostsCurrency,proto3" json:"instrument_costs_currency,omitempty"`
	// *
	// Service costs for the order
	ServiceCostsAbsolute float64 `protobuf:"fixed64,10,opt,name=service_costs_absolute,json=serviceCostsAbsolute,proto3" json:"service_costs_absolute,omitempty"`
	// *
	// Percentage part of the service costs
	ServiceCostsRelative float64 `protobuf:"fixed64,11,opt,name=service_costs_relative,json=serviceCostsRelative,proto3" json:"service_costs_relative,omitempty"`
	// *
	// Currency for the servcie costs
	ServiceCostsCurrency string `protobuf:"bytes,12,opt,name=service_costs_currency,json=serviceCostsCurrency,proto3" json:"service_costs_currency,omitempty"`
	// *
	// Subsidy costs for the order
	SubsidyCostsAbsolute float64 `protobuf:"fixed64,13,opt,name=subsidy_costs_absolute,json=subsidyCostsAbsolute,proto3" json:"subsidy_costs_absolute,omitempty"`
	// *
	// Percentage part of the subsidy costs
	SubsidyCostsRelative float64 `protobuf:"fixed64,14,opt,name=subsidy_costs_relative,json=subsidyCostsRelative,proto3" json:"subsidy_costs_relative,omitempty"`
	// *
	// Currency for the subsidy costs
	SubsidyCostsCurrency string `protobuf:"bytes,15,opt,name=subsidy_costs_currency,json=subsidyCostsCurrency,proto3" json:"subsidy_costs_currency,omitempty"`
	// *
	// Foreign currency costs for the order
	ForeignCurrencyCostsAbsolute float64 `protobuf:"fixed64,16,opt,name=foreign_currency_costs_absolute,json=foreignCurrencyCostsAbsolute,proto3" json:"foreign_currency_costs_absolute,omitempty"`
	// *
	// Percentage part of the foreign currency costs
	ForeignCurrencyCostsRelative float64 `protobuf:"fixed64,17,opt,name=foreign_currency_costs_relative,json=foreignCurrencyCostsRelative,proto3" json:"foreign_currency_costs_relative,omitempty"`
	// *
	// Currency for the foreign currency costs
	ForeignCurrencyCostsCurrency string `protobuf:"bytes,18,opt,name=foreign_currency_costs_currency,json=foreignCurrencyCostsCurrency,proto3" json:"foreign_currency_costs_currency,omitempty"`
	// *
	// Performance impact for the order
	PerformanceImpactAbsolute float64 `protobuf:"fixed64,19,opt,name=performance_impact_absolute,json=performanceImpactAbsolute,proto3" json:"performance_impact_absolute,omitempty"`
	// *
	// Percentage part of the performance impact
	PerformanceImpactRelative float64 `protobuf:"fixed64,20,opt,name=performance_impact_relative,json=performanceImpactRelative,proto3" json:"performance_impact_relative,omitempty"`
	// *
	// Currency for the performance impact
	PerformanceImpactCurrency string `protobuf:"bytes,21,opt,name=performance_impact_currency,json=performanceImpactCurrency,proto3" json:"performance_impact_currency,omitempty"`
	// *
	// Expected amount estimated for the order
	ExpectedAmount float64 `protobuf:"fixed64,22,opt,name=expected_amount,json=expectedAmount,proto3" json:"expected_amount,omitempty"`
	// *
	// Currency for the expected amount
	ExpectedAmountCurrency string `protobuf:"bytes,23,opt,name=expected_amount_currency,json=expectedAmountCurrency,proto3" json:"expected_amount_currency,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OrderCosts_AggregatedCosts) Reset() {
	*x = OrderCosts_AggregatedCosts{}
	mi := &file_OrderService_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCosts_AggregatedCosts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCosts_AggregatedCosts) ProtoMessage() {}

func (x *OrderCosts_AggregatedCosts) ProtoReflect() protoreflect.Message {
	mi := &file_OrderService_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCosts_AggregatedCosts.ProtoReflect.Descriptor instead.
func (*OrderCosts_AggregatedCosts) Descriptor() ([]byte, []int) {
	return file_OrderService_proto_rawDescGZIP(), []int{3, 1}
}

func (x *OrderCosts_AggregatedCosts) GetInCostsAbsolute() float64 {
	if x != nil {
		return x.InCostsAbsolute
	}
	return 0
}

func (x *OrderCosts_AggregatedCosts) GetInCostsRelative() float64 {
	if x != nil {
		return x.InCostsRelative
	}
	return 0
}

func (x *OrderCosts_AggregatedCosts) GetInCostsCurrency() string {
	if x != nil {
		return x.InCostsCurrency
	}
	return ""
}

func (x *OrderCosts_AggregatedCosts) GetOutCostsAbsolute() float64 {
	if x != nil {
		return x.OutCostsAbsolute
	}
	return 0
}

func (x *OrderCosts_AggregatedCosts) GetOutCostsRelative() float64 {
	if x != nil {
		return x.OutCostsRelative
	}
	return 0
}

func (x *OrderCosts_AggregatedCosts) GetOutCostsCurrency() string {
	if x != nil {
		return x.OutCostsCurrency
	}
	return ""
}

func (x *OrderCosts_AggregatedCosts) GetInstrumentCostsAbsolute() float64 {
	if x != nil {
		return x.InstrumentCostsAbsolute
	}
	return 0
}

func (x *OrderCosts_AggregatedCosts) GetInstrumentCostsRelative() float64 {
	if x != nil {
		return x.InstrumentCostsRelative
	}
	return 0
}

func (x *OrderCosts_AggregatedCosts) GetInstrumentCostsCurrency() string {
	if x != nil {
		return x.InstrumentCostsCurrency
	}
	return ""
}

func (x *OrderCosts_AggregatedCosts) GetServiceCostsAbsolute() float64 {
	if x != nil {
		return x.ServiceCostsAbsolute
	}
	return 0
}

func (x *OrderCosts_AggregatedCosts) GetServiceCostsRelative() float64 {
	if x != nil {
		return x.ServiceCostsRelative
	}
	return 0
}

func (x *OrderCosts_AggregatedCosts) GetServiceCostsCurrency() string {
	if x != nil {
		return x.ServiceCostsCurrency
	}
	return ""
}

func (x *OrderCosts_AggregatedCosts) GetSubsidyCostsAbsolute() float64 {
	if x != nil {
		return x.SubsidyCostsAbsolute
	}
	return 0
}

func (x *OrderCosts_AggregatedCosts) GetSubsidyCostsRelative() float64 {
	if x != nil {
		return x.SubsidyCostsRelative
	}
	return 0
}

func (x *OrderCosts_AggregatedCosts) GetSubsidyCostsCurrency() string {
	if x != nil {
		return x.SubsidyCostsCurrency
	}
	return ""
}

func (x *OrderCosts_AggregatedCosts) GetForeignCurrencyCostsAbsolute() float64 {
	if x != nil {
		return x.ForeignCurrencyCostsAbsolute
	}
	return 0
}

func (x *OrderCosts_AggregatedCosts) GetForeignCurrencyCostsRelative() float64 {
	if x != nil {
		return x.ForeignCurrencyCostsRelative
	}
	return 0
}

func (x *OrderCosts_AggregatedCosts) GetForeignCurrencyCostsCurrency() string {
	if x != nil {
		return x.ForeignCurrencyCostsCurrency
	}
	return ""
}

func (x *OrderCosts_AggregatedCosts) GetPerformanceImpactAbsolute() float64 {
	if x != nil {
		return x.PerformanceImpactAbsolute
	}
	return 0
}

func (x *OrderCosts_AggregatedCosts) GetPerformanceImpactRelative() float64 {
	if x != nil {
		return x.PerformanceImpactRelative
	}
	return 0
}

func (x *OrderCosts_AggregatedCosts) GetPerformanceImpactCurrency() string {
	if x != nil {
		return x.PerformanceImpactCurrency
	}
	return ""
}

func (x *OrderCosts_AggregatedCosts) GetExpectedAmount() float64 {
	if x != nil {
		return x.ExpectedAmount
	}
	return 0
}

func (x *OrderCosts_AggregatedCosts) GetExpectedAmountCurrency() string {
	if x != nil {
		return x.ExpectedAmountCurrency
	}
	return ""
}

// *
// Detail cost contains one entry for the selected
// category
type OrderCosts_DetailCost struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Detail id
	DetailId string `protobuf:"bytes,1,opt,name=detail_id,json=detailId,proto3" json:"detail_id,omitempty"`
	// *
	// Human redable detail label
	DetailLabel string `protobuf:"bytes,2,opt,name=detail_label,json=detailLabel,proto3" json:"detail_label,omitempty"`
	// *
	// Absolute value for this entry
	ValueAbsolute float64 `protobuf:"fixed64,3,opt,name=value_absolute,json=valueAbsolute,proto3" json:"value_absolute,omitempty"`
	// *
	// Relative value for this entry
	ValueRelative float64 `protobuf:"fixed64,4,opt,name=value_relative,json=valueRelative,proto3" json:"value_relative,omitempty"`
	// *
	// Currency for this entry
	Currency string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	// *
	// Specific entry type
	DetailType    string `protobuf:"bytes,6,opt,name=detail_type,json=detailType,proto3" json:"detail_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCosts_DetailCost) Reset() {
	*x = OrderCosts_DetailCost{}
	mi := &file_OrderService_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCosts_DetailCost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCosts_DetailCost) ProtoMessage() {}

func (x *OrderCosts_DetailCost) ProtoReflect() protoreflect.Message {
	mi := &file_OrderService_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCosts_DetailCost.ProtoReflect.Descriptor instead.
func (*OrderCosts_DetailCost) Descriptor() ([]byte, []int) {
	return file_OrderService_proto_rawDescGZIP(), []int{3, 2}
}

func (x *OrderCosts_DetailCost) GetDetailId() string {
	if x != nil {
		return x.DetailId
	}
	return ""
}

func (x *OrderCosts_DetailCost) GetDetailLabel() string {
	if x != nil {
		return x.DetailLabel
	}
	return ""
}

func (x *OrderCosts_DetailCost) GetValueAbsolute() float64 {
	if x != nil {
		return x.ValueAbsolute
	}
	return 0
}

func (x *OrderCosts_DetailCost) GetValueRelative() float64 {
	if x != nil {
		return x.ValueRelative
	}
	return 0
}

func (x *OrderCosts_DetailCost) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *OrderCosts_DetailCost) GetDetailType() string {
	if x != nil {
		return x.DetailType
	}
	return ""
}

var File_OrderService_proto protoreflect.FileDescriptor

const file_OrderService_proto_rawDesc = "" +
	"\n" +
	"\x12OrderService.proto\x12 com.consorsbank.module.tapi.grpc\x1a\fCommon.proto\x1a\x15SecurityService.proto\x1a\x1aStockExchangeService.proto\x1a\x14AccountService.proto\x1a\x12TradingTypes.proto\"\xe6\t\n" +
	"\x05Order\x12{\n" +
	"\x1bsecurity_with_stockexchange\x18\x01 \x01(\v2;.com.consorsbank.module.tapi.grpc.SecurityWithStockExchangeR\x19securityWithStockexchange\x12J\n" +
	"\n" +
	"order_type\x18\x02 \x01(\x0e2+.com.consorsbank.module.tapi.grpc.OrderTypeR\torderType\x12!\n" +
	"\forder_number\x18\x03 \x01(\tR\vorderNumber\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12M\n" +
	"\vorder_model\x18\x05 \x01(\x0e2,.com.consorsbank.module.tapi.grpc.OrderModelR\n" +
	"orderModel\x12\\\n" +
	"\x10order_supplement\x18\x06 \x01(\x0e21.com.consorsbank.module.tapi.grpc.OrderSupplementR\x0forderSupplement\x12V\n" +
	"\x0ecash_quotation\x18\a \x01(\x0e2/.com.consorsbank.module.tapi.grpc.CashQuotationR\rcashQuotation\x12'\n" +
	"\x0fexecuted_amount\x18\b \x01(\x01R\x0eexecutedAmount\x12P\n" +
	"\forder_status\x18\t \x01(\x0e2-.com.consorsbank.module.tapi.grpc.OrderStatusR\vorderStatus\x12V\n" +
	"\x10status_timestamp\x18\n" +
	" \x01(\v2+.com.consorsbank.module.tapi.grpc.TimestampR\x0fstatusTimestamp\x12K\n" +
	"\rvalidity_date\x18\v \x01(\v2&.com.consorsbank.module.tapi.grpc.DateR\fvalidityDate\x12\x14\n" +
	"\x05limit\x18\f \x01(\x01R\x05limit\x12\x12\n" +
	"\x04stop\x18\r \x01(\x01R\x04stop\x12\x1d\n" +
	"\n" +
	"stop_limit\x18\x0e \x01(\x01R\tstopLimit\x12+\n" +
	"\x11trailing_distance\x18\x0f \x01(\x01R\x10trailingDistance\x12_\n" +
	"\x11trailing_notation\x18\x10 \x01(\x0e22.com.consorsbank.module.tapi.grpc.TrailingNotationR\x10trailingNotation\x128\n" +
	"\x18trailing_limit_tolerance\x18\x11 \x01(\x01R\x16trailingLimitTolerance\x12+\n" +
	"\x11dripping_quantity\x18\x12 \x01(\x01R\x10drippingQuantity\x120\n" +
	"\x14trading_partner_name\x18\x13 \x01(\tR\x12tradingPartnerName\x12'\n" +
	"\x0fexecution_quote\x18\x14 \x01(\x01R\x0eexecutionQuote\x12\x1b\n" +
	"\tunique_id\x18\x15 \x01(\tR\buniqueId\"\xfa\n" +
	"\n" +
	"\x0fAddOrderRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\tR\raccountNumber\x12{\n" +
	"\x1bsecurity_with_stockexchange\x18\x03 \x01(\v2;.com.consorsbank.module.tapi.grpc.SecurityWithStockExchangeR\x19securityWithStockexchange\x12J\n" +
	"\n" +
	"order_type\x18\x04 \x01(\x0e2+.com.consorsbank.module.tapi.grpc.OrderTypeR\torderType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12M\n" +
	"\vorder_model\x18\x06 \x01(\x0e2,.com.consorsbank.module.tapi.grpc.OrderModelR\n" +
	"orderModel\x12\\\n" +
	"\x10order_supplement\x18\a \x01(\x0e21.com.consorsbank.module.tapi.grpc.OrderSupplementR\x0forderSupplement\x12V\n" +
	"\x0ecash_quotation\x18\b \x01(\x0e2/.com.consorsbank.module.tapi.grpc.CashQuotationR\rcashQuotation\x12K\n" +
	"\rvalidity_date\x18\t \x01(\v2&.com.consorsbank.module.tapi.grpc.DateR\fvalidityDate\x12\x14\n" +
	"\x05limit\x18\n" +
	" \x01(\x01R\x05limit\x12\x12\n" +
	"\x04stop\x18\v \x01(\x01R\x04stop\x12\x1d\n" +
	"\n" +
	"stop_limit\x18\f \x01(\x01R\tstopLimit\x12+\n" +
	"\x11trailing_distance\x18\r \x01(\x01R\x10trailingDistance\x12_\n" +
	"\x11trailing_notation\x18\x0e \x01(\x0e22.com.consorsbank.module.tapi.grpc.TrailingNotationR\x10trailingNotation\x128\n" +
	"\x18trailing_limit_tolerance\x18\x0f \x01(\x01R\x16trailingLimitTolerance\x12+\n" +
	"\x11dripping_quantity\x18\x10 \x01(\x01R\x10drippingQuantity\x12\x1f\n" +
	"\vposition_id\x18\x11 \x01(\tR\n" +
	"positionId\x12L\n" +
	"\n" +
	"validation\x18\x12 \x01(\x0e2,.com.consorsbank.module.tapi.grpc.ValidationR\n" +
	"validation\x12.\n" +
	"\x13risk_class_override\x18\x13 \x01(\bR\x11riskClassOverride\x124\n" +
	"\x16target_market_override\x18\x14 \x01(\bR\x14targetMarketOverride\x12>\n" +
	"\x1btax_nontransparent_override\x18\x15 \x01(\bR\x19taxNontransparentOverride\x124\n" +
	"\x16accept_additional_fees\x18\x16 \x01(\bR\x14acceptAdditionalFees\x12E\n" +
	"\x1fclosed_realestate_fond_override\x18\x17 \x01(\bR\x1cclosedRealestateFondOverride\x12\x1a\n" +
	"\binactive\x18\x18 \x01(\bR\binactive\"\xa6\x02\n" +
	"\n" +
	"OrderReply\x12J\n" +
	"\aaccount\x18\x01 \x01(\v20.com.consorsbank.module.tapi.grpc.TradingAccountR\aaccount\x12=\n" +
	"\x05order\x18\x02 \x01(\v2'.com.consorsbank.module.tapi.grpc.OrderR\x05order\x12M\n" +
	"\vorder_costs\x18\x03 \x01(\v2,.com.consorsbank.module.tapi.grpc.OrderCostsR\n" +
	"orderCosts\x12>\n" +
	"\x05error\x18\xe8\a \x01(\v2'.com.consorsbank.module.tapi.grpc.ErrorR\x05error\"\xbf\x10\n" +
	"\n" +
	"OrderCosts\x122\n" +
	"\x15estimated_total_costs\x18\x01 \x01(\x01R\x13estimatedTotalCosts\x12\x17\n" +
	"\acost_id\x18\x02 \x01(\tR\x06costId\x12b\n" +
	"\x0fcategorie_costs\x18\x03 \x03(\v29.com.consorsbank.module.tapi.grpc.OrderCosts.CategoryCostR\x0ecategorieCosts\x12g\n" +
	"\x10aggregated_costs\x18\x04 \x01(\v2<.com.consorsbank.module.tapi.grpc.OrderCosts.AggregatedCostsR\x0faggregatedCosts\x1a\xaa\x02\n" +
	"\fCategoryCost\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x12%\n" +
	"\x0ecategory_label\x18\x02 \x01(\tR\rcategoryLabel\x12,\n" +
	"\x12total_sum_absolute\x18\x03 \x01(\x01R\x10totalSumAbsolute\x12,\n" +
	"\x12total_sum_relative\x18\x04 \x01(\x01R\x10totalSumRelative\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12Z\n" +
	"\fdetail_costs\x18\x06 \x03(\v27.com.consorsbank.module.tapi.grpc.OrderCosts.DetailCostR\vdetailCosts\x1a\x8f\n" +
	"\n" +
	"\x0fAggregatedCosts\x12*\n" +
	"\x11in_costs_absolute\x18\x01 \x01(\x01R\x0finCostsAbsolute\x12*\n" +
	"\x11in_costs_relative\x18\x02 \x01(\x01R\x0finCostsRelative\x12*\n" +
	"\x11in_costs_currency\x18\x03 \x01(\tR\x0finCostsCurrency\x12,\n" +
	"\x12out_costs_absolute\x18\x04 \x01(\x01R\x10outCostsAbsolute\x12,\n" +
	"\x12out_costs_relative\x18\x05 \x01(\x01R\x10outCostsRelative\x12,\n" +
	"\x12out_costs_currency\x18\x06 \x01(\tR\x10outCostsCurrency\x12:\n" +
	"\x19instrument_costs_absolute\x18\a \x01(\x01R\x17instrumentCostsAbsolute\x12:\n" +
	"\x19instrument_costs_relative\x18\b \x01(\x01R\x17instrumentCostsRelative\x12:\n" +
	"\x19instrument_costs_currency\x18\t \x01(\tR\x17instrumentCostsCurrency\x124\n" +
	"\x16service_costs_absolute\x18\n" +
	" \x01(\x01R\x14serviceCostsAbsolute\x124\n" +
	"\x16service_costs_relative\x18\v \x01(\x01R\x14serviceCostsRelative\x124\n" +
	"\x16service_costs_currency\x18\f \x01(\tR\x14serviceCostsCurrency\x124\n" +
	"\x16subsidy_costs_absolute\x18\r \x01(\x01R\x14subsidyCostsAbsolute\x124\n" +
	"\x16subsidy_costs_relative\x18\x0e \x01(\x01R\x14subsidyCostsRelative\x124\n" +
	"\x16subsidy_costs_currency\x18\x0f \x01(\tR\x14subsidyCostsCurrency\x12E\n" +
	"\x1fforeign_currency_costs_absolute\x18\x10 \x01(\x01R\x1cforeignCurrencyCostsAbsolute\x12E\n" +
	"\x1fforeign_currency_costs_relative\x18\x11 \x01(\x01R\x1cforeignCurrencyCostsRelative\x12E\n" +
	"\x1fforeign_currency_costs_currency\x18\x12 \x01(\tR\x1cforeignCurrencyCostsCurrency\x12>\n" +
	"\x1bperformance_impact_absolute\x18\x13 \x01(\x01R\x19performanceImpactAbsolute\x12>\n" +
	"\x1bperformance_impact_relative\x18\x14 \x01(\x01R\x19performanceImpactRelative\x12>\n" +
	"\x1bperformance_impact_currency\x18\x15 \x01(\tR\x19performanceImpactCurrency\x12'\n" +
	"\x0fexpected_amount\x18\x16 \x01(\x01R\x0eexpectedAmount\x128\n" +
	"\x18expected_amount_currency\x18\x17 \x01(\tR\x16expectedAmountCurrency\x1a\xd7\x01\n" +
	"\n" +
	"DetailCost\x12\x1b\n" +
	"\tdetail_id\x18\x01 \x01(\tR\bdetailId\x12!\n" +
	"\fdetail_label\x18\x02 \x01(\tR\vdetailLabel\x12%\n" +
	"\x0evalue_absolute\x18\x03 \x01(\x01R\rvalueAbsolute\x12%\n" +
	"\x0evalue_relative\x18\x04 \x01(\x01R\rvalueRelative\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1f\n" +
	"\vdetail_type\x18\x06 \x01(\tR\n" +
	"detailType\"\xbe\x05\n" +
	"\x12ChangeOrderRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\tR\raccountNumber\x12!\n" +
	"\forder_number\x18\x03 \x01(\tR\vorderNumber\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x01R\x05limit\x12\x12\n" +
	"\x04stop\x18\x05 \x01(\x01R\x04stop\x12\x1d\n" +
	"\n" +
	"stop_limit\x18\x06 \x01(\x01R\tstopLimit\x12\x16\n" +
	"\x06amount\x18\a \x01(\x01R\x06amount\x12K\n" +
	"\rvalidity_date\x18\b \x01(\v2&.com.consorsbank.module.tapi.grpc.DateR\fvalidityDate\x12M\n" +
	"\vorder_model\x18\t \x01(\x0e2,.com.consorsbank.module.tapi.grpc.OrderModelR\n" +
	"orderModel\x12\\\n" +
	"\x10order_supplement\x18\n" +
	" \x01(\x0e21.com.consorsbank.module.tapi.grpc.OrderSupplementR\x0forderSupplement\x12+\n" +
	"\x11dripping_quantity\x18\v \x01(\x01R\x10drippingQuantity\x12L\n" +
	"\n" +
	"validation\x18\f \x01(\x0e2,.com.consorsbank.module.tapi.grpc.ValidationR\n" +
	"validation\x12+\n" +
	"\x11trailing_distance\x18\r \x01(\x01R\x10trailingDistance\x128\n" +
	"\x18trailing_limit_tolerance\x18\x0e \x01(\x01R\x16trailingLimitTolerance\"\xcf\x01\n" +
	"\x12CancelOrderRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\tR\raccountNumber\x12!\n" +
	"\forder_number\x18\x03 \x01(\tR\vorderNumber\x12L\n" +
	"\n" +
	"validation\x18\x04 \x01(\x0e2,.com.consorsbank.module.tapi.grpc.ValidationR\n" +
	"validation\"\xd1\x01\n" +
	"\x14ActivateOrderRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\tR\raccountNumber\x12!\n" +
	"\forder_number\x18\x03 \x01(\tR\vorderNumber\x12L\n" +
	"\n" +
	"validation\x18\x04 \x01(\x0e2,.com.consorsbank.module.tapi.grpc.ValidationR\n" +
	"validation\"\xd3\x01\n" +
	"\x16DeactivateOrderRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\tR\raccountNumber\x12!\n" +
	"\forder_number\x18\x03 \x01(\tR\vorderNumber\x12L\n" +
	"\n" +
	"validation\x18\x04 \x01(\x0e2,.com.consorsbank.module.tapi.grpc.ValidationR\n" +
	"validation\"\xa8\x05\n" +
	"\x12AcceptQuoteRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\tR\raccountNumber\x12{\n" +
	"\x1bsecurity_with_stockexchange\x18\x03 \x01(\v2;.com.consorsbank.module.tapi.grpc.SecurityWithStockExchangeR\x19securityWithStockexchange\x12J\n" +
	"\n" +
	"order_type\x18\x04 \x01(\x0e2+.com.consorsbank.module.tapi.grpc.OrderTypeR\torderType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x01R\x05limit\x12'\n" +
	"\x0fquote_reference\x18\a \x01(\tR\x0equoteReference\x12L\n" +
	"\n" +
	"validation\x18\b \x01(\x0e2,.com.consorsbank.module.tapi.grpc.ValidationR\n" +
	"validation\x12.\n" +
	"\x13risk_class_override\x18\t \x01(\bR\x11riskClassOverride\x124\n" +
	"\x16target_market_override\x18\n" +
	" \x01(\bR\x14targetMarketOverride\x12>\n" +
	"\x1btax_nontransparent_override\x18\v \x01(\bR\x19taxNontransparentOverride\x124\n" +
	"\x16accept_additional_fees\x18\f \x01(\bR\x14acceptAdditionalFees\"\xc4\x02\n" +
	"\fQuoteRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12S\n" +
	"\rsecurity_code\x18\x02 \x01(\v2..com.consorsbank.module.tapi.grpc.SecurityCodeR\fsecurityCode\x12J\n" +
	"\n" +
	"order_type\x18\x03 \x01(\x0e2+.com.consorsbank.module.tapi.grpc.OrderTypeR\torderType\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12X\n" +
	"\x0fstock_exchanges\x18\x05 \x03(\v2/.com.consorsbank.module.tapi.grpc.StockExchangeR\x0estockExchanges\"\xc0\x02\n" +
	"\n" +
	"QuoteReply\x12S\n" +
	"\rsecurity_code\x18\x01 \x01(\v2..com.consorsbank.module.tapi.grpc.SecurityCodeR\fsecurityCode\x12J\n" +
	"\n" +
	"order_type\x18\x02 \x01(\x0e2+.com.consorsbank.module.tapi.grpc.OrderTypeR\torderType\x12Q\n" +
	"\rprice_entries\x18\x03 \x03(\v2,.com.consorsbank.module.tapi.grpc.QuoteEntryR\fpriceEntries\x12>\n" +
	"\x05error\x18\xe8\a \x01(\v2'.com.consorsbank.module.tapi.grpc.ErrorR\x05error\"\xbb\x04\n" +
	"\n" +
	"QuoteEntry\x12V\n" +
	"\x0estock_exchange\x18\x01 \x01(\v2/.com.consorsbank.module.tapi.grpc.StockExchangeR\rstockExchange\x12\x1b\n" +
	"\tbuy_price\x18\x02 \x01(\x01R\bbuyPrice\x12\x1d\n" +
	"\n" +
	"buy_volume\x18\x03 \x01(\x01R\tbuyVolume\x12\x1d\n" +
	"\n" +
	"sell_price\x18\x04 \x01(\x01R\tsellPrice\x12\x1f\n" +
	"\vsell_volume\x18\x05 \x01(\x01R\n" +
	"sellVolume\x12\x1d\n" +
	"\n" +
	"last_price\x18\x06 \x01(\x01R\tlastPrice\x12\x1f\n" +
	"\vlast_volume\x18\a \x01(\x01R\n" +
	"lastVolume\x12H\n" +
	"\tlast_time\x18\b \x01(\v2+.com.consorsbank.module.tapi.grpc.TimestampR\blastTime\x12\x1a\n" +
	"\bcurrency\x18\t \x01(\tR\bcurrency\x12'\n" +
	"\x0fquote_reference\x18\n" +
	" \x01(\tR\x0equoteReference\x12J\n" +
	"\n" +
	"order_type\x18\v \x01(\x0e2+.com.consorsbank.module.tapi.grpc.OrderTypeR\torderType\x12>\n" +
	"\x05error\x18\xe8\a \x01(\v2'.com.consorsbank.module.tapi.grpc.ErrorR\x05error\"\xd5\x01\n" +
	"\x06Orders\x12J\n" +
	"\aaccount\x18\x01 \x01(\v20.com.consorsbank.module.tapi.grpc.TradingAccountR\aaccount\x12?\n" +
	"\x06orders\x18\x02 \x03(\v2'.com.consorsbank.module.tapi.grpc.OrderR\x06orders\x12>\n" +
	"\x05error\x18\xa8F \x01(\v2'.com.consorsbank.module.tapi.grpc.ErrorR\x05error*\xf6\x01\n" +
	"\vOrderStatus\x12\x13\n" +
	"\x0fNO_ORDER_STATUS\x10\x00\x12\a\n" +
	"\x03NEW\x10\x01\x12\b\n" +
	"\x04OPEN\x10\x02\x12\f\n" +
	"\bEXECUTED\x10\x03\x12\x16\n" +
	"\x12PARTIALLY_EXECUTED\x10\x04\x12\f\n" +
	"\bCANCELED\x10\x05\x12\x13\n" +
	"\x0fCANCELED_FORCED\x10\x06\x12\x12\n" +
	"\x0eCANCELED_NOTED\x10\a\x12\x14\n" +
	"\x10CANCELED_TIMEOUT\x10\b\x12\v\n" +
	"\aCHANGED\x10\t\x12\x11\n" +
	"\rCHANGED_NOTED\x10\n" +
	"\x12\f\n" +
	"\bINACTIVE\x10\v\x12\x12\n" +
	"\x0eINACTIVE_NOTED\x10\f\x12\n" +
	"\n" +
	"\x06STORNO\x10\r*\x8c\x01\n" +
	"\n" +
	"Validation\x12\x16\n" +
	"\x12WITHOUT_VALIDATION\x10\x00\x12\x11\n" +
	"\rVALIDATE_ONLY\x10\x01\x12\x1d\n" +
	"\x19VALIDATE_WITH_TOTAL_COSTS\x10\x02\x12\x1e\n" +
	"\x1aVALIDATE_WITH_DETAIL_COSTS\x10\x03\x12\x14\n" +
	"\x10TOTAL_COSTS_ONLY\x10\x04B*\n" +
	"&com.consorsbank.module.tapi.grpc.orderP\x01b\x06proto3"

var (
	file_OrderService_proto_rawDescOnce sync.Once
	file_OrderService_proto_rawDescData []byte
)

func file_OrderService_proto_rawDescGZIP() []byte {
	file_OrderService_proto_rawDescOnce.Do(func() {
		file_OrderService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_OrderService_proto_rawDesc), len(file_OrderService_proto_rawDesc)))
	})
	return file_OrderService_proto_rawDescData
}

var file_OrderService_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_OrderService_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_OrderService_proto_goTypes = []any{
	(OrderStatus)(0),                   // 0: com.consorsbank.module.tapi.grpc.OrderStatus
	(Validation)(0),                    // 1: com.consorsbank.module.tapi.grpc.Validation
	(*Order)(nil),                      // 2: com.consorsbank.module.tapi.grpc.Order
	(*AddOrderRequest)(nil),            // 3: com.consorsbank.module.tapi.grpc.AddOrderRequest
	(*OrderReply)(nil),                 // 4: com.consorsbank.module.tapi.grpc.OrderReply
	(*OrderCosts)(nil),                 // 5: com.consorsbank.module.tapi.grpc.OrderCosts
	(*ChangeOrderRequest)(nil),         // 6: com.consorsbank.module.tapi.grpc.ChangeOrderRequest
	(*CancelOrderRequest)(nil),         // 7: com.consorsbank.module.tapi.grpc.CancelOrderRequest
	(*ActivateOrderRequest)(nil),       // 8: com.consorsbank.module.tapi.grpc.ActivateOrderRequest
	(*DeactivateOrderRequest)(nil),     // 9: com.consorsbank.module.tapi.grpc.DeactivateOrderRequest
	(*AcceptQuoteRequest)(nil),         // 10: com.consorsbank.module.tapi.grpc.AcceptQuoteRequest
	(*QuoteRequest)(nil),               // 11: com.consorsbank.module.tapi.grpc.QuoteRequest
	(*QuoteReply)(nil),                 // 12: com.consorsbank.module.tapi.grpc.QuoteReply
	(*QuoteEntry)(nil),                 // 13: com.consorsbank.module.tapi.grpc.QuoteEntry
	(*Orders)(nil),                     // 14: com.consorsbank.module.tapi.grpc.Orders
	(*OrderCosts_CategoryCost)(nil),    // 15: com.consorsbank.module.tapi.grpc.OrderCosts.CategoryCost
	(*OrderCosts_AggregatedCosts)(nil), // 16: com.consorsbank.module.tapi.grpc.OrderCosts.AggregatedCosts
	(*OrderCosts_DetailCost)(nil),      // 17: com.consorsbank.module.tapi.grpc.OrderCosts.DetailCost
	(*SecurityWithStockExchange)(nil),  // 18: com.consorsbank.module.tapi.grpc.SecurityWithStockExchange
	(OrderType)(0),                     // 19: com.consorsbank.module.tapi.grpc.OrderType
	(OrderModel)(0),                    // 20: com.consorsbank.module.tapi.grpc.OrderModel
	(OrderSupplement)(0),               // 21: com.consorsbank.module.tapi.grpc.OrderSupplement
	(CashQuotation)(0),                 // 22: com.consorsbank.module.tapi.grpc.CashQuotation
	(*Timestamp)(nil),                  // 23: com.consorsbank.module.tapi.grpc.Timestamp
	(*Date)(nil),                       // 24: com.consorsbank.module.tapi.grpc.Date
	(TrailingNotation)(0),              // 25: com.consorsbank.module.tapi.grpc.TrailingNotation
	(*TradingAccount)(nil),             // 26: com.consorsbank.module.tapi.grpc.TradingAccount
	(*Error)(nil),                      // 27: com.consorsbank.module.tapi.grpc.Error
	(*SecurityCode)(nil),               // 28: com.consorsbank.module.tapi.grpc.SecurityCode
	(*StockExchange)(nil),              // 29: com.consorsbank.module.tapi.grpc.StockExchange
}
var file_OrderService_proto_depIdxs = []int32{
	18, // 0: com.consorsbank.module.tapi.grpc.Order.security_with_stockexchange:type_name -> com.consorsbank.module.tapi.grpc.SecurityWithStockExchange
	19, // 1: com.consorsbank.module.tapi.grpc.Order.order_type:type_name -> com.consorsbank.module.tapi.grpc.OrderType
	20, // 2: com.consorsbank.module.tapi.grpc.Order.order_model:type_name -> com.consorsbank.module.tapi.grpc.OrderModel
	21, // 3: com.consorsbank.module.tapi.grpc.Order.order_supplement:type_name -> com.consorsbank.module.tapi.grpc.OrderSupplement
	22, // 4: com.consorsbank.module.tapi.grpc.Order.cash_quotation:type_name -> com.consorsbank.module.tapi.grpc.CashQuotation
	0,  // 5: com.consorsbank.module.tapi.grpc.Order.order_status:type_name -> com.consorsbank.module.tapi.grpc.OrderStatus
	23, // 6: com.consorsbank.module.tapi.grpc.Order.status_timestamp:type_name -> com.consorsbank.module.tapi.grpc.Timestamp
	24, // 7: com.consorsbank.module.tapi.grpc.Order.validity_date:type_name -> com.consorsbank.module.tapi.grpc.Date
	25, // 8: com.consorsbank.module.tapi.grpc.Order.trailing_notation:type_name -> com.consorsbank.module.tapi.grpc.TrailingNotation
	18, // 9: com.consorsbank.module.tapi.grpc.AddOrderRequest.security_with_stockexchange:type_name -> com.consorsbank.module.tapi.grpc.SecurityWithStockExchange
	19, // 10: com.consorsbank.module.tapi.grpc.AddOrderRequest.order_type:type_name -> com.consorsbank.module.tapi.grpc.OrderType
	20, // 11: com.consorsbank.module.tapi.grpc.AddOrderRequest.order_model:type_name -> com.consorsbank.module.tapi.grpc.OrderModel
	21, // 12: com.consorsbank.module.tapi.grpc.AddOrderRequest.order_supplement:type_name -> com.consorsbank.module.tapi.grpc.OrderSupplement
	22, // 13: com.consorsbank.module.tapi.grpc.AddOrderRequest.cash_quotation:type_name -> com.consorsbank.module.tapi.grpc.CashQuotation
	24, // 14: com.consorsbank.module.tapi.grpc.AddOrderRequest.validity_date:type_name -> com.consorsbank.module.tapi.grpc.Date
	25, // 15: com.consorsbank.module.tapi.grpc.AddOrderRequest.trailing_notation:type_name -> com.consorsbank.module.tapi.grpc.TrailingNotation
	1,  // 16: com.consorsbank.module.tapi.grpc.AddOrderRequest.validation:type_name -> com.consorsbank.module.tapi.grpc.Validation
	26, // 17: com.consorsbank.module.tapi.grpc.OrderReply.account:type_name -> com.consorsbank.module.tapi.grpc.TradingAccount
	2,  // 18: com.consorsbank.module.tapi.grpc.OrderReply.order:type_name -> com.consorsbank.module.tapi.grpc.Order
	5,  // 19: com.consorsbank.module.tapi.grpc.OrderReply.order_costs:type_name -> com.consorsbank.module.tapi.grpc.OrderCosts
	27, // 20: com.consorsbank.module.tapi.grpc.OrderReply.error:type_name -> com.consorsbank.module.tapi.grpc.Error
	15, // 21: com.consorsbank.module.tapi.grpc.OrderCosts.categorie_costs:type_name -> com.consorsbank.module.tapi.grpc.OrderCosts.CategoryCost
	16, // 22: com.consorsbank.module.tapi.grpc.OrderCosts.aggregated_costs:type_name -> com.consorsbank.module.tapi.grpc.OrderCosts.AggregatedCosts
	24, // 23: com.consorsbank.module.tapi.grpc.ChangeOrderRequest.validity_date:type_name -> com.consorsbank.module.tapi.grpc.Date
	20, // 24: com.consorsbank.module.tapi.grpc.ChangeOrderRequest.order_model:type_name -> com.consorsbank.module.tapi.grpc.OrderModel
	21, // 25: com.consorsbank.module.tapi.grpc.ChangeOrderRequest.order_supplement:type_name -> com.consorsbank.module.tapi.grpc.OrderSupplement
	1,  // 26: com.consorsbank.module.tapi.grpc.ChangeOrderRequest.validation:type_name -> com.consorsbank.module.tapi.grpc.Validation
	1,  // 27: com.consorsbank.module.tapi.grpc.CancelOrderRequest.validation:type_name -> com.consorsbank.module.tapi.grpc.Validation
	1,  // 28: com.consorsbank.module.tapi.grpc.ActivateOrderRequest.validation:type_name -> com.consorsbank.module.tapi.grpc.Validation
	1,  // 29: com.consorsbank.module.tapi.grpc.DeactivateOrderRequest.validation:type_name -> com.consorsbank.module.tapi.grpc.Validation
	18, // 30: com.consorsbank.module.tapi.grpc.AcceptQuoteRequest.security_with_stockexchange:type_name -> com.consorsbank.module.tapi.grpc.SecurityWithStockExchange
	19, // 31: com.consorsbank.module.tapi.grpc.AcceptQuoteRequest.order_type:type_name -> com.consorsbank.module.tapi.grpc.OrderType
	1,  // 32: com.consorsbank.module.tapi.grpc.AcceptQuoteRequest.validation:type_name -> com.consorsbank.module.tapi.grpc.Validation
	28, // 33: com.consorsbank.module.tapi.grpc.QuoteRequest.security_code:type_name -> com.consorsbank.module.tapi.grpc.SecurityCode
	19, // 34: com.consorsbank.module.tapi.grpc.QuoteRequest.order_type:type_name -> com.consorsbank.module.tapi.grpc.OrderType
	29, // 35: com.consorsbank.module.tapi.grpc.QuoteRequest.stock_exchanges:type_name -> com.consorsbank.module.tapi.grpc.StockExchange
	28, // 36: com.consorsbank.module.tapi.grpc.QuoteReply.security_code:type_name -> com.consorsbank.module.tapi.grpc.SecurityCode
	19, // 37: com.consorsbank.module.tapi.grpc.QuoteReply.order_type:type_name -> com.consorsbank.module.tapi.grpc.OrderType
	13, // 38: com.consorsbank.module.tapi.grpc.QuoteReply.price_entries:type_name -> com.consorsbank.module.tapi.grpc.QuoteEntry
	27, // 39: com.consorsbank.module.tapi.grpc.QuoteReply.error:type_name -> com.consorsbank.module.tapi.grpc.Error
	29, // 40: com.consorsbank.module.tapi.grpc.QuoteEntry.stock_exchange:type_name -> com.consorsbank.module.tapi.grpc.StockExchange
	23, // 41: com.consorsbank.module.tapi.grpc.QuoteEntry.last_time:type_name -> com.consorsbank.module.tapi.grpc.Timestamp
	19, // 42: com.consorsbank.module.tapi.grpc.QuoteEntry.order_type:type_name -> com.consorsbank.module.tapi.grpc.OrderType
	27, // 43: com.consorsbank.module.tapi.grpc.QuoteEntry.error:type_name -> com.consorsbank.module.tapi.grpc.Error
	26, // 44: com.consorsbank.module.tapi.grpc.Orders.account:type_name -> com.consorsbank.module.tapi.grpc.TradingAccount
	2,  // 45: com.consorsbank.module.tapi.grpc.Orders.orders:type_name -> com.consorsbank.module.tapi.grpc.Order
	27, // 46: com.consorsbank.module.tapi.grpc.Orders.error:type_name -> com.consorsbank.module.tapi.grpc.Error
	17, // 47: com.consorsbank.module.tapi.grpc.OrderCosts.CategoryCost.detail_costs:type_name -> com.consorsbank.module.tapi.grpc.OrderCosts.DetailCost
	48, // [48:48] is the sub-list for method output_type
	48, // [48:48] is the sub-list for method input_type
	48, // [48:48] is the sub-list for extension type_name
	48, // [48:48] is the sub-list for extension extendee
	0,  // [0:48] is the sub-list for field type_name
}

func init() { file_OrderService_proto_init() }
func file_OrderService_proto_init() {
	if File_OrderService_proto != nil {
		return
	}
	file_Common_proto_init()
	file_SecurityService_proto_init()
	file_StockExchangeService_proto_init()
	file_AccountService_proto_init()
	file_TradingTypes_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_OrderService_proto_rawDesc), len(file_OrderService_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_OrderService_proto_goTypes,
		DependencyIndexes: file_OrderService_proto_depIdxs,
		EnumInfos:         file_OrderService_proto_enumTypes,
		MessageInfos:      file_OrderService_proto_msgTypes,
	}.Build()
	File_OrderService_proto = out.File
	file_OrderService_proto_goTypes = nil
	file_OrderService_proto_depIdxs = nil
}
