//
// Copyright 2018, Trading-API, Consorsbank.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: SecurityService.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Time resolution represents information about price aggregation
type TimeResolution int32

const (
	// * Undefined resolution
	TimeResolution_NO_RESOLUTION TimeResolution = 0
	// *
	// Tick resolution. *intraday*.
	//
	// Be careful, in same cases there is a lot of data.
	TimeResolution_TICK TimeResolution = 1
	// * Second resolution *intraday*
	TimeResolution_SECOND TimeResolution = 2
	// * Minute resolution *intraday*
	TimeResolution_MINUTE TimeResolution = 3
	// * Hour resolution *intraday*
	TimeResolution_HOUR TimeResolution = 4
	// * Day resolution *historic*
	TimeResolution_DAY TimeResolution = 5
)

// Enum value maps for TimeResolution.
var (
	TimeResolution_name = map[int32]string{
		0: "NO_RESOLUTION",
		1: "TICK",
		2: "SECOND",
		3: "MINUTE",
		4: "HOUR",
		5: "DAY",
	}
	TimeResolution_value = map[string]int32{
		"NO_RESOLUTION": 0,
		"TICK":          1,
		"SECOND":        2,
		"MINUTE":        3,
		"HOUR":          4,
		"DAY":           5,
	}
)

func (x TimeResolution) Enum() *TimeResolution {
	p := new(TimeResolution)
	*p = x
	return p
}

func (x TimeResolution) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeResolution) Descriptor() protoreflect.EnumDescriptor {
	return file_SecurityService_proto_enumTypes[0].Descriptor()
}

func (TimeResolution) Type() protoreflect.EnumType {
	return &file_SecurityService_proto_enumTypes[0]
}

func (x TimeResolution) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeResolution.Descriptor instead.
func (TimeResolution) EnumDescriptor() ([]byte, []int) {
	return file_SecurityService_proto_rawDescGZIP(), []int{0}
}

// *
// Represents information about security code type
// Some of the types are refer to the market data provider (FactSet)
type SecurityCodeType int32

const (
	// * Unknown code type
	SecurityCodeType_NO_CODE_TYPE SecurityCodeType = 0
	// *  WKN code type
	SecurityCodeType_WKN SecurityCodeType = 1
	// *  ISIN code type
	SecurityCodeType_ISIN SecurityCodeType = 2
	// *  Factset id notation
	SecurityCodeType_ID_NOTATION SecurityCodeType = 3
	// *  Factset id osi
	SecurityCodeType_ID_OSI SecurityCodeType = 4
	// *  Factset id instrument
	SecurityCodeType_ID_INSTRUMENT SecurityCodeType = 5
	// *  Mnemonic or symbol
	SecurityCodeType_MNEMONIC SecurityCodeType = 6
	// *  US Mnemonic or symbol
	SecurityCodeType_MNEMONIC_US SecurityCodeType = 7
)

// Enum value maps for SecurityCodeType.
var (
	SecurityCodeType_name = map[int32]string{
		0: "NO_CODE_TYPE",
		1: "WKN",
		2: "ISIN",
		3: "ID_NOTATION",
		4: "ID_OSI",
		5: "ID_INSTRUMENT",
		6: "MNEMONIC",
		7: "MNEMONIC_US",
	}
	SecurityCodeType_value = map[string]int32{
		"NO_CODE_TYPE":  0,
		"WKN":           1,
		"ISIN":          2,
		"ID_NOTATION":   3,
		"ID_OSI":        4,
		"ID_INSTRUMENT": 5,
		"MNEMONIC":      6,
		"MNEMONIC_US":   7,
	}
)

func (x SecurityCodeType) Enum() *SecurityCodeType {
	p := new(SecurityCodeType)
	*p = x
	return p
}

func (x SecurityCodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecurityCodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_SecurityService_proto_enumTypes[1].Descriptor()
}

func (SecurityCodeType) Type() protoreflect.EnumType {
	return &file_SecurityService_proto_enumTypes[1]
}

func (x SecurityCodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecurityCodeType.Descriptor instead.
func (SecurityCodeType) EnumDescriptor() ([]byte, []int) {
	return file_SecurityService_proto_rawDescGZIP(), []int{1}
}

// *
// Represents information about security class
type SecurityClass int32

const (
	// * Security class is undefined on unknown
	SecurityClass_NO_SECURITY_CLASS SecurityClass = 0
	// * Stock security class
	SecurityClass_STOCK SecurityClass = 1
	// * Bond security class
	SecurityClass_BOND SecurityClass = 2
	// * Certificate security class
	SecurityClass_CERTIFICATE SecurityClass = 3
	// * Precious metal security class
	SecurityClass_PRECIOUS_METAL SecurityClass = 4
	// * Participation certificate security class
	SecurityClass_PARTICIPATION_CERTIFICATE SecurityClass = 5
	// * Funds security class
	SecurityClass_FUNDS SecurityClass = 6
	// *  Mutual funds security class
	SecurityClass_MUTUAL_FUNDS SecurityClass = 7
	// * Warrants security class
	SecurityClass_WARRANT SecurityClass = 8
	// * Futures security class
	SecurityClass_FUTURE SecurityClass = 9
	// * Indexies security class
	SecurityClass_INDEX SecurityClass = 10
	// * Other securities security class
	SecurityClass_OTHERS SecurityClass = 11
	// * Future c1 security class
	SecurityClass_FUTURE_C1 SecurityClass = 12
	// * Future c2 security class
	SecurityClass_FUTURE_C2 SecurityClass = 13
	// * Future c3 security class
	SecurityClass_FUTURE_C3 SecurityClass = 14
	// * Trackers security class
	SecurityClass_TRACKERS SecurityClass = 15
	// * Currency security class
	SecurityClass_CURRENCY SecurityClass = 16
	// * Commodity security class
	SecurityClass_COMMODITY SecurityClass = 17
)

// Enum value maps for SecurityClass.
var (
	SecurityClass_name = map[int32]string{
		0:  "NO_SECURITY_CLASS",
		1:  "STOCK",
		2:  "BOND",
		3:  "CERTIFICATE",
		4:  "PRECIOUS_METAL",
		5:  "PARTICIPATION_CERTIFICATE",
		6:  "FUNDS",
		7:  "MUTUAL_FUNDS",
		8:  "WARRANT",
		9:  "FUTURE",
		10: "INDEX",
		11: "OTHERS",
		12: "FUTURE_C1",
		13: "FUTURE_C2",
		14: "FUTURE_C3",
		15: "TRACKERS",
		16: "CURRENCY",
		17: "COMMODITY",
	}
	SecurityClass_value = map[string]int32{
		"NO_SECURITY_CLASS":         0,
		"STOCK":                     1,
		"BOND":                      2,
		"CERTIFICATE":               3,
		"PRECIOUS_METAL":            4,
		"PARTICIPATION_CERTIFICATE": 5,
		"FUNDS":                     6,
		"MUTUAL_FUNDS":              7,
		"WARRANT":                   8,
		"FUTURE":                    9,
		"INDEX":                     10,
		"OTHERS":                    11,
		"FUTURE_C1":                 12,
		"FUTURE_C2":                 13,
		"FUTURE_C3":                 14,
		"TRACKERS":                  15,
		"CURRENCY":                  16,
		"COMMODITY":                 17,
	}
)

func (x SecurityClass) Enum() *SecurityClass {
	p := new(SecurityClass)
	*p = x
	return p
}

func (x SecurityClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecurityClass) Descriptor() protoreflect.EnumDescriptor {
	return file_SecurityService_proto_enumTypes[2].Descriptor()
}

func (SecurityClass) Type() protoreflect.EnumType {
	return &file_SecurityService_proto_enumTypes[2]
}

func (x SecurityClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecurityClass.Descriptor instead.
func (SecurityClass) EnumDescriptor() ([]byte, []int) {
	return file_SecurityService_proto_rawDescGZIP(), []int{2}
}

// *
// Represents stock exchange trading phase.
// Some values are refer to the Xetra stock exchange
type TradingPhase int32

const (
	// * Unknown trading phase
	TradingPhase_NONE TradingPhase = 0
	// *  Pretrade trading phase
	TradingPhase_PRETRADE TradingPhase = 1
	// *  Posttrade trading phase
	TradingPhase_POSTTRADE TradingPhase = 2
	// *  Start trading phase
	TradingPhase_START TradingPhase = 3
	// *  End trading phase
	TradingPhase_END TradingPhase = 4
	// *  Vola trading phase
	TradingPhase_VOLA TradingPhase = 5
	// *  OCall trading phase
	TradingPhase_OCALL TradingPhase = 6
	// *  ICall trading phase
	TradingPhase_ICALL TradingPhase = 7
	// *  CCall trading phase
	TradingPhase_CCALL TradingPhase = 8
	// *  Trade trading phase
	TradingPhase_TRADE TradingPhase = 9
	// *  Trade indicative trading phase
	TradingPhase_TRADE_INDICATIVE TradingPhase = 10
	// *  Trade best bid / ask trading phase
	TradingPhase_TRADE_BEST_BID_ASK TradingPhase = 11
	// *  Trade auction, but not indicative trading phase
	TradingPhase_TRADE_AUCTION_NO_INDICATIVE TradingPhase = 12
)

// Enum value maps for TradingPhase.
var (
	TradingPhase_name = map[int32]string{
		0:  "NONE",
		1:  "PRETRADE",
		2:  "POSTTRADE",
		3:  "START",
		4:  "END",
		5:  "VOLA",
		6:  "OCALL",
		7:  "ICALL",
		8:  "CCALL",
		9:  "TRADE",
		10: "TRADE_INDICATIVE",
		11: "TRADE_BEST_BID_ASK",
		12: "TRADE_AUCTION_NO_INDICATIVE",
	}
	TradingPhase_value = map[string]int32{
		"NONE":                        0,
		"PRETRADE":                    1,
		"POSTTRADE":                   2,
		"START":                       3,
		"END":                         4,
		"VOLA":                        5,
		"OCALL":                       6,
		"ICALL":                       7,
		"CCALL":                       8,
		"TRADE":                       9,
		"TRADE_INDICATIVE":            10,
		"TRADE_BEST_BID_ASK":          11,
		"TRADE_AUCTION_NO_INDICATIVE": 12,
	}
)

func (x TradingPhase) Enum() *TradingPhase {
	p := new(TradingPhase)
	*p = x
	return p
}

func (x TradingPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TradingPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_SecurityService_proto_enumTypes[3].Descriptor()
}

func (TradingPhase) Type() protoreflect.EnumType {
	return &file_SecurityService_proto_enumTypes[3]
}

func (x TradingPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TradingPhase.Descriptor instead.
func (TradingPhase) EnumDescriptor() ([]byte, []int) {
	return file_SecurityService_proto_rawDescGZIP(), []int{3}
}

// *
// Short mode gives information amout security shortability
// on the selected market.
type SecurityStockExchangeInfo_ShortMode int32

const (
	// * Undefined short selling
	SecurityStockExchangeInfo_NO_SHORT_MODE SecurityStockExchangeInfo_ShortMode = 0
	// * Short selling is possible
	SecurityStockExchangeInfo_YES SecurityStockExchangeInfo_ShortMode = 1
	// * No short selling
	SecurityStockExchangeInfo_NO SecurityStockExchangeInfo_ShortMode = 2
	// * Temporary no short selling
	SecurityStockExchangeInfo_TEMPORARY_NO SecurityStockExchangeInfo_ShortMode = 3
	// * Intraday short selling
	SecurityStockExchangeInfo_INTRADAY SecurityStockExchangeInfo_ShortMode = 4
	// * Overnight short selling
	SecurityStockExchangeInfo_OVERNIGHT SecurityStockExchangeInfo_ShortMode = 5
	// * Intraday and Overnight short selling
	SecurityStockExchangeInfo_INTRADAY_AND_OVERNIGHT SecurityStockExchangeInfo_ShortMode = 6
)

// Enum value maps for SecurityStockExchangeInfo_ShortMode.
var (
	SecurityStockExchangeInfo_ShortMode_name = map[int32]string{
		0: "NO_SHORT_MODE",
		1: "YES",
		2: "NO",
		3: "TEMPORARY_NO",
		4: "INTRADAY",
		5: "OVERNIGHT",
		6: "INTRADAY_AND_OVERNIGHT",
	}
	SecurityStockExchangeInfo_ShortMode_value = map[string]int32{
		"NO_SHORT_MODE":          0,
		"YES":                    1,
		"NO":                     2,
		"TEMPORARY_NO":           3,
		"INTRADAY":               4,
		"OVERNIGHT":              5,
		"INTRADAY_AND_OVERNIGHT": 6,
	}
)

func (x SecurityStockExchangeInfo_ShortMode) Enum() *SecurityStockExchangeInfo_ShortMode {
	p := new(SecurityStockExchangeInfo_ShortMode)
	*p = x
	return p
}

func (x SecurityStockExchangeInfo_ShortMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecurityStockExchangeInfo_ShortMode) Descriptor() protoreflect.EnumDescriptor {
	return file_SecurityService_proto_enumTypes[4].Descriptor()
}

func (SecurityStockExchangeInfo_ShortMode) Type() protoreflect.EnumType {
	return &file_SecurityService_proto_enumTypes[4]
}

func (x SecurityStockExchangeInfo_ShortMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecurityStockExchangeInfo_ShortMode.Descriptor instead.
func (SecurityStockExchangeInfo_ShortMode) EnumDescriptor() ([]byte, []int) {
	return file_SecurityService_proto_rawDescGZIP(), []int{5, 0}
}

// *
// Limit token represents a possibility to trade on the
// short term markets (AcceptQuote) and long term markets (AddOrder)
type SecurityStockExchangeInfo_LimitToken int32

const (
	// * AcceptQuote and AddOrder possible
	SecurityStockExchangeInfo_LIMIT_AND_QUOTE SecurityStockExchangeInfo_LimitToken = 0
	// * AcceptQuote only possible
	SecurityStockExchangeInfo_QUOTE_ONLY SecurityStockExchangeInfo_LimitToken = 1
	// * AddOrder only possible
	SecurityStockExchangeInfo_LIMIT_ONLY SecurityStockExchangeInfo_LimitToken = 2
)

// Enum value maps for SecurityStockExchangeInfo_LimitToken.
var (
	SecurityStockExchangeInfo_LimitToken_name = map[int32]string{
		0: "LIMIT_AND_QUOTE",
		1: "QUOTE_ONLY",
		2: "LIMIT_ONLY",
	}
	SecurityStockExchangeInfo_LimitToken_value = map[string]int32{
		"LIMIT_AND_QUOTE": 0,
		"QUOTE_ONLY":      1,
		"LIMIT_ONLY":      2,
	}
)

func (x SecurityStockExchangeInfo_LimitToken) Enum() *SecurityStockExchangeInfo_LimitToken {
	p := new(SecurityStockExchangeInfo_LimitToken)
	*p = x
	return p
}

func (x SecurityStockExchangeInfo_LimitToken) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecurityStockExchangeInfo_LimitToken) Descriptor() protoreflect.EnumDescriptor {
	return file_SecurityService_proto_enumTypes[5].Descriptor()
}

func (SecurityStockExchangeInfo_LimitToken) Type() protoreflect.EnumType {
	return &file_SecurityService_proto_enumTypes[5]
}

func (x SecurityStockExchangeInfo_LimitToken) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecurityStockExchangeInfo_LimitToken.Descriptor instead.
func (SecurityStockExchangeInfo_LimitToken) EnumDescriptor() ([]byte, []int) {
	return file_SecurityService_proto_rawDescGZIP(), []int{5, 1}
}

// *
// SecurityChangedField represents information about changed fields during marked data event.
// Not all field can be initialized. There are only changed fields. Some fields can be changed, but have undefined state
// for example NaN.
type SecurityMarketDataReply_SecurityChangedField int32

const (
	// * No data
	SecurityMarketDataReply_NONE SecurityMarketDataReply_SecurityChangedField = 0
	// * Price of the last trade
	SecurityMarketDataReply_LAST_PRICE SecurityMarketDataReply_SecurityChangedField = 4
	// * Volume last trade
	SecurityMarketDataReply_LAST_VOLUME SecurityMarketDataReply_SecurityChangedField = 5
	// * Last quote date and time
	SecurityMarketDataReply_LAST_DATE_TIME SecurityMarketDataReply_SecurityChangedField = 6
	// * Today number of tradings
	SecurityMarketDataReply_TODAY_NUM_TRADES SecurityMarketDataReply_SecurityChangedField = 7
	// * Today volume
	SecurityMarketDataReply_TODAY_VOLUME SecurityMarketDataReply_SecurityChangedField = 8
	// * Last ask price
	SecurityMarketDataReply_ASK_PRICE SecurityMarketDataReply_SecurityChangedField = 9
	// * Volume last ask
	SecurityMarketDataReply_ASK_VOLUME SecurityMarketDataReply_SecurityChangedField = 10
	// * Time of the last ask
	SecurityMarketDataReply_ASK_TIME SecurityMarketDataReply_SecurityChangedField = 11
	// * Last bid price
	SecurityMarketDataReply_BID_PRICE SecurityMarketDataReply_SecurityChangedField = 12
	// * Volume last bid
	SecurityMarketDataReply_BID_VOLUME SecurityMarketDataReply_SecurityChangedField = 13
	// * Time of the last bid
	SecurityMarketDataReply_BID_TIME SecurityMarketDataReply_SecurityChangedField = 14
	// * Quote of the previous trading day
	SecurityMarketDataReply_PREVIOUS_PRICE SecurityMarketDataReply_SecurityChangedField = 15
	// * Date of the previous trading day
	SecurityMarketDataReply_PREVIOUS_DATE SecurityMarketDataReply_SecurityChangedField = 16
	// * Relative difference to the previous day
	SecurityMarketDataReply_RELATIVE_DIFF SecurityMarketDataReply_SecurityChangedField = 17
	// * Absolute difference to the previous day
	SecurityMarketDataReply_ABS_DIFF SecurityMarketDataReply_SecurityChangedField = 18
	// * Highest price
	SecurityMarketDataReply_HIGH_PRICE SecurityMarketDataReply_SecurityChangedField = 19
	// * Lowest price
	SecurityMarketDataReply_LOW_PRICE SecurityMarketDataReply_SecurityChangedField = 20
	// * Price at opening
	SecurityMarketDataReply_OPEN_PRICE SecurityMarketDataReply_SecurityChangedField = 21
	// * Highest price of the previous week
	SecurityMarketDataReply_WEEK_HIGH_PRICE SecurityMarketDataReply_SecurityChangedField = 22
	// * Date of highest price of the previous week
	SecurityMarketDataReply_DATE_WEEK_HIGH SecurityMarketDataReply_SecurityChangedField = 23
	// * Lowest price of the previous week
	SecurityMarketDataReply_WEEK_LOW_PRICE SecurityMarketDataReply_SecurityChangedField = 24
	// * Date of lowest price of the previous week
	SecurityMarketDataReply_DATE_WEEK_LOW SecurityMarketDataReply_SecurityChangedField = 25
	// * Highest price of the previous month
	SecurityMarketDataReply_MONTH_HIGH_PRICE SecurityMarketDataReply_SecurityChangedField = 26
	// * Date of highest price of the previous month
	SecurityMarketDataReply_DATE_MONTH_HIGH SecurityMarketDataReply_SecurityChangedField = 27
	// * Lowest price of the previous month
	SecurityMarketDataReply_MONTH_LOW_PRICE SecurityMarketDataReply_SecurityChangedField = 28
	// * Date of lowest price of the previous month
	SecurityMarketDataReply_DATE_MONTH_LOW SecurityMarketDataReply_SecurityChangedField = 29
	// * Highest price of the current year
	SecurityMarketDataReply_YEAR_HIGH_PRICE SecurityMarketDataReply_SecurityChangedField = 30
	// * Date of the highest price of the current year
	SecurityMarketDataReply_DATE_YEAR_HIGH SecurityMarketDataReply_SecurityChangedField = 31
	// * Lowest price of the current year
	SecurityMarketDataReply_YEAR_LOW_PRICE SecurityMarketDataReply_SecurityChangedField = 32
	// * Date of the lowest price of the current year
	SecurityMarketDataReply_DATE_YEAR_LOW SecurityMarketDataReply_SecurityChangedField = 33
	// * Addendum of the last price.
	SecurityMarketDataReply_LAST_ADDENDUM SecurityMarketDataReply_SecurityChangedField = 34
	// * Trading phase
	SecurityMarketDataReply_TRADING_PHASE SecurityMarketDataReply_SecurityChangedField = 35
	// * Indicative price
	SecurityMarketDataReply_INDICATIVE_PRICE SecurityMarketDataReply_SecurityChangedField = 36
	// * Trading volume corresponding to the last price
	SecurityMarketDataReply_PREVALENCE_VOLUME SecurityMarketDataReply_SecurityChangedField = 37
)

// Enum value maps for SecurityMarketDataReply_SecurityChangedField.
var (
	SecurityMarketDataReply_SecurityChangedField_name = map[int32]string{
		0:  "NONE",
		4:  "LAST_PRICE",
		5:  "LAST_VOLUME",
		6:  "LAST_DATE_TIME",
		7:  "TODAY_NUM_TRADES",
		8:  "TODAY_VOLUME",
		9:  "ASK_PRICE",
		10: "ASK_VOLUME",
		11: "ASK_TIME",
		12: "BID_PRICE",
		13: "BID_VOLUME",
		14: "BID_TIME",
		15: "PREVIOUS_PRICE",
		16: "PREVIOUS_DATE",
		17: "RELATIVE_DIFF",
		18: "ABS_DIFF",
		19: "HIGH_PRICE",
		20: "LOW_PRICE",
		21: "OPEN_PRICE",
		22: "WEEK_HIGH_PRICE",
		23: "DATE_WEEK_HIGH",
		24: "WEEK_LOW_PRICE",
		25: "DATE_WEEK_LOW",
		26: "MONTH_HIGH_PRICE",
		27: "DATE_MONTH_HIGH",
		28: "MONTH_LOW_PRICE",
		29: "DATE_MONTH_LOW",
		30: "YEAR_HIGH_PRICE",
		31: "DATE_YEAR_HIGH",
		32: "YEAR_LOW_PRICE",
		33: "DATE_YEAR_LOW",
		34: "LAST_ADDENDUM",
		35: "TRADING_PHASE",
		36: "INDICATIVE_PRICE",
		37: "PREVALENCE_VOLUME",
	}
	SecurityMarketDataReply_SecurityChangedField_value = map[string]int32{
		"NONE":              0,
		"LAST_PRICE":        4,
		"LAST_VOLUME":       5,
		"LAST_DATE_TIME":    6,
		"TODAY_NUM_TRADES":  7,
		"TODAY_VOLUME":      8,
		"ASK_PRICE":         9,
		"ASK_VOLUME":        10,
		"ASK_TIME":          11,
		"BID_PRICE":         12,
		"BID_VOLUME":        13,
		"BID_TIME":          14,
		"PREVIOUS_PRICE":    15,
		"PREVIOUS_DATE":     16,
		"RELATIVE_DIFF":     17,
		"ABS_DIFF":          18,
		"HIGH_PRICE":        19,
		"LOW_PRICE":         20,
		"OPEN_PRICE":        21,
		"WEEK_HIGH_PRICE":   22,
		"DATE_WEEK_HIGH":    23,
		"WEEK_LOW_PRICE":    24,
		"DATE_WEEK_LOW":     25,
		"MONTH_HIGH_PRICE":  26,
		"DATE_MONTH_HIGH":   27,
		"MONTH_LOW_PRICE":   28,
		"DATE_MONTH_LOW":    29,
		"YEAR_HIGH_PRICE":   30,
		"DATE_YEAR_HIGH":    31,
		"YEAR_LOW_PRICE":    32,
		"DATE_YEAR_LOW":     33,
		"LAST_ADDENDUM":     34,
		"TRADING_PHASE":     35,
		"INDICATIVE_PRICE":  36,
		"PREVALENCE_VOLUME": 37,
	}
)

func (x SecurityMarketDataReply_SecurityChangedField) Enum() *SecurityMarketDataReply_SecurityChangedField {
	p := new(SecurityMarketDataReply_SecurityChangedField)
	*p = x
	return p
}

func (x SecurityMarketDataReply_SecurityChangedField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecurityMarketDataReply_SecurityChangedField) Descriptor() protoreflect.EnumDescriptor {
	return file_SecurityService_proto_enumTypes[6].Descriptor()
}

func (SecurityMarketDataReply_SecurityChangedField) Type() protoreflect.EnumType {
	return &file_SecurityService_proto_enumTypes[6]
}

func (x SecurityMarketDataReply_SecurityChangedField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecurityMarketDataReply_SecurityChangedField.Descriptor instead.
func (SecurityMarketDataReply_SecurityChangedField) EnumDescriptor() ([]byte, []int) {
	return file_SecurityService_proto_rawDescGZIP(), []int{9, 0}
}

// *
// Requests security information for security code
type SecurityInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Access token
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// *
	// Security code with security type (WKN, ISIN)
	SecurityCode  *SecurityCode `protobuf:"bytes,2,opt,name=security_code,json=securityCode,proto3" json:"security_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityInfoRequest) Reset() {
	*x = SecurityInfoRequest{}
	mi := &file_SecurityService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityInfoRequest) ProtoMessage() {}

func (x *SecurityInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SecurityService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityInfoRequest.ProtoReflect.Descriptor instead.
func (*SecurityInfoRequest) Descriptor() ([]byte, []int) {
	return file_SecurityService_proto_rawDescGZIP(), []int{0}
}

func (x *SecurityInfoRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SecurityInfoRequest) GetSecurityCode() *SecurityCode {
	if x != nil {
		return x.SecurityCode
	}
	return nil
}

// *
// Returns security information
type SecurityInfoReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Security name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// * Security class
	SecurityClass SecurityClass `protobuf:"varint,2,opt,name=security_class,json=securityClass,proto3,enum=com.consorsbank.module.tapi.grpc.SecurityClass" json:"security_class,omitempty"`
	// * Security codes with security type (WKN, ISIN, etc)
	SecurityCodes []*SecurityCode `protobuf:"bytes,3,rep,name=security_codes,json=securityCodes,proto3" json:"security_codes,omitempty"`
	// *  Stockexchange info (stock exchange, name)
	StockExchangeInfos []*SecurityStockExchangeInfo `protobuf:"bytes,4,rep,name=stock_exchange_infos,json=stockExchangeInfos,proto3" json:"stock_exchange_infos,omitempty"`
	// * Unit note
	UnitNote UnitNote `protobuf:"varint,5,opt,name=unit_note,json=unitNote,proto3,enum=com.consorsbank.module.tapi.grpc.UnitNote" json:"unit_note,omitempty"`
	// *
	// Error information if occuirs
	Error         *Error `protobuf:"bytes,1000,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityInfoReply) Reset() {
	*x = SecurityInfoReply{}
	mi := &file_SecurityService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityInfoReply) ProtoMessage() {}

func (x *SecurityInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_SecurityService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityInfoReply.ProtoReflect.Descriptor instead.
func (*SecurityInfoReply) Descriptor() ([]byte, []int) {
	return file_SecurityService_proto_rawDescGZIP(), []int{1}
}

func (x *SecurityInfoReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecurityInfoReply) GetSecurityClass() SecurityClass {
	if x != nil {
		return x.SecurityClass
	}
	return SecurityClass_NO_SECURITY_CLASS
}

func (x *SecurityInfoReply) GetSecurityCodes() []*SecurityCode {
	if x != nil {
		return x.SecurityCodes
	}
	return nil
}

func (x *SecurityInfoReply) GetStockExchangeInfos() []*SecurityStockExchangeInfo {
	if x != nil {
		return x.StockExchangeInfos
	}
	return nil
}

func (x *SecurityInfoReply) GetUnitNote() UnitNote {
	if x != nil {
		return x.UnitNote
	}
	return UnitNote_NO_UNIT_NOTE
}

func (x *SecurityInfoReply) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type SecurityPriceHistoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Access token
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// *
	// Security with stockExchange object (security code, stock exchange)
	SecurityWithStockexchange *SecurityWithStockExchange `protobuf:"bytes,2,opt,name=security_with_stockexchange,json=securityWithStockexchange,proto3" json:"security_with_stockexchange,omitempty"`
	// *
	// Amount of the day in the past. This value should be positive.
	// Maximal value for the intraday resolution is 15.
	Days int32 `protobuf:"varint,3,opt,name=days,proto3" json:"days,omitempty"`
	// *
	// Time resolution for the data
	TimeResolution TimeResolution `protobuf:"varint,4,opt,name=time_resolution,json=timeResolution,proto3,enum=com.consorsbank.module.tapi.grpc.TimeResolution" json:"time_resolution,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SecurityPriceHistoryRequest) Reset() {
	*x = SecurityPriceHistoryRequest{}
	mi := &file_SecurityService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityPriceHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityPriceHistoryRequest) ProtoMessage() {}

func (x *SecurityPriceHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SecurityService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityPriceHistoryRequest.ProtoReflect.Descriptor instead.
func (*SecurityPriceHistoryRequest) Descriptor() ([]byte, []int) {
	return file_SecurityService_proto_rawDescGZIP(), []int{2}
}

func (x *SecurityPriceHistoryRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SecurityPriceHistoryRequest) GetSecurityWithStockexchange() *SecurityWithStockExchange {
	if x != nil {
		return x.SecurityWithStockexchange
	}
	return nil
}

func (x *SecurityPriceHistoryRequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *SecurityPriceHistoryRequest) GetTimeResolution() TimeResolution {
	if x != nil {
		return x.TimeResolution
	}
	return TimeResolution_NO_RESOLUTION
}

// * Returns history data for defined security
type SecurityPriceHistoryReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Security with stockExchange object (security code, stock exchange)
	SecurityWithStockexchange *SecurityWithStockExchange `protobuf:"bytes,1,opt,name=security_with_stockexchange,json=securityWithStockexchange,proto3" json:"security_with_stockexchange,omitempty"`
	// * Currency
	Currency string `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	// * List of the price entries
	PriceEntries []*PriceEntry `protobuf:"bytes,3,rep,name=price_entries,json=priceEntries,proto3" json:"price_entries,omitempty"`
	// *
	// Error information if occuirs
	Error         *Error `protobuf:"bytes,1000,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityPriceHistoryReply) Reset() {
	*x = SecurityPriceHistoryReply{}
	mi := &file_SecurityService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityPriceHistoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityPriceHistoryReply) ProtoMessage() {}

func (x *SecurityPriceHistoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_SecurityService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityPriceHistoryReply.ProtoReflect.Descriptor instead.
func (*SecurityPriceHistoryReply) Descriptor() ([]byte, []int) {
	return file_SecurityService_proto_rawDescGZIP(), []int{3}
}

func (x *SecurityPriceHistoryReply) GetSecurityWithStockexchange() *SecurityWithStockExchange {
	if x != nil {
		return x.SecurityWithStockexchange
	}
	return nil
}

func (x *SecurityPriceHistoryReply) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SecurityPriceHistoryReply) GetPriceEntries() []*PriceEntry {
	if x != nil {
		return x.PriceEntries
	}
	return nil
}

func (x *SecurityPriceHistoryReply) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type PriceEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Open price
	OpenPrice float64 `protobuf:"fixed64,1,opt,name=open_price,json=openPrice,proto3" json:"open_price,omitempty"`
	// * Close price
	ClosePrice float64 `protobuf:"fixed64,2,opt,name=close_price,json=closePrice,proto3" json:"close_price,omitempty"`
	// * High price
	HighPrice float64 `protobuf:"fixed64,3,opt,name=high_price,json=highPrice,proto3" json:"high_price,omitempty"`
	// * Low price
	LowPrice float64 `protobuf:"fixed64,4,opt,name=low_price,json=lowPrice,proto3" json:"low_price,omitempty"`
	// * Volume, can not be filled
	Volume float64 `protobuf:"fixed64,5,opt,name=volume,proto3" json:"volume,omitempty"`
	// * Open time
	OpenTime *Timestamp `protobuf:"bytes,6,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	// * Close time
	CloseTime     *Timestamp `protobuf:"bytes,7,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceEntry) Reset() {
	*x = PriceEntry{}
	mi := &file_SecurityService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceEntry) ProtoMessage() {}

func (x *PriceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_SecurityService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceEntry.ProtoReflect.Descriptor instead.
func (*PriceEntry) Descriptor() ([]byte, []int) {
	return file_SecurityService_proto_rawDescGZIP(), []int{4}
}

func (x *PriceEntry) GetOpenPrice() float64 {
	if x != nil {
		return x.OpenPrice
	}
	return 0
}

func (x *PriceEntry) GetClosePrice() float64 {
	if x != nil {
		return x.ClosePrice
	}
	return 0
}

func (x *PriceEntry) GetHighPrice() float64 {
	if x != nil {
		return x.HighPrice
	}
	return 0
}

func (x *PriceEntry) GetLowPrice() float64 {
	if x != nil {
		return x.LowPrice
	}
	return 0
}

func (x *PriceEntry) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *PriceEntry) GetOpenTime() *Timestamp {
	if x != nil {
		return x.OpenTime
	}
	return nil
}

func (x *PriceEntry) GetCloseTime() *Timestamp {
	if x != nil {
		return x.CloseTime
	}
	return nil
}

// *
// Security stock exchange info represents trading information
// about one security on the one market
type SecurityStockExchangeInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *  Stockexchange (id und issuer)
	StockExchange *StockExchange `protobuf:"bytes,1,opt,name=stock_exchange,json=stockExchange,proto3" json:"stock_exchange,omitempty"`
	// * Possible limit token for buy orders
	BuyLimitToken SecurityStockExchangeInfo_LimitToken `protobuf:"varint,2,opt,name=buy_limit_token,json=buyLimitToken,proto3,enum=com.consorsbank.module.tapi.grpc.SecurityStockExchangeInfo_LimitToken" json:"buy_limit_token,omitempty"`
	// * Possible limit token for sell orders
	SellLimitToken SecurityStockExchangeInfo_LimitToken `protobuf:"varint,3,opt,name=sell_limit_token,json=sellLimitToken,proto3,enum=com.consorsbank.module.tapi.grpc.SecurityStockExchangeInfo_LimitToken" json:"sell_limit_token,omitempty"`
	// * Buy trading data (order models, order supplements, trailing notations)
	BuyTradingTypes []*TradingPossibility `protobuf:"bytes,4,rep,name=buy_trading_types,json=buyTradingTypes,proto3" json:"buy_trading_types,omitempty"`
	// * Sell trading data (order models, order supplements, trailing notations)
	SellTradingTypes []*TradingPossibility `protobuf:"bytes,5,rep,name=sell_trading_types,json=sellTradingTypes,proto3" json:"sell_trading_types,omitempty"`
	// * Maximal order validity date
	MaximalOrderDate *Date `protobuf:"bytes,6,opt,name=maximal_order_date,json=maximalOrderDate,proto3" json:"maximal_order_date,omitempty"`
	// * Short selling mode
	ShortMode     SecurityStockExchangeInfo_ShortMode `protobuf:"varint,7,opt,name=short_mode,json=shortMode,proto3,enum=com.consorsbank.module.tapi.grpc.SecurityStockExchangeInfo_ShortMode" json:"short_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityStockExchangeInfo) Reset() {
	*x = SecurityStockExchangeInfo{}
	mi := &file_SecurityService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityStockExchangeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityStockExchangeInfo) ProtoMessage() {}

func (x *SecurityStockExchangeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_SecurityService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityStockExchangeInfo.ProtoReflect.Descriptor instead.
func (*SecurityStockExchangeInfo) Descriptor() ([]byte, []int) {
	return file_SecurityService_proto_rawDescGZIP(), []int{5}
}

func (x *SecurityStockExchangeInfo) GetStockExchange() *StockExchange {
	if x != nil {
		return x.StockExchange
	}
	return nil
}

func (x *SecurityStockExchangeInfo) GetBuyLimitToken() SecurityStockExchangeInfo_LimitToken {
	if x != nil {
		return x.BuyLimitToken
	}
	return SecurityStockExchangeInfo_LIMIT_AND_QUOTE
}

func (x *SecurityStockExchangeInfo) GetSellLimitToken() SecurityStockExchangeInfo_LimitToken {
	if x != nil {
		return x.SellLimitToken
	}
	return SecurityStockExchangeInfo_LIMIT_AND_QUOTE
}

func (x *SecurityStockExchangeInfo) GetBuyTradingTypes() []*TradingPossibility {
	if x != nil {
		return x.BuyTradingTypes
	}
	return nil
}

func (x *SecurityStockExchangeInfo) GetSellTradingTypes() []*TradingPossibility {
	if x != nil {
		return x.SellTradingTypes
	}
	return nil
}

func (x *SecurityStockExchangeInfo) GetMaximalOrderDate() *Date {
	if x != nil {
		return x.MaximalOrderDate
	}
	return nil
}

func (x *SecurityStockExchangeInfo) GetShortMode() SecurityStockExchangeInfo_ShortMode {
	if x != nil {
		return x.ShortMode
	}
	return SecurityStockExchangeInfo_NO_SHORT_MODE
}

type SecurityCode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Security code
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// * Security code type (WKN, ISIN, etc)
	CodeType      SecurityCodeType `protobuf:"varint,2,opt,name=code_type,json=codeType,proto3,enum=com.consorsbank.module.tapi.grpc.SecurityCodeType" json:"code_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityCode) Reset() {
	*x = SecurityCode{}
	mi := &file_SecurityService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityCode) ProtoMessage() {}

func (x *SecurityCode) ProtoReflect() protoreflect.Message {
	mi := &file_SecurityService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityCode.ProtoReflect.Descriptor instead.
func (*SecurityCode) Descriptor() ([]byte, []int) {
	return file_SecurityService_proto_rawDescGZIP(), []int{6}
}

func (x *SecurityCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SecurityCode) GetCodeType() SecurityCodeType {
	if x != nil {
		return x.CodeType
	}
	return SecurityCodeType_NO_CODE_TYPE
}

type SecurityWithStockExchange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Security code object
	SecurityCode *SecurityCode `protobuf:"bytes,1,opt,name=security_code,json=securityCode,proto3" json:"security_code,omitempty"`
	// * Stock exchange object
	StockExchange *StockExchange `protobuf:"bytes,2,opt,name=stock_exchange,json=stockExchange,proto3" json:"stock_exchange,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityWithStockExchange) Reset() {
	*x = SecurityWithStockExchange{}
	mi := &file_SecurityService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityWithStockExchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityWithStockExchange) ProtoMessage() {}

func (x *SecurityWithStockExchange) ProtoReflect() protoreflect.Message {
	mi := &file_SecurityService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityWithStockExchange.ProtoReflect.Descriptor instead.
func (*SecurityWithStockExchange) Descriptor() ([]byte, []int) {
	return file_SecurityService_proto_rawDescGZIP(), []int{7}
}

func (x *SecurityWithStockExchange) GetSecurityCode() *SecurityCode {
	if x != nil {
		return x.SecurityCode
	}
	return nil
}

func (x *SecurityWithStockExchange) GetStockExchange() *StockExchange {
	if x != nil {
		return x.StockExchange
	}
	return nil
}

// *
// Requests market data values for defined security with stockexchange
type SecurityMarketDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Access token
	AccessToken               string                     `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	SecurityWithStockexchange *SecurityWithStockExchange `protobuf:"bytes,2,opt,name=security_with_stockexchange,json=securityWithStockexchange,proto3" json:"security_with_stockexchange,omitempty"`
	// * Currency
	Currency      string `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityMarketDataRequest) Reset() {
	*x = SecurityMarketDataRequest{}
	mi := &file_SecurityService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityMarketDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityMarketDataRequest) ProtoMessage() {}

func (x *SecurityMarketDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SecurityService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityMarketDataRequest.ProtoReflect.Descriptor instead.
func (*SecurityMarketDataRequest) Descriptor() ([]byte, []int) {
	return file_SecurityService_proto_rawDescGZIP(), []int{8}
}

func (x *SecurityMarketDataRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SecurityMarketDataRequest) GetSecurityWithStockexchange() *SecurityWithStockExchange {
	if x != nil {
		return x.SecurityWithStockexchange
	}
	return nil
}

func (x *SecurityMarketDataRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// *
// Returns market data information
type SecurityMarketDataReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Security with stockExchange object (security code, stock exchange)
	SecurityWithStockexchange *SecurityWithStockExchange `protobuf:"bytes,1,opt,name=security_with_stockexchange,json=securityWithStockexchange,proto3" json:"security_with_stockexchange,omitempty"`
	// * Security fields, which were changed
	ChangedFields []SecurityMarketDataReply_SecurityChangedField `protobuf:"varint,2,rep,packed,name=changed_fields,json=changedFields,proto3,enum=com.consorsbank.module.tapi.grpc.SecurityMarketDataReply_SecurityChangedField" json:"changed_fields,omitempty"`
	// * Currency
	Currency string `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	// * Price of the last trade
	LastPrice float64 `protobuf:"fixed64,4,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`
	// * Volume last trade
	LastVolume float64 `protobuf:"fixed64,5,opt,name=last_volume,json=lastVolume,proto3" json:"last_volume,omitempty"`
	// * Last quote date and time
	LastDateTime *Timestamp `protobuf:"bytes,6,opt,name=last_date_time,json=lastDateTime,proto3" json:"last_date_time,omitempty"`
	// * Today number of tradings
	TodayNumTrades int32 `protobuf:"varint,7,opt,name=today_num_trades,json=todayNumTrades,proto3" json:"today_num_trades,omitempty"`
	// * Today volume
	TodayVolume float64 `protobuf:"fixed64,8,opt,name=today_volume,json=todayVolume,proto3" json:"today_volume,omitempty"`
	// * Last ask price
	AskPrice float64 `protobuf:"fixed64,9,opt,name=ask_price,json=askPrice,proto3" json:"ask_price,omitempty"`
	// * Volume last ask
	AskVolume float64 `protobuf:"fixed64,10,opt,name=ask_volume,json=askVolume,proto3" json:"ask_volume,omitempty"`
	// * Time of the last ask
	AskTime *Timestamp `protobuf:"bytes,11,opt,name=ask_time,json=askTime,proto3" json:"ask_time,omitempty"`
	// * Last bid price
	BidPrice float64 `protobuf:"fixed64,12,opt,name=bid_price,json=bidPrice,proto3" json:"bid_price,omitempty"`
	// * Volume last bid
	BidVolume float64 `protobuf:"fixed64,13,opt,name=bid_volume,json=bidVolume,proto3" json:"bid_volume,omitempty"`
	// * Time of the last bid
	BidTime *Timestamp `protobuf:"bytes,14,opt,name=bid_time,json=bidTime,proto3" json:"bid_time,omitempty"`
	// * Quote of the previous trading day
	PreviousPrice float64 `protobuf:"fixed64,15,opt,name=previous_price,json=previousPrice,proto3" json:"previous_price,omitempty"`
	// * Date of the previous trading day
	PreviousDate *Date `protobuf:"bytes,16,opt,name=previous_date,json=previousDate,proto3" json:"previous_date,omitempty"`
	// * Relative difference to the previous day
	RelativeDiff float64 `protobuf:"fixed64,17,opt,name=relative_diff,json=relativeDiff,proto3" json:"relative_diff,omitempty"`
	// * Absolute difference to the previous day
	AbsDiff float64 `protobuf:"fixed64,18,opt,name=abs_diff,json=absDiff,proto3" json:"abs_diff,omitempty"`
	// * Highest price
	HighPrice float64 `protobuf:"fixed64,19,opt,name=high_price,json=highPrice,proto3" json:"high_price,omitempty"`
	// * Lowest price
	LowPrice float64 `protobuf:"fixed64,20,opt,name=low_price,json=lowPrice,proto3" json:"low_price,omitempty"`
	// * Price at opening
	OpenPrice float64 `protobuf:"fixed64,21,opt,name=open_price,json=openPrice,proto3" json:"open_price,omitempty"`
	// * Highest price of the previous week
	WeekHighPrice float64 `protobuf:"fixed64,22,opt,name=week_high_price,json=weekHighPrice,proto3" json:"week_high_price,omitempty"`
	// * Date of highest price of the previous week
	DateWeekHigh *Date `protobuf:"bytes,23,opt,name=date_week_high,json=dateWeekHigh,proto3" json:"date_week_high,omitempty"`
	// * Lowest price of the previous week
	WeekLowPrice float64 `protobuf:"fixed64,24,opt,name=week_low_price,json=weekLowPrice,proto3" json:"week_low_price,omitempty"`
	// * Date of lowest price of the previous week
	DateWeekLow *Date `protobuf:"bytes,25,opt,name=date_week_low,json=dateWeekLow,proto3" json:"date_week_low,omitempty"`
	// * Highest price of the previous month
	MonthHighPrice float64 `protobuf:"fixed64,26,opt,name=month_high_price,json=monthHighPrice,proto3" json:"month_high_price,omitempty"`
	// * Date of highest price of the previous month
	DateMonthHigh *Date `protobuf:"bytes,27,opt,name=date_month_high,json=dateMonthHigh,proto3" json:"date_month_high,omitempty"`
	// * Lowest price of the previous month
	MonthLowPrice float64 `protobuf:"fixed64,28,opt,name=month_low_price,json=monthLowPrice,proto3" json:"month_low_price,omitempty"`
	// * Date of lowest price of the previous month
	DateMonthLow *Date `protobuf:"bytes,29,opt,name=date_month_low,json=dateMonthLow,proto3" json:"date_month_low,omitempty"`
	// * Highest price of the current year
	YearHighPrice float64 `protobuf:"fixed64,30,opt,name=year_high_price,json=yearHighPrice,proto3" json:"year_high_price,omitempty"`
	// * Date of the highest price of the current year
	DateYearHigh *Date `protobuf:"bytes,31,opt,name=date_year_high,json=dateYearHigh,proto3" json:"date_year_high,omitempty"`
	// * Lowest price of the current year
	YearLowPrice float64 `protobuf:"fixed64,32,opt,name=year_low_price,json=yearLowPrice,proto3" json:"year_low_price,omitempty"`
	// * Date of the lowest price of the current year
	DateYearLow *Date `protobuf:"bytes,33,opt,name=date_year_low,json=dateYearLow,proto3" json:"date_year_low,omitempty"`
	// * Addendum of the last price.
	LastAddendum string `protobuf:"bytes,34,opt,name=last_addendum,json=lastAddendum,proto3" json:"last_addendum,omitempty"`
	// * Trading phase
	TradingPhase TradingPhase `protobuf:"varint,35,opt,name=trading_phase,json=tradingPhase,proto3,enum=com.consorsbank.module.tapi.grpc.TradingPhase" json:"trading_phase,omitempty"`
	// * Indicative price
	IndicativePrice float64 `protobuf:"fixed64,36,opt,name=indicative_price,json=indicativePrice,proto3" json:"indicative_price,omitempty"`
	// * Trading volume corresponding to the last price
	PrevalenceVolume float64 `protobuf:"fixed64,37,opt,name=prevalence_volume,json=prevalenceVolume,proto3" json:"prevalence_volume,omitempty"`
	// *
	// Error information if occuirs
	Error         *Error `protobuf:"bytes,1000,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityMarketDataReply) Reset() {
	*x = SecurityMarketDataReply{}
	mi := &file_SecurityService_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityMarketDataReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityMarketDataReply) ProtoMessage() {}

func (x *SecurityMarketDataReply) ProtoReflect() protoreflect.Message {
	mi := &file_SecurityService_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityMarketDataReply.ProtoReflect.Descriptor instead.
func (*SecurityMarketDataReply) Descriptor() ([]byte, []int) {
	return file_SecurityService_proto_rawDescGZIP(), []int{9}
}

func (x *SecurityMarketDataReply) GetSecurityWithStockexchange() *SecurityWithStockExchange {
	if x != nil {
		return x.SecurityWithStockexchange
	}
	return nil
}

func (x *SecurityMarketDataReply) GetChangedFields() []SecurityMarketDataReply_SecurityChangedField {
	if x != nil {
		return x.ChangedFields
	}
	return nil
}

func (x *SecurityMarketDataReply) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SecurityMarketDataReply) GetLastPrice() float64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

func (x *SecurityMarketDataReply) GetLastVolume() float64 {
	if x != nil {
		return x.LastVolume
	}
	return 0
}

func (x *SecurityMarketDataReply) GetLastDateTime() *Timestamp {
	if x != nil {
		return x.LastDateTime
	}
	return nil
}

func (x *SecurityMarketDataReply) GetTodayNumTrades() int32 {
	if x != nil {
		return x.TodayNumTrades
	}
	return 0
}

func (x *SecurityMarketDataReply) GetTodayVolume() float64 {
	if x != nil {
		return x.TodayVolume
	}
	return 0
}

func (x *SecurityMarketDataReply) GetAskPrice() float64 {
	if x != nil {
		return x.AskPrice
	}
	return 0
}

func (x *SecurityMarketDataReply) GetAskVolume() float64 {
	if x != nil {
		return x.AskVolume
	}
	return 0
}

func (x *SecurityMarketDataReply) GetAskTime() *Timestamp {
	if x != nil {
		return x.AskTime
	}
	return nil
}

func (x *SecurityMarketDataReply) GetBidPrice() float64 {
	if x != nil {
		return x.BidPrice
	}
	return 0
}

func (x *SecurityMarketDataReply) GetBidVolume() float64 {
	if x != nil {
		return x.BidVolume
	}
	return 0
}

func (x *SecurityMarketDataReply) GetBidTime() *Timestamp {
	if x != nil {
		return x.BidTime
	}
	return nil
}

func (x *SecurityMarketDataReply) GetPreviousPrice() float64 {
	if x != nil {
		return x.PreviousPrice
	}
	return 0
}

func (x *SecurityMarketDataReply) GetPreviousDate() *Date {
	if x != nil {
		return x.PreviousDate
	}
	return nil
}

func (x *SecurityMarketDataReply) GetRelativeDiff() float64 {
	if x != nil {
		return x.RelativeDiff
	}
	return 0
}

func (x *SecurityMarketDataReply) GetAbsDiff() float64 {
	if x != nil {
		return x.AbsDiff
	}
	return 0
}

func (x *SecurityMarketDataReply) GetHighPrice() float64 {
	if x != nil {
		return x.HighPrice
	}
	return 0
}

func (x *SecurityMarketDataReply) GetLowPrice() float64 {
	if x != nil {
		return x.LowPrice
	}
	return 0
}

func (x *SecurityMarketDataReply) GetOpenPrice() float64 {
	if x != nil {
		return x.OpenPrice
	}
	return 0
}

func (x *SecurityMarketDataReply) GetWeekHighPrice() float64 {
	if x != nil {
		return x.WeekHighPrice
	}
	return 0
}

func (x *SecurityMarketDataReply) GetDateWeekHigh() *Date {
	if x != nil {
		return x.DateWeekHigh
	}
	return nil
}

func (x *SecurityMarketDataReply) GetWeekLowPrice() float64 {
	if x != nil {
		return x.WeekLowPrice
	}
	return 0
}

func (x *SecurityMarketDataReply) GetDateWeekLow() *Date {
	if x != nil {
		return x.DateWeekLow
	}
	return nil
}

func (x *SecurityMarketDataReply) GetMonthHighPrice() float64 {
	if x != nil {
		return x.MonthHighPrice
	}
	return 0
}

func (x *SecurityMarketDataReply) GetDateMonthHigh() *Date {
	if x != nil {
		return x.DateMonthHigh
	}
	return nil
}

func (x *SecurityMarketDataReply) GetMonthLowPrice() float64 {
	if x != nil {
		return x.MonthLowPrice
	}
	return 0
}

func (x *SecurityMarketDataReply) GetDateMonthLow() *Date {
	if x != nil {
		return x.DateMonthLow
	}
	return nil
}

func (x *SecurityMarketDataReply) GetYearHighPrice() float64 {
	if x != nil {
		return x.YearHighPrice
	}
	return 0
}

func (x *SecurityMarketDataReply) GetDateYearHigh() *Date {
	if x != nil {
		return x.DateYearHigh
	}
	return nil
}

func (x *SecurityMarketDataReply) GetYearLowPrice() float64 {
	if x != nil {
		return x.YearLowPrice
	}
	return 0
}

func (x *SecurityMarketDataReply) GetDateYearLow() *Date {
	if x != nil {
		return x.DateYearLow
	}
	return nil
}

func (x *SecurityMarketDataReply) GetLastAddendum() string {
	if x != nil {
		return x.LastAddendum
	}
	return ""
}

func (x *SecurityMarketDataReply) GetTradingPhase() TradingPhase {
	if x != nil {
		return x.TradingPhase
	}
	return TradingPhase_NONE
}

func (x *SecurityMarketDataReply) GetIndicativePrice() float64 {
	if x != nil {
		return x.IndicativePrice
	}
	return 0
}

func (x *SecurityMarketDataReply) GetPrevalenceVolume() float64 {
	if x != nil {
		return x.PrevalenceVolume
	}
	return 0
}

func (x *SecurityMarketDataReply) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// *
// Requests orderbook data for security with stockexchange
type SecurityOrderBookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Access token
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// *
	// Security with stockExchange object (security code, stock exchange)
	SecurityWithStockexchange *SecurityWithStockExchange `protobuf:"bytes,2,opt,name=security_with_stockexchange,json=securityWithStockexchange,proto3" json:"security_with_stockexchange,omitempty"`
	// *
	// Requested currency. If not filled used default currency.
	// Otherwise values will be converted to requested currency.
	Currency      string `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityOrderBookRequest) Reset() {
	*x = SecurityOrderBookRequest{}
	mi := &file_SecurityService_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityOrderBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityOrderBookRequest) ProtoMessage() {}

func (x *SecurityOrderBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SecurityService_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityOrderBookRequest.ProtoReflect.Descriptor instead.
func (*SecurityOrderBookRequest) Descriptor() ([]byte, []int) {
	return file_SecurityService_proto_rawDescGZIP(), []int{10}
}

func (x *SecurityOrderBookRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SecurityOrderBookRequest) GetSecurityWithStockexchange() *SecurityWithStockExchange {
	if x != nil {
		return x.SecurityWithStockexchange
	}
	return nil
}

func (x *SecurityOrderBookRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// *
// SecurityOrderBookReply represents information with orderbook market data.
// Currently this information is avialable for the Xetra stock exchange for the accepted
// for the second level market data instruments
type SecurityOrderBookReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Security with stock exchange object (security code, stock exchange)
	SecurityWithStockexchange *SecurityWithStockExchange `protobuf:"bytes,1,opt,name=security_with_stockexchange,json=securityWithStockexchange,proto3" json:"security_with_stockexchange,omitempty"`
	// * Currency of the order book entries
	Currency string `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	// * List of the order book entries
	OrderBookEntries []*SecurityOrderBookReply_OrderBookEntry `protobuf:"bytes,3,rep,name=order_book_entries,json=orderBookEntries,proto3" json:"order_book_entries,omitempty"`
	// *
	// Error information if occuirs
	Error         *Error `protobuf:"bytes,1000,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityOrderBookReply) Reset() {
	*x = SecurityOrderBookReply{}
	mi := &file_SecurityService_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityOrderBookReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityOrderBookReply) ProtoMessage() {}

func (x *SecurityOrderBookReply) ProtoReflect() protoreflect.Message {
	mi := &file_SecurityService_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityOrderBookReply.ProtoReflect.Descriptor instead.
func (*SecurityOrderBookReply) Descriptor() ([]byte, []int) {
	return file_SecurityService_proto_rawDescGZIP(), []int{11}
}

func (x *SecurityOrderBookReply) GetSecurityWithStockexchange() *SecurityWithStockExchange {
	if x != nil {
		return x.SecurityWithStockexchange
	}
	return nil
}

func (x *SecurityOrderBookReply) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SecurityOrderBookReply) GetOrderBookEntries() []*SecurityOrderBookReply_OrderBookEntry {
	if x != nil {
		return x.OrderBookEntries
	}
	return nil
}

func (x *SecurityOrderBookReply) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// *
// CurrencyRateRequest used for the determination of the currency rate from one currency rate to second  currency.
// Results depends from user market data aboniment and can be realtime or delayed.
type CurrencyRateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Access token
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// *
	// Source currency
	CurrencyFrom string `protobuf:"bytes,2,opt,name=currency_from,json=currencyFrom,proto3" json:"currency_from,omitempty"`
	// *
	// Target currency
	CurrencyTo    string `protobuf:"bytes,3,opt,name=currency_to,json=currencyTo,proto3" json:"currency_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrencyRateRequest) Reset() {
	*x = CurrencyRateRequest{}
	mi := &file_SecurityService_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyRateRequest) ProtoMessage() {}

func (x *CurrencyRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SecurityService_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyRateRequest.ProtoReflect.Descriptor instead.
func (*CurrencyRateRequest) Descriptor() ([]byte, []int) {
	return file_SecurityService_proto_rawDescGZIP(), []int{12}
}

func (x *CurrencyRateRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *CurrencyRateRequest) GetCurrencyFrom() string {
	if x != nil {
		return x.CurrencyFrom
	}
	return ""
}

func (x *CurrencyRateRequest) GetCurrencyTo() string {
	if x != nil {
		return x.CurrencyTo
	}
	return ""
}

// *
// Returns currency rate
type CurrencyRateReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Source currency
	CurrencyFrom string `protobuf:"bytes,1,opt,name=currency_from,json=currencyFrom,proto3" json:"currency_from,omitempty"`
	// * Target currency
	CurrencyTo string `protobuf:"bytes,2,opt,name=currency_to,json=currencyTo,proto3" json:"currency_to,omitempty"`
	// * Currency rate
	CurrencyRate float64 `protobuf:"fixed64,3,opt,name=currency_rate,json=currencyRate,proto3" json:"currency_rate,omitempty"`
	// * Error information if occuirs
	Error         *Error `protobuf:"bytes,1000,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrencyRateReply) Reset() {
	*x = CurrencyRateReply{}
	mi := &file_SecurityService_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyRateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyRateReply) ProtoMessage() {}

func (x *CurrencyRateReply) ProtoReflect() protoreflect.Message {
	mi := &file_SecurityService_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyRateReply.ProtoReflect.Descriptor instead.
func (*CurrencyRateReply) Descriptor() ([]byte, []int) {
	return file_SecurityService_proto_rawDescGZIP(), []int{13}
}

func (x *CurrencyRateReply) GetCurrencyFrom() string {
	if x != nil {
		return x.CurrencyFrom
	}
	return ""
}

func (x *CurrencyRateReply) GetCurrencyTo() string {
	if x != nil {
		return x.CurrencyTo
	}
	return ""
}

func (x *CurrencyRateReply) GetCurrencyRate() float64 {
	if x != nil {
		return x.CurrencyRate
	}
	return 0
}

func (x *CurrencyRateReply) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// * Orderbook entry contains data about one level of the order book.
// This is bid price, ask price, bid volume, ask volume. Entries with lower index have lower ask and higer bid prices.
type SecurityOrderBookReply_OrderBookEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Bid price
	BidPrice float64 `protobuf:"fixed64,1,opt,name=bid_price,json=bidPrice,proto3" json:"bid_price,omitempty"`
	// * Ask price
	AskPrice float64 `protobuf:"fixed64,2,opt,name=ask_price,json=askPrice,proto3" json:"ask_price,omitempty"`
	// * Bid volume
	BidVolume float64 `protobuf:"fixed64,3,opt,name=bid_volume,json=bidVolume,proto3" json:"bid_volume,omitempty"`
	// * Ask volume
	AskVolume     float64 `protobuf:"fixed64,4,opt,name=ask_volume,json=askVolume,proto3" json:"ask_volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityOrderBookReply_OrderBookEntry) Reset() {
	*x = SecurityOrderBookReply_OrderBookEntry{}
	mi := &file_SecurityService_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityOrderBookReply_OrderBookEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityOrderBookReply_OrderBookEntry) ProtoMessage() {}

func (x *SecurityOrderBookReply_OrderBookEntry) ProtoReflect() protoreflect.Message {
	mi := &file_SecurityService_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityOrderBookReply_OrderBookEntry.ProtoReflect.Descriptor instead.
func (*SecurityOrderBookReply_OrderBookEntry) Descriptor() ([]byte, []int) {
	return file_SecurityService_proto_rawDescGZIP(), []int{11, 0}
}

func (x *SecurityOrderBookReply_OrderBookEntry) GetBidPrice() float64 {
	if x != nil {
		return x.BidPrice
	}
	return 0
}

func (x *SecurityOrderBookReply_OrderBookEntry) GetAskPrice() float64 {
	if x != nil {
		return x.AskPrice
	}
	return 0
}

func (x *SecurityOrderBookReply_OrderBookEntry) GetBidVolume() float64 {
	if x != nil {
		return x.BidVolume
	}
	return 0
}

func (x *SecurityOrderBookReply_OrderBookEntry) GetAskVolume() float64 {
	if x != nil {
		return x.AskVolume
	}
	return 0
}

var File_SecurityService_proto protoreflect.FileDescriptor

const file_SecurityService_proto_rawDesc = "" +
	"\n" +
	"\x15SecurityService.proto\x12 com.consorsbank.module.tapi.grpc\x1a\fCommon.proto\x1a\x1aStockExchangeService.proto\x1a\x12TradingTypes.proto\"\x8d\x01\n" +
	"\x13SecurityInfoRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12S\n" +
	"\rsecurity_code\x18\x02 \x01(\v2..com.consorsbank.module.tapi.grpc.SecurityCodeR\fsecurityCode\"\xce\x03\n" +
	"\x11SecurityInfoReply\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12V\n" +
	"\x0esecurity_class\x18\x02 \x01(\x0e2/.com.consorsbank.module.tapi.grpc.SecurityClassR\rsecurityClass\x12U\n" +
	"\x0esecurity_codes\x18\x03 \x03(\v2..com.consorsbank.module.tapi.grpc.SecurityCodeR\rsecurityCodes\x12m\n" +
	"\x14stock_exchange_infos\x18\x04 \x03(\v2;.com.consorsbank.module.tapi.grpc.SecurityStockExchangeInfoR\x12stockExchangeInfos\x12G\n" +
	"\tunit_note\x18\x05 \x01(\x0e2*.com.consorsbank.module.tapi.grpc.UnitNoteR\bunitNote\x12>\n" +
	"\x05error\x18\xe8\a \x01(\v2'.com.consorsbank.module.tapi.grpc.ErrorR\x05error\"\xac\x02\n" +
	"\x1bSecurityPriceHistoryRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12{\n" +
	"\x1bsecurity_with_stockexchange\x18\x02 \x01(\v2;.com.consorsbank.module.tapi.grpc.SecurityWithStockExchangeR\x19securityWithStockexchange\x12\x12\n" +
	"\x04days\x18\x03 \x01(\x05R\x04days\x12Y\n" +
	"\x0ftime_resolution\x18\x04 \x01(\x0e20.com.consorsbank.module.tapi.grpc.TimeResolutionR\x0etimeResolution\"\xc7\x02\n" +
	"\x19SecurityPriceHistoryReply\x12{\n" +
	"\x1bsecurity_with_stockexchange\x18\x01 \x01(\v2;.com.consorsbank.module.tapi.grpc.SecurityWithStockExchangeR\x19securityWithStockexchange\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12Q\n" +
	"\rprice_entries\x18\x03 \x03(\v2,.com.consorsbank.module.tapi.grpc.PriceEntryR\fpriceEntries\x12>\n" +
	"\x05error\x18\xe8\a \x01(\v2'.com.consorsbank.module.tapi.grpc.ErrorR\x05error\"\xb6\x02\n" +
	"\n" +
	"PriceEntry\x12\x1d\n" +
	"\n" +
	"open_price\x18\x01 \x01(\x01R\topenPrice\x12\x1f\n" +
	"\vclose_price\x18\x02 \x01(\x01R\n" +
	"closePrice\x12\x1d\n" +
	"\n" +
	"high_price\x18\x03 \x01(\x01R\thighPrice\x12\x1b\n" +
	"\tlow_price\x18\x04 \x01(\x01R\blowPrice\x12\x16\n" +
	"\x06volume\x18\x05 \x01(\x01R\x06volume\x12H\n" +
	"\topen_time\x18\x06 \x01(\v2+.com.consorsbank.module.tapi.grpc.TimestampR\bopenTime\x12J\n" +
	"\n" +
	"close_time\x18\a \x01(\v2+.com.consorsbank.module.tapi.grpc.TimestampR\tcloseTime\"\x96\a\n" +
	"\x19SecurityStockExchangeInfo\x12V\n" +
	"\x0estock_exchange\x18\x01 \x01(\v2/.com.consorsbank.module.tapi.grpc.StockExchangeR\rstockExchange\x12n\n" +
	"\x0fbuy_limit_token\x18\x02 \x01(\x0e2F.com.consorsbank.module.tapi.grpc.SecurityStockExchangeInfo.LimitTokenR\rbuyLimitToken\x12p\n" +
	"\x10sell_limit_token\x18\x03 \x01(\x0e2F.com.consorsbank.module.tapi.grpc.SecurityStockExchangeInfo.LimitTokenR\x0esellLimitToken\x12`\n" +
	"\x11buy_trading_types\x18\x04 \x03(\v24.com.consorsbank.module.tapi.grpc.TradingPossibilityR\x0fbuyTradingTypes\x12b\n" +
	"\x12sell_trading_types\x18\x05 \x03(\v24.com.consorsbank.module.tapi.grpc.TradingPossibilityR\x10sellTradingTypes\x12T\n" +
	"\x12maximal_order_date\x18\x06 \x01(\v2&.com.consorsbank.module.tapi.grpc.DateR\x10maximalOrderDate\x12d\n" +
	"\n" +
	"short_mode\x18\a \x01(\x0e2E.com.consorsbank.module.tapi.grpc.SecurityStockExchangeInfo.ShortModeR\tshortMode\"z\n" +
	"\tShortMode\x12\x11\n" +
	"\rNO_SHORT_MODE\x10\x00\x12\a\n" +
	"\x03YES\x10\x01\x12\x06\n" +
	"\x02NO\x10\x02\x12\x10\n" +
	"\fTEMPORARY_NO\x10\x03\x12\f\n" +
	"\bINTRADAY\x10\x04\x12\r\n" +
	"\tOVERNIGHT\x10\x05\x12\x1a\n" +
	"\x16INTRADAY_AND_OVERNIGHT\x10\x06\"A\n" +
	"\n" +
	"LimitToken\x12\x13\n" +
	"\x0fLIMIT_AND_QUOTE\x10\x00\x12\x0e\n" +
	"\n" +
	"QUOTE_ONLY\x10\x01\x12\x0e\n" +
	"\n" +
	"LIMIT_ONLY\x10\x02\"s\n" +
	"\fSecurityCode\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12O\n" +
	"\tcode_type\x18\x02 \x01(\x0e22.com.consorsbank.module.tapi.grpc.SecurityCodeTypeR\bcodeType\"\xc8\x01\n" +
	"\x19SecurityWithStockExchange\x12S\n" +
	"\rsecurity_code\x18\x01 \x01(\v2..com.consorsbank.module.tapi.grpc.SecurityCodeR\fsecurityCode\x12V\n" +
	"\x0estock_exchange\x18\x02 \x01(\v2/.com.consorsbank.module.tapi.grpc.StockExchangeR\rstockExchange\"\xd7\x01\n" +
	"\x19SecurityMarketDataRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12{\n" +
	"\x1bsecurity_with_stockexchange\x18\x02 \x01(\v2;.com.consorsbank.module.tapi.grpc.SecurityWithStockExchangeR\x19securityWithStockexchange\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"\x8a\x15\n" +
	"\x17SecurityMarketDataReply\x12{\n" +
	"\x1bsecurity_with_stockexchange\x18\x01 \x01(\v2;.com.consorsbank.module.tapi.grpc.SecurityWithStockExchangeR\x19securityWithStockexchange\x12u\n" +
	"\x0echanged_fields\x18\x02 \x03(\x0e2N.com.consorsbank.module.tapi.grpc.SecurityMarketDataReply.SecurityChangedFieldR\rchangedFields\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"last_price\x18\x04 \x01(\x01R\tlastPrice\x12\x1f\n" +
	"\vlast_volume\x18\x05 \x01(\x01R\n" +
	"lastVolume\x12Q\n" +
	"\x0elast_date_time\x18\x06 \x01(\v2+.com.consorsbank.module.tapi.grpc.TimestampR\flastDateTime\x12(\n" +
	"\x10today_num_trades\x18\a \x01(\x05R\x0etodayNumTrades\x12!\n" +
	"\ftoday_volume\x18\b \x01(\x01R\vtodayVolume\x12\x1b\n" +
	"\task_price\x18\t \x01(\x01R\baskPrice\x12\x1d\n" +
	"\n" +
	"ask_volume\x18\n" +
	" \x01(\x01R\taskVolume\x12F\n" +
	"\bask_time\x18\v \x01(\v2+.com.consorsbank.module.tapi.grpc.TimestampR\aaskTime\x12\x1b\n" +
	"\tbid_price\x18\f \x01(\x01R\bbidPrice\x12\x1d\n" +
	"\n" +
	"bid_volume\x18\r \x01(\x01R\tbidVolume\x12F\n" +
	"\bbid_time\x18\x0e \x01(\v2+.com.consorsbank.module.tapi.grpc.TimestampR\abidTime\x12%\n" +
	"\x0eprevious_price\x18\x0f \x01(\x01R\rpreviousPrice\x12K\n" +
	"\rprevious_date\x18\x10 \x01(\v2&.com.consorsbank.module.tapi.grpc.DateR\fpreviousDate\x12#\n" +
	"\rrelative_diff\x18\x11 \x01(\x01R\frelativeDiff\x12\x19\n" +
	"\babs_diff\x18\x12 \x01(\x01R\aabsDiff\x12\x1d\n" +
	"\n" +
	"high_price\x18\x13 \x01(\x01R\thighPrice\x12\x1b\n" +
	"\tlow_price\x18\x14 \x01(\x01R\blowPrice\x12\x1d\n" +
	"\n" +
	"open_price\x18\x15 \x01(\x01R\topenPrice\x12&\n" +
	"\x0fweek_high_price\x18\x16 \x01(\x01R\rweekHighPrice\x12L\n" +
	"\x0edate_week_high\x18\x17 \x01(\v2&.com.consorsbank.module.tapi.grpc.DateR\fdateWeekHigh\x12$\n" +
	"\x0eweek_low_price\x18\x18 \x01(\x01R\fweekLowPrice\x12J\n" +
	"\rdate_week_low\x18\x19 \x01(\v2&.com.consorsbank.module.tapi.grpc.DateR\vdateWeekLow\x12(\n" +
	"\x10month_high_price\x18\x1a \x01(\x01R\x0emonthHighPrice\x12N\n" +
	"\x0fdate_month_high\x18\x1b \x01(\v2&.com.consorsbank.module.tapi.grpc.DateR\rdateMonthHigh\x12&\n" +
	"\x0fmonth_low_price\x18\x1c \x01(\x01R\rmonthLowPrice\x12L\n" +
	"\x0edate_month_low\x18\x1d \x01(\v2&.com.consorsbank.module.tapi.grpc.DateR\fdateMonthLow\x12&\n" +
	"\x0fyear_high_price\x18\x1e \x01(\x01R\ryearHighPrice\x12L\n" +
	"\x0edate_year_high\x18\x1f \x01(\v2&.com.consorsbank.module.tapi.grpc.DateR\fdateYearHigh\x12$\n" +
	"\x0eyear_low_price\x18  \x01(\x01R\fyearLowPrice\x12J\n" +
	"\rdate_year_low\x18! \x01(\v2&.com.consorsbank.module.tapi.grpc.DateR\vdateYearLow\x12#\n" +
	"\rlast_addendum\x18\" \x01(\tR\flastAddendum\x12S\n" +
	"\rtrading_phase\x18# \x01(\x0e2..com.consorsbank.module.tapi.grpc.TradingPhaseR\ftradingPhase\x12)\n" +
	"\x10indicative_price\x18$ \x01(\x01R\x0findicativePrice\x12+\n" +
	"\x11prevalence_volume\x18% \x01(\x01R\x10prevalenceVolume\x12>\n" +
	"\x05error\x18\xe8\a \x01(\v2'.com.consorsbank.module.tapi.grpc.ErrorR\x05error\"\x95\x05\n" +
	"\x14SecurityChangedField\x12\b\n" +
	"\x04NONE\x10\x00\x12\x0e\n" +
	"\n" +
	"LAST_PRICE\x10\x04\x12\x0f\n" +
	"\vLAST_VOLUME\x10\x05\x12\x12\n" +
	"\x0eLAST_DATE_TIME\x10\x06\x12\x14\n" +
	"\x10TODAY_NUM_TRADES\x10\a\x12\x10\n" +
	"\fTODAY_VOLUME\x10\b\x12\r\n" +
	"\tASK_PRICE\x10\t\x12\x0e\n" +
	"\n" +
	"ASK_VOLUME\x10\n" +
	"\x12\f\n" +
	"\bASK_TIME\x10\v\x12\r\n" +
	"\tBID_PRICE\x10\f\x12\x0e\n" +
	"\n" +
	"BID_VOLUME\x10\r\x12\f\n" +
	"\bBID_TIME\x10\x0e\x12\x12\n" +
	"\x0ePREVIOUS_PRICE\x10\x0f\x12\x11\n" +
	"\rPREVIOUS_DATE\x10\x10\x12\x11\n" +
	"\rRELATIVE_DIFF\x10\x11\x12\f\n" +
	"\bABS_DIFF\x10\x12\x12\x0e\n" +
	"\n" +
	"HIGH_PRICE\x10\x13\x12\r\n" +
	"\tLOW_PRICE\x10\x14\x12\x0e\n" +
	"\n" +
	"OPEN_PRICE\x10\x15\x12\x13\n" +
	"\x0fWEEK_HIGH_PRICE\x10\x16\x12\x12\n" +
	"\x0eDATE_WEEK_HIGH\x10\x17\x12\x12\n" +
	"\x0eWEEK_LOW_PRICE\x10\x18\x12\x11\n" +
	"\rDATE_WEEK_LOW\x10\x19\x12\x14\n" +
	"\x10MONTH_HIGH_PRICE\x10\x1a\x12\x13\n" +
	"\x0fDATE_MONTH_HIGH\x10\x1b\x12\x13\n" +
	"\x0fMONTH_LOW_PRICE\x10\x1c\x12\x12\n" +
	"\x0eDATE_MONTH_LOW\x10\x1d\x12\x13\n" +
	"\x0fYEAR_HIGH_PRICE\x10\x1e\x12\x12\n" +
	"\x0eDATE_YEAR_HIGH\x10\x1f\x12\x12\n" +
	"\x0eYEAR_LOW_PRICE\x10 \x12\x11\n" +
	"\rDATE_YEAR_LOW\x10!\x12\x11\n" +
	"\rLAST_ADDENDUM\x10\"\x12\x11\n" +
	"\rTRADING_PHASE\x10#\x12\x14\n" +
	"\x10INDICATIVE_PRICE\x10$\x12\x15\n" +
	"\x11PREVALENCE_VOLUME\x10%\"\xd6\x01\n" +
	"\x18SecurityOrderBookRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12{\n" +
	"\x1bsecurity_with_stockexchange\x18\x02 \x01(\v2;.com.consorsbank.module.tapi.grpc.SecurityWithStockExchangeR\x19securityWithStockexchange\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"\xf3\x03\n" +
	"\x16SecurityOrderBookReply\x12{\n" +
	"\x1bsecurity_with_stockexchange\x18\x01 \x01(\v2;.com.consorsbank.module.tapi.grpc.SecurityWithStockExchangeR\x19securityWithStockexchange\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12u\n" +
	"\x12order_book_entries\x18\x03 \x03(\v2G.com.consorsbank.module.tapi.grpc.SecurityOrderBookReply.OrderBookEntryR\x10orderBookEntries\x12>\n" +
	"\x05error\x18\xe8\a \x01(\v2'.com.consorsbank.module.tapi.grpc.ErrorR\x05error\x1a\x88\x01\n" +
	"\x0eOrderBookEntry\x12\x1b\n" +
	"\tbid_price\x18\x01 \x01(\x01R\bbidPrice\x12\x1b\n" +
	"\task_price\x18\x02 \x01(\x01R\baskPrice\x12\x1d\n" +
	"\n" +
	"bid_volume\x18\x03 \x01(\x01R\tbidVolume\x12\x1d\n" +
	"\n" +
	"ask_volume\x18\x04 \x01(\x01R\taskVolume\"~\n" +
	"\x13CurrencyRateRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rcurrency_from\x18\x02 \x01(\tR\fcurrencyFrom\x12\x1f\n" +
	"\vcurrency_to\x18\x03 \x01(\tR\n" +
	"currencyTo\"\xbe\x01\n" +
	"\x11CurrencyRateReply\x12#\n" +
	"\rcurrency_from\x18\x01 \x01(\tR\fcurrencyFrom\x12\x1f\n" +
	"\vcurrency_to\x18\x02 \x01(\tR\n" +
	"currencyTo\x12#\n" +
	"\rcurrency_rate\x18\x03 \x01(\x01R\fcurrencyRate\x12>\n" +
	"\x05error\x18\xe8\a \x01(\v2'.com.consorsbank.module.tapi.grpc.ErrorR\x05error*X\n" +
	"\x0eTimeResolution\x12\x11\n" +
	"\rNO_RESOLUTION\x10\x00\x12\b\n" +
	"\x04TICK\x10\x01\x12\n" +
	"\n" +
	"\x06SECOND\x10\x02\x12\n" +
	"\n" +
	"\x06MINUTE\x10\x03\x12\b\n" +
	"\x04HOUR\x10\x04\x12\a\n" +
	"\x03DAY\x10\x05*\x86\x01\n" +
	"\x10SecurityCodeType\x12\x10\n" +
	"\fNO_CODE_TYPE\x10\x00\x12\a\n" +
	"\x03WKN\x10\x01\x12\b\n" +
	"\x04ISIN\x10\x02\x12\x0f\n" +
	"\vID_NOTATION\x10\x03\x12\n" +
	"\n" +
	"\x06ID_OSI\x10\x04\x12\x11\n" +
	"\rID_INSTRUMENT\x10\x05\x12\f\n" +
	"\bMNEMONIC\x10\x06\x12\x0f\n" +
	"\vMNEMONIC_US\x10\a*\xa4\x02\n" +
	"\rSecurityClass\x12\x15\n" +
	"\x11NO_SECURITY_CLASS\x10\x00\x12\t\n" +
	"\x05STOCK\x10\x01\x12\b\n" +
	"\x04BOND\x10\x02\x12\x0f\n" +
	"\vCERTIFICATE\x10\x03\x12\x12\n" +
	"\x0ePRECIOUS_METAL\x10\x04\x12\x1d\n" +
	"\x19PARTICIPATION_CERTIFICATE\x10\x05\x12\t\n" +
	"\x05FUNDS\x10\x06\x12\x10\n" +
	"\fMUTUAL_FUNDS\x10\a\x12\v\n" +
	"\aWARRANT\x10\b\x12\n" +
	"\n" +
	"\x06FUTURE\x10\t\x12\t\n" +
	"\x05INDEX\x10\n" +
	"\x12\n" +
	"\n" +
	"\x06OTHERS\x10\v\x12\r\n" +
	"\tFUTURE_C1\x10\f\x12\r\n" +
	"\tFUTURE_C2\x10\r\x12\r\n" +
	"\tFUTURE_C3\x10\x0e\x12\f\n" +
	"\bTRACKERS\x10\x0f\x12\f\n" +
	"\bCURRENCY\x10\x10\x12\r\n" +
	"\tCOMMODITY\x10\x11*\xce\x01\n" +
	"\fTradingPhase\x12\b\n" +
	"\x04NONE\x10\x00\x12\f\n" +
	"\bPRETRADE\x10\x01\x12\r\n" +
	"\tPOSTTRADE\x10\x02\x12\t\n" +
	"\x05START\x10\x03\x12\a\n" +
	"\x03END\x10\x04\x12\b\n" +
	"\x04VOLA\x10\x05\x12\t\n" +
	"\x05OCALL\x10\x06\x12\t\n" +
	"\x05ICALL\x10\a\x12\t\n" +
	"\x05CCALL\x10\b\x12\t\n" +
	"\x05TRADE\x10\t\x12\x14\n" +
	"\x10TRADE_INDICATIVE\x10\n" +
	"\x12\x16\n" +
	"\x12TRADE_BEST_BID_ASK\x10\v\x12\x1f\n" +
	"\x1bTRADE_AUCTION_NO_INDICATIVE\x10\fB-\n" +
	")com.consorsbank.module.tapi.grpc.securityP\x01b\x06proto3"

var (
	file_SecurityService_proto_rawDescOnce sync.Once
	file_SecurityService_proto_rawDescData []byte
)

func file_SecurityService_proto_rawDescGZIP() []byte {
	file_SecurityService_proto_rawDescOnce.Do(func() {
		file_SecurityService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SecurityService_proto_rawDesc), len(file_SecurityService_proto_rawDesc)))
	})
	return file_SecurityService_proto_rawDescData
}

var file_SecurityService_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_SecurityService_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_SecurityService_proto_goTypes = []any{
	(TimeResolution)(0),                               // 0: com.consorsbank.module.tapi.grpc.TimeResolution
	(SecurityCodeType)(0),                             // 1: com.consorsbank.module.tapi.grpc.SecurityCodeType
	(SecurityClass)(0),                                // 2: com.consorsbank.module.tapi.grpc.SecurityClass
	(TradingPhase)(0),                                 // 3: com.consorsbank.module.tapi.grpc.TradingPhase
	(SecurityStockExchangeInfo_ShortMode)(0),          // 4: com.consorsbank.module.tapi.grpc.SecurityStockExchangeInfo.ShortMode
	(SecurityStockExchangeInfo_LimitToken)(0),         // 5: com.consorsbank.module.tapi.grpc.SecurityStockExchangeInfo.LimitToken
	(SecurityMarketDataReply_SecurityChangedField)(0), // 6: com.consorsbank.module.tapi.grpc.SecurityMarketDataReply.SecurityChangedField
	(*SecurityInfoRequest)(nil),                       // 7: com.consorsbank.module.tapi.grpc.SecurityInfoRequest
	(*SecurityInfoReply)(nil),                         // 8: com.consorsbank.module.tapi.grpc.SecurityInfoReply
	(*SecurityPriceHistoryRequest)(nil),               // 9: com.consorsbank.module.tapi.grpc.SecurityPriceHistoryRequest
	(*SecurityPriceHistoryReply)(nil),                 // 10: com.consorsbank.module.tapi.grpc.SecurityPriceHistoryReply
	(*PriceEntry)(nil),                                // 11: com.consorsbank.module.tapi.grpc.PriceEntry
	(*SecurityStockExchangeInfo)(nil),                 // 12: com.consorsbank.module.tapi.grpc.SecurityStockExchangeInfo
	(*SecurityCode)(nil),                              // 13: com.consorsbank.module.tapi.grpc.SecurityCode
	(*SecurityWithStockExchange)(nil),                 // 14: com.consorsbank.module.tapi.grpc.SecurityWithStockExchange
	(*SecurityMarketDataRequest)(nil),                 // 15: com.consorsbank.module.tapi.grpc.SecurityMarketDataRequest
	(*SecurityMarketDataReply)(nil),                   // 16: com.consorsbank.module.tapi.grpc.SecurityMarketDataReply
	(*SecurityOrderBookRequest)(nil),                  // 17: com.consorsbank.module.tapi.grpc.SecurityOrderBookRequest
	(*SecurityOrderBookReply)(nil),                    // 18: com.consorsbank.module.tapi.grpc.SecurityOrderBookReply
	(*CurrencyRateRequest)(nil),                       // 19: com.consorsbank.module.tapi.grpc.CurrencyRateRequest
	(*CurrencyRateReply)(nil),                         // 20: com.consorsbank.module.tapi.grpc.CurrencyRateReply
	(*SecurityOrderBookReply_OrderBookEntry)(nil),     // 21: com.consorsbank.module.tapi.grpc.SecurityOrderBookReply.OrderBookEntry
	(UnitNote)(0),                                     // 22: com.consorsbank.module.tapi.grpc.UnitNote
	(*Error)(nil),                                     // 23: com.consorsbank.module.tapi.grpc.Error
	(*Timestamp)(nil),                                 // 24: com.consorsbank.module.tapi.grpc.Timestamp
	(*StockExchange)(nil),                             // 25: com.consorsbank.module.tapi.grpc.StockExchange
	(*TradingPossibility)(nil),                        // 26: com.consorsbank.module.tapi.grpc.TradingPossibility
	(*Date)(nil),                                      // 27: com.consorsbank.module.tapi.grpc.Date
}
var file_SecurityService_proto_depIdxs = []int32{
	13, // 0: com.consorsbank.module.tapi.grpc.SecurityInfoRequest.security_code:type_name -> com.consorsbank.module.tapi.grpc.SecurityCode
	2,  // 1: com.consorsbank.module.tapi.grpc.SecurityInfoReply.security_class:type_name -> com.consorsbank.module.tapi.grpc.SecurityClass
	13, // 2: com.consorsbank.module.tapi.grpc.SecurityInfoReply.security_codes:type_name -> com.consorsbank.module.tapi.grpc.SecurityCode
	12, // 3: com.consorsbank.module.tapi.grpc.SecurityInfoReply.stock_exchange_infos:type_name -> com.consorsbank.module.tapi.grpc.SecurityStockExchangeInfo
	22, // 4: com.consorsbank.module.tapi.grpc.SecurityInfoReply.unit_note:type_name -> com.consorsbank.module.tapi.grpc.UnitNote
	23, // 5: com.consorsbank.module.tapi.grpc.SecurityInfoReply.error:type_name -> com.consorsbank.module.tapi.grpc.Error
	14, // 6: com.consorsbank.module.tapi.grpc.SecurityPriceHistoryRequest.security_with_stockexchange:type_name -> com.consorsbank.module.tapi.grpc.SecurityWithStockExchange
	0,  // 7: com.consorsbank.module.tapi.grpc.SecurityPriceHistoryRequest.time_resolution:type_name -> com.consorsbank.module.tapi.grpc.TimeResolution
	14, // 8: com.consorsbank.module.tapi.grpc.SecurityPriceHistoryReply.security_with_stockexchange:type_name -> com.consorsbank.module.tapi.grpc.SecurityWithStockExchange
	11, // 9: com.consorsbank.module.tapi.grpc.SecurityPriceHistoryReply.price_entries:type_name -> com.consorsbank.module.tapi.grpc.PriceEntry
	23, // 10: com.consorsbank.module.tapi.grpc.SecurityPriceHistoryReply.error:type_name -> com.consorsbank.module.tapi.grpc.Error
	24, // 11: com.consorsbank.module.tapi.grpc.PriceEntry.open_time:type_name -> com.consorsbank.module.tapi.grpc.Timestamp
	24, // 12: com.consorsbank.module.tapi.grpc.PriceEntry.close_time:type_name -> com.consorsbank.module.tapi.grpc.Timestamp
	25, // 13: com.consorsbank.module.tapi.grpc.SecurityStockExchangeInfo.stock_exchange:type_name -> com.consorsbank.module.tapi.grpc.StockExchange
	5,  // 14: com.consorsbank.module.tapi.grpc.SecurityStockExchangeInfo.buy_limit_token:type_name -> com.consorsbank.module.tapi.grpc.SecurityStockExchangeInfo.LimitToken
	5,  // 15: com.consorsbank.module.tapi.grpc.SecurityStockExchangeInfo.sell_limit_token:type_name -> com.consorsbank.module.tapi.grpc.SecurityStockExchangeInfo.LimitToken
	26, // 16: com.consorsbank.module.tapi.grpc.SecurityStockExchangeInfo.buy_trading_types:type_name -> com.consorsbank.module.tapi.grpc.TradingPossibility
	26, // 17: com.consorsbank.module.tapi.grpc.SecurityStockExchangeInfo.sell_trading_types:type_name -> com.consorsbank.module.tapi.grpc.TradingPossibility
	27, // 18: com.consorsbank.module.tapi.grpc.SecurityStockExchangeInfo.maximal_order_date:type_name -> com.consorsbank.module.tapi.grpc.Date
	4,  // 19: com.consorsbank.module.tapi.grpc.SecurityStockExchangeInfo.short_mode:type_name -> com.consorsbank.module.tapi.grpc.SecurityStockExchangeInfo.ShortMode
	1,  // 20: com.consorsbank.module.tapi.grpc.SecurityCode.code_type:type_name -> com.consorsbank.module.tapi.grpc.SecurityCodeType
	13, // 21: com.consorsbank.module.tapi.grpc.SecurityWithStockExchange.security_code:type_name -> com.consorsbank.module.tapi.grpc.SecurityCode
	25, // 22: com.consorsbank.module.tapi.grpc.SecurityWithStockExchange.stock_exchange:type_name -> com.consorsbank.module.tapi.grpc.StockExchange
	14, // 23: com.consorsbank.module.tapi.grpc.SecurityMarketDataRequest.security_with_stockexchange:type_name -> com.consorsbank.module.tapi.grpc.SecurityWithStockExchange
	14, // 24: com.consorsbank.module.tapi.grpc.SecurityMarketDataReply.security_with_stockexchange:type_name -> com.consorsbank.module.tapi.grpc.SecurityWithStockExchange
	6,  // 25: com.consorsbank.module.tapi.grpc.SecurityMarketDataReply.changed_fields:type_name -> com.consorsbank.module.tapi.grpc.SecurityMarketDataReply.SecurityChangedField
	24, // 26: com.consorsbank.module.tapi.grpc.SecurityMarketDataReply.last_date_time:type_name -> com.consorsbank.module.tapi.grpc.Timestamp
	24, // 27: com.consorsbank.module.tapi.grpc.SecurityMarketDataReply.ask_time:type_name -> com.consorsbank.module.tapi.grpc.Timestamp
	24, // 28: com.consorsbank.module.tapi.grpc.SecurityMarketDataReply.bid_time:type_name -> com.consorsbank.module.tapi.grpc.Timestamp
	27, // 29: com.consorsbank.module.tapi.grpc.SecurityMarketDataReply.previous_date:type_name -> com.consorsbank.module.tapi.grpc.Date
	27, // 30: com.consorsbank.module.tapi.grpc.SecurityMarketDataReply.date_week_high:type_name -> com.consorsbank.module.tapi.grpc.Date
	27, // 31: com.consorsbank.module.tapi.grpc.SecurityMarketDataReply.date_week_low:type_name -> com.consorsbank.module.tapi.grpc.Date
	27, // 32: com.consorsbank.module.tapi.grpc.SecurityMarketDataReply.date_month_high:type_name -> com.consorsbank.module.tapi.grpc.Date
	27, // 33: com.consorsbank.module.tapi.grpc.SecurityMarketDataReply.date_month_low:type_name -> com.consorsbank.module.tapi.grpc.Date
	27, // 34: com.consorsbank.module.tapi.grpc.SecurityMarketDataReply.date_year_high:type_name -> com.consorsbank.module.tapi.grpc.Date
	27, // 35: com.consorsbank.module.tapi.grpc.SecurityMarketDataReply.date_year_low:type_name -> com.consorsbank.module.tapi.grpc.Date
	3,  // 36: com.consorsbank.module.tapi.grpc.SecurityMarketDataReply.trading_phase:type_name -> com.consorsbank.module.tapi.grpc.TradingPhase
	23, // 37: com.consorsbank.module.tapi.grpc.SecurityMarketDataReply.error:type_name -> com.consorsbank.module.tapi.grpc.Error
	14, // 38: com.consorsbank.module.tapi.grpc.SecurityOrderBookRequest.security_with_stockexchange:type_name -> com.consorsbank.module.tapi.grpc.SecurityWithStockExchange
	14, // 39: com.consorsbank.module.tapi.grpc.SecurityOrderBookReply.security_with_stockexchange:type_name -> com.consorsbank.module.tapi.grpc.SecurityWithStockExchange
	21, // 40: com.consorsbank.module.tapi.grpc.SecurityOrderBookReply.order_book_entries:type_name -> com.consorsbank.module.tapi.grpc.SecurityOrderBookReply.OrderBookEntry
	23, // 41: com.consorsbank.module.tapi.grpc.SecurityOrderBookReply.error:type_name -> com.consorsbank.module.tapi.grpc.Error
	23, // 42: com.consorsbank.module.tapi.grpc.CurrencyRateReply.error:type_name -> com.consorsbank.module.tapi.grpc.Error
	43, // [43:43] is the sub-list for method output_type
	43, // [43:43] is the sub-list for method input_type
	43, // [43:43] is the sub-list for extension type_name
	43, // [43:43] is the sub-list for extension extendee
	0,  // [0:43] is the sub-list for field type_name
}

func init() { file_SecurityService_proto_init() }
func file_SecurityService_proto_init() {
	if File_SecurityService_proto != nil {
		return
	}
	file_Common_proto_init()
	file_StockExchangeService_proto_init()
	file_TradingTypes_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SecurityService_proto_rawDesc), len(file_SecurityService_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SecurityService_proto_goTypes,
		DependencyIndexes: file_SecurityService_proto_depIdxs,
		EnumInfos:         file_SecurityService_proto_enumTypes,
		MessageInfos:      file_SecurityService_proto_msgTypes,
	}.Build()
	File_SecurityService_proto = out.File
	file_SecurityService_proto_goTypes = nil
	file_SecurityService_proto_depIdxs = nil
}
