//
// Copyright 2018, Trading-API, Consorsbank.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: StockExchangeService.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Stock exchange data
type StockExchange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Stock exchange id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// * Stock exchange issuer. Can be null
	Issuer        string `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockExchange) Reset() {
	*x = StockExchange{}
	mi := &file_StockExchangeService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockExchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockExchange) ProtoMessage() {}

func (x *StockExchange) ProtoReflect() protoreflect.Message {
	mi := &file_StockExchangeService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockExchange.ProtoReflect.Descriptor instead.
func (*StockExchange) Descriptor() ([]byte, []int) {
	return file_StockExchangeService_proto_rawDescGZIP(), []int{0}
}

func (x *StockExchange) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StockExchange) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

// *
// Stock exchange request contains data that need to request stock exchange
// related data
type StockExchangeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Access token
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// *
	// Stock exchange
	StockExchange *StockExchange `protobuf:"bytes,2,opt,name=stock_exchange,json=stockExchange,proto3" json:"stock_exchange,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockExchangeRequest) Reset() {
	*x = StockExchangeRequest{}
	mi := &file_StockExchangeService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockExchangeRequest) ProtoMessage() {}

func (x *StockExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_StockExchangeService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockExchangeRequest.ProtoReflect.Descriptor instead.
func (*StockExchangeRequest) Descriptor() ([]byte, []int) {
	return file_StockExchangeService_proto_rawDescGZIP(), []int{1}
}

func (x *StockExchangeRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *StockExchangeRequest) GetStockExchange() *StockExchange {
	if x != nil {
		return x.StockExchange
	}
	return nil
}

type StockExchangeInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Stock exchange object
	StockExchange *StockExchange `protobuf:"bytes,1,opt,name=stockExchange,proto3" json:"stockExchange,omitempty"`
	// * Stock exchange name
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockExchangeInfo) Reset() {
	*x = StockExchangeInfo{}
	mi := &file_StockExchangeService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockExchangeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockExchangeInfo) ProtoMessage() {}

func (x *StockExchangeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_StockExchangeService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockExchangeInfo.ProtoReflect.Descriptor instead.
func (*StockExchangeInfo) Descriptor() ([]byte, []int) {
	return file_StockExchangeService_proto_rawDescGZIP(), []int{2}
}

func (x *StockExchangeInfo) GetStockExchange() *StockExchange {
	if x != nil {
		return x.StockExchange
	}
	return nil
}

func (x *StockExchangeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StockExchangeDescriptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * List with stock exchange information
	StockExchangeInfos []*StockExchangeInfo `protobuf:"bytes,1,rep,name=stock_exchange_infos,json=stockExchangeInfos,proto3" json:"stock_exchange_infos,omitempty"`
	// * Error
	Error         *Error `protobuf:"bytes,1000,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockExchangeDescriptions) Reset() {
	*x = StockExchangeDescriptions{}
	mi := &file_StockExchangeService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockExchangeDescriptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockExchangeDescriptions) ProtoMessage() {}

func (x *StockExchangeDescriptions) ProtoReflect() protoreflect.Message {
	mi := &file_StockExchangeService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockExchangeDescriptions.ProtoReflect.Descriptor instead.
func (*StockExchangeDescriptions) Descriptor() ([]byte, []int) {
	return file_StockExchangeService_proto_rawDescGZIP(), []int{3}
}

func (x *StockExchangeDescriptions) GetStockExchangeInfos() []*StockExchangeInfo {
	if x != nil {
		return x.StockExchangeInfos
	}
	return nil
}

func (x *StockExchangeDescriptions) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type StockExchangeDescription struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Stock exchange information
	StockExchangeInfo *StockExchangeInfo `protobuf:"bytes,1,opt,name=stock_exchange_info,json=stockExchangeInfo,proto3" json:"stock_exchange_info,omitempty"`
	// *
	// Error information if occuirs
	Error         *Error `protobuf:"bytes,1000,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockExchangeDescription) Reset() {
	*x = StockExchangeDescription{}
	mi := &file_StockExchangeService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockExchangeDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockExchangeDescription) ProtoMessage() {}

func (x *StockExchangeDescription) ProtoReflect() protoreflect.Message {
	mi := &file_StockExchangeService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockExchangeDescription.ProtoReflect.Descriptor instead.
func (*StockExchangeDescription) Descriptor() ([]byte, []int) {
	return file_StockExchangeService_proto_rawDescGZIP(), []int{4}
}

func (x *StockExchangeDescription) GetStockExchangeInfo() *StockExchangeInfo {
	if x != nil {
		return x.StockExchangeInfo
	}
	return nil
}

func (x *StockExchangeDescription) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_StockExchangeService_proto protoreflect.FileDescriptor

const file_StockExchangeService_proto_rawDesc = "" +
	"\n" +
	"\x1aStockExchangeService.proto\x12 com.consorsbank.module.tapi.grpc\x1a\fCommon.proto\"7\n" +
	"\rStockExchange\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\"\x91\x01\n" +
	"\x14StockExchangeRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12V\n" +
	"\x0estock_exchange\x18\x02 \x01(\v2/.com.consorsbank.module.tapi.grpc.StockExchangeR\rstockExchange\"~\n" +
	"\x11StockExchangeInfo\x12U\n" +
	"\rstockExchange\x18\x01 \x01(\v2/.com.consorsbank.module.tapi.grpc.StockExchangeR\rstockExchange\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xc2\x01\n" +
	"\x19StockExchangeDescriptions\x12e\n" +
	"\x14stock_exchange_infos\x18\x01 \x03(\v23.com.consorsbank.module.tapi.grpc.StockExchangeInfoR\x12stockExchangeInfos\x12>\n" +
	"\x05error\x18\xe8\a \x01(\v2'.com.consorsbank.module.tapi.grpc.ErrorR\x05error\"\xbf\x01\n" +
	"\x18StockExchangeDescription\x12c\n" +
	"\x13stock_exchange_info\x18\x01 \x01(\v23.com.consorsbank.module.tapi.grpc.StockExchangeInfoR\x11stockExchangeInfo\x12>\n" +
	"\x05error\x18\xe8\a \x01(\v2'.com.consorsbank.module.tapi.grpc.ErrorR\x05errorB*\n" +
	"&com.consorsbank.module.tapi.grpc.stockP\x01b\x06proto3"

var (
	file_StockExchangeService_proto_rawDescOnce sync.Once
	file_StockExchangeService_proto_rawDescData []byte
)

func file_StockExchangeService_proto_rawDescGZIP() []byte {
	file_StockExchangeService_proto_rawDescOnce.Do(func() {
		file_StockExchangeService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_StockExchangeService_proto_rawDesc), len(file_StockExchangeService_proto_rawDesc)))
	})
	return file_StockExchangeService_proto_rawDescData
}

var file_StockExchangeService_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_StockExchangeService_proto_goTypes = []any{
	(*StockExchange)(nil),             // 0: com.consorsbank.module.tapi.grpc.StockExchange
	(*StockExchangeRequest)(nil),      // 1: com.consorsbank.module.tapi.grpc.StockExchangeRequest
	(*StockExchangeInfo)(nil),         // 2: com.consorsbank.module.tapi.grpc.StockExchangeInfo
	(*StockExchangeDescriptions)(nil), // 3: com.consorsbank.module.tapi.grpc.StockExchangeDescriptions
	(*StockExchangeDescription)(nil),  // 4: com.consorsbank.module.tapi.grpc.StockExchangeDescription
	(*Error)(nil),                     // 5: com.consorsbank.module.tapi.grpc.Error
}
var file_StockExchangeService_proto_depIdxs = []int32{
	0, // 0: com.consorsbank.module.tapi.grpc.StockExchangeRequest.stock_exchange:type_name -> com.consorsbank.module.tapi.grpc.StockExchange
	0, // 1: com.consorsbank.module.tapi.grpc.StockExchangeInfo.stockExchange:type_name -> com.consorsbank.module.tapi.grpc.StockExchange
	2, // 2: com.consorsbank.module.tapi.grpc.StockExchangeDescriptions.stock_exchange_infos:type_name -> com.consorsbank.module.tapi.grpc.StockExchangeInfo
	5, // 3: com.consorsbank.module.tapi.grpc.StockExchangeDescriptions.error:type_name -> com.consorsbank.module.tapi.grpc.Error
	2, // 4: com.consorsbank.module.tapi.grpc.StockExchangeDescription.stock_exchange_info:type_name -> com.consorsbank.module.tapi.grpc.StockExchangeInfo
	5, // 5: com.consorsbank.module.tapi.grpc.StockExchangeDescription.error:type_name -> com.consorsbank.module.tapi.grpc.Error
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_StockExchangeService_proto_init() }
func file_StockExchangeService_proto_init() {
	if File_StockExchangeService_proto != nil {
		return
	}
	file_Common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_StockExchangeService_proto_rawDesc), len(file_StockExchangeService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_StockExchangeService_proto_goTypes,
		DependencyIndexes: file_StockExchangeService_proto_depIdxs,
		MessageInfos:      file_StockExchangeService_proto_msgTypes,
	}.Build()
	File_StockExchangeService_proto = out.File
	file_StockExchangeService_proto_goTypes = nil
	file_StockExchangeService_proto_depIdxs = nil
}
