//
// Copyright 2018, Trading-API, Consorsbank.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: TradingTypes.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Order model represents possible orders
type OrderModel int32

const (
	// *
	// Order model absent
	OrderModel_NO_ORDER_MODEL OrderModel = 0
	// *
	// Market order
	OrderModel_MARKET OrderModel = 1
	// *
	// Limit order
	OrderModel_LIMIT OrderModel = 2
	// *
	// Stop market order.
	OrderModel_STOP_MARKET OrderModel = 3
	// *
	// Stop limit order
	OrderModel_STOP_LIMIT OrderModel = 4
	// *
	// One cancels other market order
	OrderModel_ONE_CANCELS_OTHER_MARKET OrderModel = 5
	// *
	// One cancels other limit order
	OrderModel_ONE_CANCELS_OTHER_LIMIT OrderModel = 6
	// *
	// Trailing stop market order
	OrderModel_TRAILING_STOP_MARKET OrderModel = 7
	// *
	// Trailing stop limit order
	OrderModel_TRAILING_STOP_LIMIT OrderModel = 8
)

// Enum value maps for OrderModel.
var (
	OrderModel_name = map[int32]string{
		0: "NO_ORDER_MODEL",
		1: "MARKET",
		2: "LIMIT",
		3: "STOP_MARKET",
		4: "STOP_LIMIT",
		5: "ONE_CANCELS_OTHER_MARKET",
		6: "ONE_CANCELS_OTHER_LIMIT",
		7: "TRAILING_STOP_MARKET",
		8: "TRAILING_STOP_LIMIT",
	}
	OrderModel_value = map[string]int32{
		"NO_ORDER_MODEL":           0,
		"MARKET":                   1,
		"LIMIT":                    2,
		"STOP_MARKET":              3,
		"STOP_LIMIT":               4,
		"ONE_CANCELS_OTHER_MARKET": 5,
		"ONE_CANCELS_OTHER_LIMIT":  6,
		"TRAILING_STOP_MARKET":     7,
		"TRAILING_STOP_LIMIT":      8,
	}
)

func (x OrderModel) Enum() *OrderModel {
	p := new(OrderModel)
	*p = x
	return p
}

func (x OrderModel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderModel) Descriptor() protoreflect.EnumDescriptor {
	return file_TradingTypes_proto_enumTypes[0].Descriptor()
}

func (OrderModel) Type() protoreflect.EnumType {
	return &file_TradingTypes_proto_enumTypes[0]
}

func (x OrderModel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderModel.Descriptor instead.
func (OrderModel) EnumDescriptor() ([]byte, []int) {
	return file_TradingTypes_proto_rawDescGZIP(), []int{0}
}

// *
// Order type represents different buy / sell order possibilities
type OrderType int32

const (
	// *
	// Order type is not defined
	OrderType_NO_ORDER_TYPE OrderType = 0
	// *
	// Buy order type
	OrderType_BUY OrderType = 1
	// *
	// Sell order type
	OrderType_SELL OrderType = 2
	// *
	// Short sell order type
	OrderType_SHORT_SELL OrderType = 3
	// *
	// Short cover order type. This type is not allowed as input parameter
	OrderType_SHORT_COVER OrderType = 4
	// *
	// Rorced cover order type. This type is not allowed as input parameter
	OrderType_FORCED_COVER OrderType = 5
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "NO_ORDER_TYPE",
		1: "BUY",
		2: "SELL",
		3: "SHORT_SELL",
		4: "SHORT_COVER",
		5: "FORCED_COVER",
	}
	OrderType_value = map[string]int32{
		"NO_ORDER_TYPE": 0,
		"BUY":           1,
		"SELL":          2,
		"SHORT_SELL":    3,
		"SHORT_COVER":   4,
		"FORCED_COVER":  5,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_TradingTypes_proto_enumTypes[1].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_TradingTypes_proto_enumTypes[1]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_TradingTypes_proto_rawDescGZIP(), []int{1}
}

// *
// Order supplement is additional parameter by order definition
type OrderSupplement int32

const (
	// *
	// Normal order supplement
	OrderSupplement_NORMAL OrderSupplement = 0
	// *
	// Immidiate or cancel order supplement
	OrderSupplement_IMMIDIATE_OR_CANCEL OrderSupplement = 1
	// *
	// Fill or kill order supplement
	OrderSupplement_FILL_OR_KILL OrderSupplement = 2
	// *
	// Icesberg order supplement. Allowes to delivery amount in portions. #pro# only
	OrderSupplement_ICEBERG OrderSupplement = 3
	// *
	// Market place order supplement
	OrderSupplement_MARKET_PRICE OrderSupplement = 4
)

// Enum value maps for OrderSupplement.
var (
	OrderSupplement_name = map[int32]string{
		0: "NORMAL",
		1: "IMMIDIATE_OR_CANCEL",
		2: "FILL_OR_KILL",
		3: "ICEBERG",
		4: "MARKET_PRICE",
	}
	OrderSupplement_value = map[string]int32{
		"NORMAL":              0,
		"IMMIDIATE_OR_CANCEL": 1,
		"FILL_OR_KILL":        2,
		"ICEBERG":             3,
		"MARKET_PRICE":        4,
	}
)

func (x OrderSupplement) Enum() *OrderSupplement {
	p := new(OrderSupplement)
	*p = x
	return p
}

func (x OrderSupplement) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderSupplement) Descriptor() protoreflect.EnumDescriptor {
	return file_TradingTypes_proto_enumTypes[2].Descriptor()
}

func (OrderSupplement) Type() protoreflect.EnumType {
	return &file_TradingTypes_proto_enumTypes[2]
}

func (x OrderSupplement) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderSupplement.Descriptor instead.
func (OrderSupplement) EnumDescriptor() ([]byte, []int) {
	return file_TradingTypes_proto_rawDescGZIP(), []int{2}
}

// *
// Trailing notation represent notation type by trailing orders
type TrailingNotation int32

const (
	// *
	// Trailing notation is not defined
	TrailingNotation_NO_TRAILING_NOTATION TrailingNotation = 0
	// *
	// Absolute order notation
	TrailingNotation_ABSOLUTE TrailingNotation = 1
	// *
	// Relative order notation
	TrailingNotation_RELATIVE TrailingNotation = 2
)

// Enum value maps for TrailingNotation.
var (
	TrailingNotation_name = map[int32]string{
		0: "NO_TRAILING_NOTATION",
		1: "ABSOLUTE",
		2: "RELATIVE",
	}
	TrailingNotation_value = map[string]int32{
		"NO_TRAILING_NOTATION": 0,
		"ABSOLUTE":             1,
		"RELATIVE":             2,
	}
)

func (x TrailingNotation) Enum() *TrailingNotation {
	p := new(TrailingNotation)
	*p = x
	return p
}

func (x TrailingNotation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrailingNotation) Descriptor() protoreflect.EnumDescriptor {
	return file_TradingTypes_proto_enumTypes[3].Descriptor()
}

func (TrailingNotation) Type() protoreflect.EnumType {
	return &file_TradingTypes_proto_enumTypes[3]
}

func (x TrailingNotation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrailingNotation.Descriptor instead.
func (TrailingNotation) EnumDescriptor() ([]byte, []int) {
	return file_TradingTypes_proto_rawDescGZIP(), []int{3}
}

// *
// Cash quotation is additional parameter of the order
type CashQuotation int32

const (
	// *
	// Quotation is not defined
	CashQuotation_NOTHING CashQuotation = 0
	// *
	// Kassa quotation
	CashQuotation_KASSA CashQuotation = 1
	// *
	// Auction quotation
	CashQuotation_AUCTION CashQuotation = 2
	// *
	// Opening quotation
	CashQuotation_OPENING CashQuotation = 3
	// *
	// Intraday quotation
	CashQuotation_INTRADAY CashQuotation = 4
	// *
	// Close quotation
	CashQuotation_CLOSING CashQuotation = 5
)

// Enum value maps for CashQuotation.
var (
	CashQuotation_name = map[int32]string{
		0: "NOTHING",
		1: "KASSA",
		2: "AUCTION",
		3: "OPENING",
		4: "INTRADAY",
		5: "CLOSING",
	}
	CashQuotation_value = map[string]int32{
		"NOTHING":  0,
		"KASSA":    1,
		"AUCTION":  2,
		"OPENING":  3,
		"INTRADAY": 4,
		"CLOSING":  5,
	}
)

func (x CashQuotation) Enum() *CashQuotation {
	p := new(CashQuotation)
	*p = x
	return p
}

func (x CashQuotation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CashQuotation) Descriptor() protoreflect.EnumDescriptor {
	return file_TradingTypes_proto_enumTypes[4].Descriptor()
}

func (CashQuotation) Type() protoreflect.EnumType {
	return &file_TradingTypes_proto_enumTypes[4]
}

func (x CashQuotation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CashQuotation.Descriptor instead.
func (CashQuotation) EnumDescriptor() ([]byte, []int) {
	return file_TradingTypes_proto_rawDescGZIP(), []int{4}
}

// *
// Trading possibility represents allowed variants to trade on specific stock exchange.
// Each trading possibility is a combination of the parameters. The list of the order possibilites
// is all possible combinations:
//
//	MARKET;NORMAL;ABSOLUTE;{KASSA;AUCTION}
//	LIMIT;NORMAL;ABSOLUTE;{KASSA;AUCTION}
//	MARKET;NORMAL;RELATIVE;{KASSA;AUCTION}
//	LIMIT;NORMAL;RELATIVE;{KASSA;AUCTION}
//	...
type TradingPossibility struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Order model
	OrderModel OrderModel `protobuf:"varint,1,opt,name=order_model,json=orderModel,proto3,enum=com.consorsbank.module.tapi.grpc.OrderModel" json:"order_model,omitempty"`
	// *
	// Order supplement
	OrderSupplement OrderSupplement `protobuf:"varint,2,opt,name=order_supplement,json=orderSupplement,proto3,enum=com.consorsbank.module.tapi.grpc.OrderSupplement" json:"order_supplement,omitempty"`
	// *
	// Trailing notation
	TrailingNotation TrailingNotation `protobuf:"varint,3,opt,name=trailing_notation,json=trailingNotation,proto3,enum=com.consorsbank.module.tapi.grpc.TrailingNotation" json:"trailing_notation,omitempty"`
	// *
	// List of allowed cash_quatations
	CashQuotations []CashQuotation `protobuf:"varint,4,rep,packed,name=cash_quotations,json=cashQuotations,proto3,enum=com.consorsbank.module.tapi.grpc.CashQuotation" json:"cash_quotations,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TradingPossibility) Reset() {
	*x = TradingPossibility{}
	mi := &file_TradingTypes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradingPossibility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradingPossibility) ProtoMessage() {}

func (x *TradingPossibility) ProtoReflect() protoreflect.Message {
	mi := &file_TradingTypes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradingPossibility.ProtoReflect.Descriptor instead.
func (*TradingPossibility) Descriptor() ([]byte, []int) {
	return file_TradingTypes_proto_rawDescGZIP(), []int{0}
}

func (x *TradingPossibility) GetOrderModel() OrderModel {
	if x != nil {
		return x.OrderModel
	}
	return OrderModel_NO_ORDER_MODEL
}

func (x *TradingPossibility) GetOrderSupplement() OrderSupplement {
	if x != nil {
		return x.OrderSupplement
	}
	return OrderSupplement_NORMAL
}

func (x *TradingPossibility) GetTrailingNotation() TrailingNotation {
	if x != nil {
		return x.TrailingNotation
	}
	return TrailingNotation_NO_TRAILING_NOTATION
}

func (x *TradingPossibility) GetCashQuotations() []CashQuotation {
	if x != nil {
		return x.CashQuotations
	}
	return nil
}

var File_TradingTypes_proto protoreflect.FileDescriptor

const file_TradingTypes_proto_rawDesc = "" +
	"\n" +
	"\x12TradingTypes.proto\x12 com.consorsbank.module.tapi.grpc\"\xfc\x02\n" +
	"\x12TradingPossibility\x12M\n" +
	"\vorder_model\x18\x01 \x01(\x0e2,.com.consorsbank.module.tapi.grpc.OrderModelR\n" +
	"orderModel\x12\\\n" +
	"\x10order_supplement\x18\x02 \x01(\x0e21.com.consorsbank.module.tapi.grpc.OrderSupplementR\x0forderSupplement\x12_\n" +
	"\x11trailing_notation\x18\x03 \x01(\x0e22.com.consorsbank.module.tapi.grpc.TrailingNotationR\x10trailingNotation\x12X\n" +
	"\x0fcash_quotations\x18\x04 \x03(\x0e2/.com.consorsbank.module.tapi.grpc.CashQuotationR\x0ecashQuotations*\xc6\x01\n" +
	"\n" +
	"OrderModel\x12\x12\n" +
	"\x0eNO_ORDER_MODEL\x10\x00\x12\n" +
	"\n" +
	"\x06MARKET\x10\x01\x12\t\n" +
	"\x05LIMIT\x10\x02\x12\x0f\n" +
	"\vSTOP_MARKET\x10\x03\x12\x0e\n" +
	"\n" +
	"STOP_LIMIT\x10\x04\x12\x1c\n" +
	"\x18ONE_CANCELS_OTHER_MARKET\x10\x05\x12\x1b\n" +
	"\x17ONE_CANCELS_OTHER_LIMIT\x10\x06\x12\x18\n" +
	"\x14TRAILING_STOP_MARKET\x10\a\x12\x17\n" +
	"\x13TRAILING_STOP_LIMIT\x10\b*d\n" +
	"\tOrderType\x12\x11\n" +
	"\rNO_ORDER_TYPE\x10\x00\x12\a\n" +
	"\x03BUY\x10\x01\x12\b\n" +
	"\x04SELL\x10\x02\x12\x0e\n" +
	"\n" +
	"SHORT_SELL\x10\x03\x12\x0f\n" +
	"\vSHORT_COVER\x10\x04\x12\x10\n" +
	"\fFORCED_COVER\x10\x05*g\n" +
	"\x0fOrderSupplement\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x00\x12\x17\n" +
	"\x13IMMIDIATE_OR_CANCEL\x10\x01\x12\x10\n" +
	"\fFILL_OR_KILL\x10\x02\x12\v\n" +
	"\aICEBERG\x10\x03\x12\x10\n" +
	"\fMARKET_PRICE\x10\x04*H\n" +
	"\x10TrailingNotation\x12\x18\n" +
	"\x14NO_TRAILING_NOTATION\x10\x00\x12\f\n" +
	"\bABSOLUTE\x10\x01\x12\f\n" +
	"\bRELATIVE\x10\x02*\\\n" +
	"\rCashQuotation\x12\v\n" +
	"\aNOTHING\x10\x00\x12\t\n" +
	"\x05KASSA\x10\x01\x12\v\n" +
	"\aAUCTION\x10\x02\x12\v\n" +
	"\aOPENING\x10\x03\x12\f\n" +
	"\bINTRADAY\x10\x04\x12\v\n" +
	"\aCLOSING\x10\x05B,\n" +
	"(com.consorsbank.module.tapi.grpc.tradingP\x01b\x06proto3"

var (
	file_TradingTypes_proto_rawDescOnce sync.Once
	file_TradingTypes_proto_rawDescData []byte
)

func file_TradingTypes_proto_rawDescGZIP() []byte {
	file_TradingTypes_proto_rawDescOnce.Do(func() {
		file_TradingTypes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TradingTypes_proto_rawDesc), len(file_TradingTypes_proto_rawDesc)))
	})
	return file_TradingTypes_proto_rawDescData
}

var file_TradingTypes_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_TradingTypes_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_TradingTypes_proto_goTypes = []any{
	(OrderModel)(0),            // 0: com.consorsbank.module.tapi.grpc.OrderModel
	(OrderType)(0),             // 1: com.consorsbank.module.tapi.grpc.OrderType
	(OrderSupplement)(0),       // 2: com.consorsbank.module.tapi.grpc.OrderSupplement
	(TrailingNotation)(0),      // 3: com.consorsbank.module.tapi.grpc.TrailingNotation
	(CashQuotation)(0),         // 4: com.consorsbank.module.tapi.grpc.CashQuotation
	(*TradingPossibility)(nil), // 5: com.consorsbank.module.tapi.grpc.TradingPossibility
}
var file_TradingTypes_proto_depIdxs = []int32{
	0, // 0: com.consorsbank.module.tapi.grpc.TradingPossibility.order_model:type_name -> com.consorsbank.module.tapi.grpc.OrderModel
	2, // 1: com.consorsbank.module.tapi.grpc.TradingPossibility.order_supplement:type_name -> com.consorsbank.module.tapi.grpc.OrderSupplement
	3, // 2: com.consorsbank.module.tapi.grpc.TradingPossibility.trailing_notation:type_name -> com.consorsbank.module.tapi.grpc.TrailingNotation
	4, // 3: com.consorsbank.module.tapi.grpc.TradingPossibility.cash_quotations:type_name -> com.consorsbank.module.tapi.grpc.CashQuotation
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_TradingTypes_proto_init() }
func file_TradingTypes_proto_init() {
	if File_TradingTypes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TradingTypes_proto_rawDesc), len(file_TradingTypes_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TradingTypes_proto_goTypes,
		DependencyIndexes: file_TradingTypes_proto_depIdxs,
		EnumInfos:         file_TradingTypes_proto_enumTypes,
		MessageInfos:      file_TradingTypes_proto_msgTypes,
	}.Build()
	File_TradingTypes_proto = out.File
	file_TradingTypes_proto_goTypes = nil
	file_TradingTypes_proto_depIdxs = nil
}
