//
// Copyright 2018, Trading-API, Consorsbank.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: TradingAPI.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_TradingAPI_proto protoreflect.FileDescriptor

const file_TradingAPI_proto_rawDesc = "" +
	"\n" +
	"\x10TradingAPI.proto\x12 com.consorsbank.module.tapi.grpc\x1a\fCommon.proto\x1a\x1aStockExchangeService.proto\x1a\x15SecurityService.proto\x1a\x14AccountService.proto\x1a\x12OrderService.proto\x1a\x12DepotService.proto\x1a\x13AccessService.proto2\xe0\x01\n" +
	"\rAccessService\x12e\n" +
	"\x05Login\x12..com.consorsbank.module.tapi.grpc.LoginRequest\x1a,.com.consorsbank.module.tapi.grpc.LoginReply\x12h\n" +
	"\x06Logout\x12/.com.consorsbank.module.tapi.grpc.LogoutRequest\x1a-.com.consorsbank.module.tapi.grpc.LogoutReply2\xc8\x05\n" +
	"\x0fSecurityService\x12}\n" +
	"\x0fGetSecurityInfo\x125.com.consorsbank.module.tapi.grpc.SecurityInfoRequest\x1a3.com.consorsbank.module.tapi.grpc.SecurityInfoReply\x12\x8c\x01\n" +
	"\x10StreamMarketData\x12;.com.consorsbank.module.tapi.grpc.SecurityMarketDataRequest\x1a9.com.consorsbank.module.tapi.grpc.SecurityMarketDataReply0\x01\x12\x89\x01\n" +
	"\x0fStreamOrderBook\x12:.com.consorsbank.module.tapi.grpc.SecurityOrderBookRequest\x1a8.com.consorsbank.module.tapi.grpc.SecurityOrderBookReply0\x01\x12\x82\x01\n" +
	"\x12StreamCurrencyRate\x125.com.consorsbank.module.tapi.grpc.CurrencyRateRequest\x1a3.com.consorsbank.module.tapi.grpc.CurrencyRateReply0\x01\x12\x95\x01\n" +
	"\x17GetSecurityPriceHistory\x12=.com.consorsbank.module.tapi.grpc.SecurityPriceHistoryRequest\x1a;.com.consorsbank.module.tapi.grpc.SecurityPriceHistoryReply2\xa8\x02\n" +
	"\x14StockExchangeService\x12\x86\x01\n" +
	"\x11GetStockExchanges\x124.com.consorsbank.module.tapi.grpc.AccessTokenRequest\x1a;.com.consorsbank.module.tapi.grpc.StockExchangeDescriptions\x12\x86\x01\n" +
	"\x10GetStockExchange\x126.com.consorsbank.module.tapi.grpc.StockExchangeRequest\x1a:.com.consorsbank.module.tapi.grpc.StockExchangeDescription2\x97\b\n" +
	"\fOrderService\x12s\n" +
	"\fStreamOrders\x127.com.consorsbank.module.tapi.grpc.TradingAccountRequest\x1a(.com.consorsbank.module.tapi.grpc.Orders0\x01\x12p\n" +
	"\fUpdateOrders\x127.com.consorsbank.module.tapi.grpc.TradingAccountRequest\x1a'.com.consorsbank.module.tapi.grpc.Empty\x12h\n" +
	"\bGetQuote\x12..com.consorsbank.module.tapi.grpc.QuoteRequest\x1a,.com.consorsbank.module.tapi.grpc.QuoteReply\x12q\n" +
	"\vAcceptQuote\x124.com.consorsbank.module.tapi.grpc.AcceptQuoteRequest\x1a,.com.consorsbank.module.tapi.grpc.OrderReply\x12k\n" +
	"\bAddOrder\x121.com.consorsbank.module.tapi.grpc.AddOrderRequest\x1a,.com.consorsbank.module.tapi.grpc.OrderReply\x12q\n" +
	"\vChangeOrder\x124.com.consorsbank.module.tapi.grpc.ChangeOrderRequest\x1a,.com.consorsbank.module.tapi.grpc.OrderReply\x12q\n" +
	"\vCancelOrder\x124.com.consorsbank.module.tapi.grpc.CancelOrderRequest\x1a,.com.consorsbank.module.tapi.grpc.OrderReply\x12u\n" +
	"\rActivateOrder\x126.com.consorsbank.module.tapi.grpc.ActivateOrderRequest\x1a,.com.consorsbank.module.tapi.grpc.OrderReply\x12y\n" +
	"\x0fDeactivateOrder\x128.com.consorsbank.module.tapi.grpc.DeactivateOrderRequest\x1a,.com.consorsbank.module.tapi.grpc.OrderReply2\xbe\x03\n" +
	"\x0eAccountService\x12}\n" +
	"\x12GetTradingAccounts\x124.com.consorsbank.module.tapi.grpc.AccessTokenRequest\x1a1.com.consorsbank.module.tapi.grpc.TradingAccounts\x12\x8e\x01\n" +
	"\x14StreamTradingAccount\x127.com.consorsbank.module.tapi.grpc.TradingAccountRequest\x1a;.com.consorsbank.module.tapi.grpc.TradingAccountInformation0\x01\x12\x9b\x01\n" +
	" StreamTradingAccountTransactions\x127.com.consorsbank.module.tapi.grpc.TradingAccountRequest\x1a<.com.consorsbank.module.tapi.grpc.TradingAccountTransactions0\x012\xf9\x01\n" +
	"\fDepotService\x12x\n" +
	"\vStreamDepot\x127.com.consorsbank.module.tapi.grpc.TradingAccountRequest\x1a..com.consorsbank.module.tapi.grpc.DepotEntries0\x01\x12o\n" +
	"\vUpdateDepot\x127.com.consorsbank.module.tapi.grpc.TradingAccountRequest\x1a'.com.consorsbank.module.tapi.grpc.EmptyB$\n" +
	" com.consorsbank.module.tapi.grpcP\x01b\x06proto3"

var file_TradingAPI_proto_goTypes = []any{
	(*LoginRequest)(nil),                // 0: com.consorsbank.module.tapi.grpc.LoginRequest
	(*LogoutRequest)(nil),               // 1: com.consorsbank.module.tapi.grpc.LogoutRequest
	(*SecurityInfoRequest)(nil),         // 2: com.consorsbank.module.tapi.grpc.SecurityInfoRequest
	(*SecurityMarketDataRequest)(nil),   // 3: com.consorsbank.module.tapi.grpc.SecurityMarketDataRequest
	(*SecurityOrderBookRequest)(nil),    // 4: com.consorsbank.module.tapi.grpc.SecurityOrderBookRequest
	(*CurrencyRateRequest)(nil),         // 5: com.consorsbank.module.tapi.grpc.CurrencyRateRequest
	(*SecurityPriceHistoryRequest)(nil), // 6: com.consorsbank.module.tapi.grpc.SecurityPriceHistoryRequest
	(*AccessTokenRequest)(nil),          // 7: com.consorsbank.module.tapi.grpc.AccessTokenRequest
	(*StockExchangeRequest)(nil),        // 8: com.consorsbank.module.tapi.grpc.StockExchangeRequest
	(*TradingAccountRequest)(nil),       // 9: com.consorsbank.module.tapi.grpc.TradingAccountRequest
	(*QuoteRequest)(nil),                // 10: com.consorsbank.module.tapi.grpc.QuoteRequest
	(*AcceptQuoteRequest)(nil),          // 11: com.consorsbank.module.tapi.grpc.AcceptQuoteRequest
	(*AddOrderRequest)(nil),             // 12: com.consorsbank.module.tapi.grpc.AddOrderRequest
	(*ChangeOrderRequest)(nil),          // 13: com.consorsbank.module.tapi.grpc.ChangeOrderRequest
	(*CancelOrderRequest)(nil),          // 14: com.consorsbank.module.tapi.grpc.CancelOrderRequest
	(*ActivateOrderRequest)(nil),        // 15: com.consorsbank.module.tapi.grpc.ActivateOrderRequest
	(*DeactivateOrderRequest)(nil),      // 16: com.consorsbank.module.tapi.grpc.DeactivateOrderRequest
	(*LoginReply)(nil),                  // 17: com.consorsbank.module.tapi.grpc.LoginReply
	(*LogoutReply)(nil),                 // 18: com.consorsbank.module.tapi.grpc.LogoutReply
	(*SecurityInfoReply)(nil),           // 19: com.consorsbank.module.tapi.grpc.SecurityInfoReply
	(*SecurityMarketDataReply)(nil),     // 20: com.consorsbank.module.tapi.grpc.SecurityMarketDataReply
	(*SecurityOrderBookReply)(nil),      // 21: com.consorsbank.module.tapi.grpc.SecurityOrderBookReply
	(*CurrencyRateReply)(nil),           // 22: com.consorsbank.module.tapi.grpc.CurrencyRateReply
	(*SecurityPriceHistoryReply)(nil),   // 23: com.consorsbank.module.tapi.grpc.SecurityPriceHistoryReply
	(*StockExchangeDescriptions)(nil),   // 24: com.consorsbank.module.tapi.grpc.StockExchangeDescriptions
	(*StockExchangeDescription)(nil),    // 25: com.consorsbank.module.tapi.grpc.StockExchangeDescription
	(*Orders)(nil),                      // 26: com.consorsbank.module.tapi.grpc.Orders
	(*Empty)(nil),                       // 27: com.consorsbank.module.tapi.grpc.Empty
	(*QuoteReply)(nil),                  // 28: com.consorsbank.module.tapi.grpc.QuoteReply
	(*OrderReply)(nil),                  // 29: com.consorsbank.module.tapi.grpc.OrderReply
	(*TradingAccounts)(nil),             // 30: com.consorsbank.module.tapi.grpc.TradingAccounts
	(*TradingAccountInformation)(nil),   // 31: com.consorsbank.module.tapi.grpc.TradingAccountInformation
	(*TradingAccountTransactions)(nil),  // 32: com.consorsbank.module.tapi.grpc.TradingAccountTransactions
	(*DepotEntries)(nil),                // 33: com.consorsbank.module.tapi.grpc.DepotEntries
}
var file_TradingAPI_proto_depIdxs = []int32{
	0,  // 0: com.consorsbank.module.tapi.grpc.AccessService.Login:input_type -> com.consorsbank.module.tapi.grpc.LoginRequest
	1,  // 1: com.consorsbank.module.tapi.grpc.AccessService.Logout:input_type -> com.consorsbank.module.tapi.grpc.LogoutRequest
	2,  // 2: com.consorsbank.module.tapi.grpc.SecurityService.GetSecurityInfo:input_type -> com.consorsbank.module.tapi.grpc.SecurityInfoRequest
	3,  // 3: com.consorsbank.module.tapi.grpc.SecurityService.StreamMarketData:input_type -> com.consorsbank.module.tapi.grpc.SecurityMarketDataRequest
	4,  // 4: com.consorsbank.module.tapi.grpc.SecurityService.StreamOrderBook:input_type -> com.consorsbank.module.tapi.grpc.SecurityOrderBookRequest
	5,  // 5: com.consorsbank.module.tapi.grpc.SecurityService.StreamCurrencyRate:input_type -> com.consorsbank.module.tapi.grpc.CurrencyRateRequest
	6,  // 6: com.consorsbank.module.tapi.grpc.SecurityService.GetSecurityPriceHistory:input_type -> com.consorsbank.module.tapi.grpc.SecurityPriceHistoryRequest
	7,  // 7: com.consorsbank.module.tapi.grpc.StockExchangeService.GetStockExchanges:input_type -> com.consorsbank.module.tapi.grpc.AccessTokenRequest
	8,  // 8: com.consorsbank.module.tapi.grpc.StockExchangeService.GetStockExchange:input_type -> com.consorsbank.module.tapi.grpc.StockExchangeRequest
	9,  // 9: com.consorsbank.module.tapi.grpc.OrderService.StreamOrders:input_type -> com.consorsbank.module.tapi.grpc.TradingAccountRequest
	9,  // 10: com.consorsbank.module.tapi.grpc.OrderService.UpdateOrders:input_type -> com.consorsbank.module.tapi.grpc.TradingAccountRequest
	10, // 11: com.consorsbank.module.tapi.grpc.OrderService.GetQuote:input_type -> com.consorsbank.module.tapi.grpc.QuoteRequest
	11, // 12: com.consorsbank.module.tapi.grpc.OrderService.AcceptQuote:input_type -> com.consorsbank.module.tapi.grpc.AcceptQuoteRequest
	12, // 13: com.consorsbank.module.tapi.grpc.OrderService.AddOrder:input_type -> com.consorsbank.module.tapi.grpc.AddOrderRequest
	13, // 14: com.consorsbank.module.tapi.grpc.OrderService.ChangeOrder:input_type -> com.consorsbank.module.tapi.grpc.ChangeOrderRequest
	14, // 15: com.consorsbank.module.tapi.grpc.OrderService.CancelOrder:input_type -> com.consorsbank.module.tapi.grpc.CancelOrderRequest
	15, // 16: com.consorsbank.module.tapi.grpc.OrderService.ActivateOrder:input_type -> com.consorsbank.module.tapi.grpc.ActivateOrderRequest
	16, // 17: com.consorsbank.module.tapi.grpc.OrderService.DeactivateOrder:input_type -> com.consorsbank.module.tapi.grpc.DeactivateOrderRequest
	7,  // 18: com.consorsbank.module.tapi.grpc.AccountService.GetTradingAccounts:input_type -> com.consorsbank.module.tapi.grpc.AccessTokenRequest
	9,  // 19: com.consorsbank.module.tapi.grpc.AccountService.StreamTradingAccount:input_type -> com.consorsbank.module.tapi.grpc.TradingAccountRequest
	9,  // 20: com.consorsbank.module.tapi.grpc.AccountService.StreamTradingAccountTransactions:input_type -> com.consorsbank.module.tapi.grpc.TradingAccountRequest
	9,  // 21: com.consorsbank.module.tapi.grpc.DepotService.StreamDepot:input_type -> com.consorsbank.module.tapi.grpc.TradingAccountRequest
	9,  // 22: com.consorsbank.module.tapi.grpc.DepotService.UpdateDepot:input_type -> com.consorsbank.module.tapi.grpc.TradingAccountRequest
	17, // 23: com.consorsbank.module.tapi.grpc.AccessService.Login:output_type -> com.consorsbank.module.tapi.grpc.LoginReply
	18, // 24: com.consorsbank.module.tapi.grpc.AccessService.Logout:output_type -> com.consorsbank.module.tapi.grpc.LogoutReply
	19, // 25: com.consorsbank.module.tapi.grpc.SecurityService.GetSecurityInfo:output_type -> com.consorsbank.module.tapi.grpc.SecurityInfoReply
	20, // 26: com.consorsbank.module.tapi.grpc.SecurityService.StreamMarketData:output_type -> com.consorsbank.module.tapi.grpc.SecurityMarketDataReply
	21, // 27: com.consorsbank.module.tapi.grpc.SecurityService.StreamOrderBook:output_type -> com.consorsbank.module.tapi.grpc.SecurityOrderBookReply
	22, // 28: com.consorsbank.module.tapi.grpc.SecurityService.StreamCurrencyRate:output_type -> com.consorsbank.module.tapi.grpc.CurrencyRateReply
	23, // 29: com.consorsbank.module.tapi.grpc.SecurityService.GetSecurityPriceHistory:output_type -> com.consorsbank.module.tapi.grpc.SecurityPriceHistoryReply
	24, // 30: com.consorsbank.module.tapi.grpc.StockExchangeService.GetStockExchanges:output_type -> com.consorsbank.module.tapi.grpc.StockExchangeDescriptions
	25, // 31: com.consorsbank.module.tapi.grpc.StockExchangeService.GetStockExchange:output_type -> com.consorsbank.module.tapi.grpc.StockExchangeDescription
	26, // 32: com.consorsbank.module.tapi.grpc.OrderService.StreamOrders:output_type -> com.consorsbank.module.tapi.grpc.Orders
	27, // 33: com.consorsbank.module.tapi.grpc.OrderService.UpdateOrders:output_type -> com.consorsbank.module.tapi.grpc.Empty
	28, // 34: com.consorsbank.module.tapi.grpc.OrderService.GetQuote:output_type -> com.consorsbank.module.tapi.grpc.QuoteReply
	29, // 35: com.consorsbank.module.tapi.grpc.OrderService.AcceptQuote:output_type -> com.consorsbank.module.tapi.grpc.OrderReply
	29, // 36: com.consorsbank.module.tapi.grpc.OrderService.AddOrder:output_type -> com.consorsbank.module.tapi.grpc.OrderReply
	29, // 37: com.consorsbank.module.tapi.grpc.OrderService.ChangeOrder:output_type -> com.consorsbank.module.tapi.grpc.OrderReply
	29, // 38: com.consorsbank.module.tapi.grpc.OrderService.CancelOrder:output_type -> com.consorsbank.module.tapi.grpc.OrderReply
	29, // 39: com.consorsbank.module.tapi.grpc.OrderService.ActivateOrder:output_type -> com.consorsbank.module.tapi.grpc.OrderReply
	29, // 40: com.consorsbank.module.tapi.grpc.OrderService.DeactivateOrder:output_type -> com.consorsbank.module.tapi.grpc.OrderReply
	30, // 41: com.consorsbank.module.tapi.grpc.AccountService.GetTradingAccounts:output_type -> com.consorsbank.module.tapi.grpc.TradingAccounts
	31, // 42: com.consorsbank.module.tapi.grpc.AccountService.StreamTradingAccount:output_type -> com.consorsbank.module.tapi.grpc.TradingAccountInformation
	32, // 43: com.consorsbank.module.tapi.grpc.AccountService.StreamTradingAccountTransactions:output_type -> com.consorsbank.module.tapi.grpc.TradingAccountTransactions
	33, // 44: com.consorsbank.module.tapi.grpc.DepotService.StreamDepot:output_type -> com.consorsbank.module.tapi.grpc.DepotEntries
	27, // 45: com.consorsbank.module.tapi.grpc.DepotService.UpdateDepot:output_type -> com.consorsbank.module.tapi.grpc.Empty
	23, // [23:46] is the sub-list for method output_type
	0,  // [0:23] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_TradingAPI_proto_init() }
func file_TradingAPI_proto_init() {
	if File_TradingAPI_proto != nil {
		return
	}
	file_Common_proto_init()
	file_StockExchangeService_proto_init()
	file_SecurityService_proto_init()
	file_AccountService_proto_init()
	file_OrderService_proto_init()
	file_DepotService_proto_init()
	file_AccessService_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TradingAPI_proto_rawDesc), len(file_TradingAPI_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   6,
		},
		GoTypes:           file_TradingAPI_proto_goTypes,
		DependencyIndexes: file_TradingAPI_proto_depIdxs,
	}.Build()
	File_TradingAPI_proto = out.File
	file_TradingAPI_proto_goTypes = nil
	file_TradingAPI_proto_depIdxs = nil
}
