//
// Copyright 2018, Trading-API, Consorsbank.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: TradingAPI.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccessService_Login_FullMethodName  = "/com.consorsbank.module.tapi.grpc.AccessService/Login"
	AccessService_Logout_FullMethodName = "/com.consorsbank.module.tapi.grpc.AccessService/Logout"
)

// AccessServiceClient is the client API for AccessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// Access service provides functions for the client validation / invalidation
type AccessServiceClient interface {
	// *
	// Validates client by the TAPI and gets access data
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	// *
	// Invalidates client by the TAPI and gets logout result
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutReply, error)
}

type accessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccessServiceClient(cc grpc.ClientConnInterface) AccessServiceClient {
	return &accessServiceClient{cc}
}

func (c *accessServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, AccessService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutReply)
	err := c.cc.Invoke(ctx, AccessService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessServiceServer is the server API for AccessService service.
// All implementations must embed UnimplementedAccessServiceServer
// for forward compatibility.
//
// *
// Access service provides functions for the client validation / invalidation
type AccessServiceServer interface {
	// *
	// Validates client by the TAPI and gets access data
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	// *
	// Invalidates client by the TAPI and gets logout result
	Logout(context.Context, *LogoutRequest) (*LogoutReply, error)
	mustEmbedUnimplementedAccessServiceServer()
}

// UnimplementedAccessServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccessServiceServer struct{}

func (UnimplementedAccessServiceServer) Login(context.Context, *LoginRequest) (*LoginReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAccessServiceServer) Logout(context.Context, *LogoutRequest) (*LogoutReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedAccessServiceServer) mustEmbedUnimplementedAccessServiceServer() {}
func (UnimplementedAccessServiceServer) testEmbeddedByValue()                       {}

// UnsafeAccessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccessServiceServer will
// result in compilation errors.
type UnsafeAccessServiceServer interface {
	mustEmbedUnimplementedAccessServiceServer()
}

func RegisterAccessServiceServer(s grpc.ServiceRegistrar, srv AccessServiceServer) {
	// If the following call panics, it indicates UnimplementedAccessServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccessService_ServiceDesc, srv)
}

func _AccessService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccessService_ServiceDesc is the grpc.ServiceDesc for AccessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.consorsbank.module.tapi.grpc.AccessService",
	HandlerType: (*AccessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AccessService_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _AccessService_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "TradingAPI.proto",
}

const (
	SecurityService_GetSecurityInfo_FullMethodName         = "/com.consorsbank.module.tapi.grpc.SecurityService/GetSecurityInfo"
	SecurityService_StreamMarketData_FullMethodName        = "/com.consorsbank.module.tapi.grpc.SecurityService/StreamMarketData"
	SecurityService_StreamOrderBook_FullMethodName         = "/com.consorsbank.module.tapi.grpc.SecurityService/StreamOrderBook"
	SecurityService_StreamCurrencyRate_FullMethodName      = "/com.consorsbank.module.tapi.grpc.SecurityService/StreamCurrencyRate"
	SecurityService_GetSecurityPriceHistory_FullMethodName = "/com.consorsbank.module.tapi.grpc.SecurityService/GetSecurityPriceHistory"
)

// SecurityServiceClient is the client API for SecurityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// Security service provides access
// to the
type SecurityServiceClient interface {
	// *
	// Gets security information about security
	// @param SecurityInfoRequest
	//
	//	Request object with interested security
	//
	// @return SecurityInfoReply
	//
	//	Complete information about security
	GetSecurityInfo(ctx context.Context, in *SecurityInfoRequest, opts ...grpc.CallOption) (*SecurityInfoReply, error)
	// *
	// Subscribes security with stock exchange for market data updates
	// @param SecurityMarketDataRequest
	//
	//	Market data request with interested security and stock exchange
	//
	// @stream SecurityMarketDataReply
	//
	//	Reply with all market data values
	StreamMarketData(ctx context.Context, in *SecurityMarketDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SecurityMarketDataReply], error)
	// *
	// Subscribes security with stock exchange for orderbook updates
	// @param SecurityOrderBookRequest
	//
	//	Orderbook data request with interested security and stock exchange
	//
	// @stream SecurityOrderBookReply
	//
	//	Reply with all orderbook values
	StreamOrderBook(ctx context.Context, in *SecurityOrderBookRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SecurityOrderBookReply], error)
	// *
	// Subscribes for currency rate from one currency to another currency.
	// @param SecurityOrderBookRequest
	//
	//	currency rate request with interested currencies from/to
	//
	// @stream CurrencyRateReply
	//
	//	reply with currency rate
	StreamCurrencyRate(ctx context.Context, in *CurrencyRateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CurrencyRateReply], error)
	// *
	// Requests history data for one security on one stockexchange in intraday or historical format
	// @param SecurityPriceHistoryRequest
	//
	//	Data with security, stockexchange, how many days and resolution
	//
	// @return SecurityPriceHistoryReply
	//
	//	List of the historical quotes or an error
	GetSecurityPriceHistory(ctx context.Context, in *SecurityPriceHistoryRequest, opts ...grpc.CallOption) (*SecurityPriceHistoryReply, error)
}

type securityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSecurityServiceClient(cc grpc.ClientConnInterface) SecurityServiceClient {
	return &securityServiceClient{cc}
}

func (c *securityServiceClient) GetSecurityInfo(ctx context.Context, in *SecurityInfoRequest, opts ...grpc.CallOption) (*SecurityInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecurityInfoReply)
	err := c.cc.Invoke(ctx, SecurityService_GetSecurityInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityServiceClient) StreamMarketData(ctx context.Context, in *SecurityMarketDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SecurityMarketDataReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SecurityService_ServiceDesc.Streams[0], SecurityService_StreamMarketData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SecurityMarketDataRequest, SecurityMarketDataReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SecurityService_StreamMarketDataClient = grpc.ServerStreamingClient[SecurityMarketDataReply]

func (c *securityServiceClient) StreamOrderBook(ctx context.Context, in *SecurityOrderBookRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SecurityOrderBookReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SecurityService_ServiceDesc.Streams[1], SecurityService_StreamOrderBook_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SecurityOrderBookRequest, SecurityOrderBookReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SecurityService_StreamOrderBookClient = grpc.ServerStreamingClient[SecurityOrderBookReply]

func (c *securityServiceClient) StreamCurrencyRate(ctx context.Context, in *CurrencyRateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CurrencyRateReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SecurityService_ServiceDesc.Streams[2], SecurityService_StreamCurrencyRate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CurrencyRateRequest, CurrencyRateReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SecurityService_StreamCurrencyRateClient = grpc.ServerStreamingClient[CurrencyRateReply]

func (c *securityServiceClient) GetSecurityPriceHistory(ctx context.Context, in *SecurityPriceHistoryRequest, opts ...grpc.CallOption) (*SecurityPriceHistoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecurityPriceHistoryReply)
	err := c.cc.Invoke(ctx, SecurityService_GetSecurityPriceHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecurityServiceServer is the server API for SecurityService service.
// All implementations must embed UnimplementedSecurityServiceServer
// for forward compatibility.
//
// *
// Security service provides access
// to the
type SecurityServiceServer interface {
	// *
	// Gets security information about security
	// @param SecurityInfoRequest
	//
	//	Request object with interested security
	//
	// @return SecurityInfoReply
	//
	//	Complete information about security
	GetSecurityInfo(context.Context, *SecurityInfoRequest) (*SecurityInfoReply, error)
	// *
	// Subscribes security with stock exchange for market data updates
	// @param SecurityMarketDataRequest
	//
	//	Market data request with interested security and stock exchange
	//
	// @stream SecurityMarketDataReply
	//
	//	Reply with all market data values
	StreamMarketData(*SecurityMarketDataRequest, grpc.ServerStreamingServer[SecurityMarketDataReply]) error
	// *
	// Subscribes security with stock exchange for orderbook updates
	// @param SecurityOrderBookRequest
	//
	//	Orderbook data request with interested security and stock exchange
	//
	// @stream SecurityOrderBookReply
	//
	//	Reply with all orderbook values
	StreamOrderBook(*SecurityOrderBookRequest, grpc.ServerStreamingServer[SecurityOrderBookReply]) error
	// *
	// Subscribes for currency rate from one currency to another currency.
	// @param SecurityOrderBookRequest
	//
	//	currency rate request with interested currencies from/to
	//
	// @stream CurrencyRateReply
	//
	//	reply with currency rate
	StreamCurrencyRate(*CurrencyRateRequest, grpc.ServerStreamingServer[CurrencyRateReply]) error
	// *
	// Requests history data for one security on one stockexchange in intraday or historical format
	// @param SecurityPriceHistoryRequest
	//
	//	Data with security, stockexchange, how many days and resolution
	//
	// @return SecurityPriceHistoryReply
	//
	//	List of the historical quotes or an error
	GetSecurityPriceHistory(context.Context, *SecurityPriceHistoryRequest) (*SecurityPriceHistoryReply, error)
	mustEmbedUnimplementedSecurityServiceServer()
}

// UnimplementedSecurityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecurityServiceServer struct{}

func (UnimplementedSecurityServiceServer) GetSecurityInfo(context.Context, *SecurityInfoRequest) (*SecurityInfoReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSecurityInfo not implemented")
}
func (UnimplementedSecurityServiceServer) StreamMarketData(*SecurityMarketDataRequest, grpc.ServerStreamingServer[SecurityMarketDataReply]) error {
	return status.Error(codes.Unimplemented, "method StreamMarketData not implemented")
}
func (UnimplementedSecurityServiceServer) StreamOrderBook(*SecurityOrderBookRequest, grpc.ServerStreamingServer[SecurityOrderBookReply]) error {
	return status.Error(codes.Unimplemented, "method StreamOrderBook not implemented")
}
func (UnimplementedSecurityServiceServer) StreamCurrencyRate(*CurrencyRateRequest, grpc.ServerStreamingServer[CurrencyRateReply]) error {
	return status.Error(codes.Unimplemented, "method StreamCurrencyRate not implemented")
}
func (UnimplementedSecurityServiceServer) GetSecurityPriceHistory(context.Context, *SecurityPriceHistoryRequest) (*SecurityPriceHistoryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSecurityPriceHistory not implemented")
}
func (UnimplementedSecurityServiceServer) mustEmbedUnimplementedSecurityServiceServer() {}
func (UnimplementedSecurityServiceServer) testEmbeddedByValue()                         {}

// UnsafeSecurityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecurityServiceServer will
// result in compilation errors.
type UnsafeSecurityServiceServer interface {
	mustEmbedUnimplementedSecurityServiceServer()
}

func RegisterSecurityServiceServer(s grpc.ServiceRegistrar, srv SecurityServiceServer) {
	// If the following call panics, it indicates UnimplementedSecurityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecurityService_ServiceDesc, srv)
}

func _SecurityService_GetSecurityInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecurityInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityServiceServer).GetSecurityInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityService_GetSecurityInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityServiceServer).GetSecurityInfo(ctx, req.(*SecurityInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityService_StreamMarketData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SecurityMarketDataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SecurityServiceServer).StreamMarketData(m, &grpc.GenericServerStream[SecurityMarketDataRequest, SecurityMarketDataReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SecurityService_StreamMarketDataServer = grpc.ServerStreamingServer[SecurityMarketDataReply]

func _SecurityService_StreamOrderBook_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SecurityOrderBookRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SecurityServiceServer).StreamOrderBook(m, &grpc.GenericServerStream[SecurityOrderBookRequest, SecurityOrderBookReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SecurityService_StreamOrderBookServer = grpc.ServerStreamingServer[SecurityOrderBookReply]

func _SecurityService_StreamCurrencyRate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CurrencyRateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SecurityServiceServer).StreamCurrencyRate(m, &grpc.GenericServerStream[CurrencyRateRequest, CurrencyRateReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SecurityService_StreamCurrencyRateServer = grpc.ServerStreamingServer[CurrencyRateReply]

func _SecurityService_GetSecurityPriceHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecurityPriceHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityServiceServer).GetSecurityPriceHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityService_GetSecurityPriceHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityServiceServer).GetSecurityPriceHistory(ctx, req.(*SecurityPriceHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecurityService_ServiceDesc is the grpc.ServiceDesc for SecurityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecurityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.consorsbank.module.tapi.grpc.SecurityService",
	HandlerType: (*SecurityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSecurityInfo",
			Handler:    _SecurityService_GetSecurityInfo_Handler,
		},
		{
			MethodName: "GetSecurityPriceHistory",
			Handler:    _SecurityService_GetSecurityPriceHistory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMarketData",
			Handler:       _SecurityService_StreamMarketData_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamOrderBook",
			Handler:       _SecurityService_StreamOrderBook_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamCurrencyRate",
			Handler:       _SecurityService_StreamCurrencyRate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "TradingAPI.proto",
}

const (
	StockExchangeService_GetStockExchanges_FullMethodName = "/com.consorsbank.module.tapi.grpc.StockExchangeService/GetStockExchanges"
	StockExchangeService_GetStockExchange_FullMethodName  = "/com.consorsbank.module.tapi.grpc.StockExchangeService/GetStockExchange"
)

// StockExchangeServiceClient is the client API for StockExchangeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// StockExchangeService provide information about stockexchanges and
// issuers
type StockExchangeServiceClient interface {
	// *
	// Gets predefined stockexchages
	// @return StockExchangeDescriptions
	//
	//	list of stock exchange informations
	GetStockExchanges(ctx context.Context, in *AccessTokenRequest, opts ...grpc.CallOption) (*StockExchangeDescriptions, error)
	// *
	// Gets specific stock exchange
	// @param StockExchange
	//
	//	Requested stock exchange
	//
	// @return StockExchangeDescription
	//
	//	Stock exchange information
	GetStockExchange(ctx context.Context, in *StockExchangeRequest, opts ...grpc.CallOption) (*StockExchangeDescription, error)
}

type stockExchangeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStockExchangeServiceClient(cc grpc.ClientConnInterface) StockExchangeServiceClient {
	return &stockExchangeServiceClient{cc}
}

func (c *stockExchangeServiceClient) GetStockExchanges(ctx context.Context, in *AccessTokenRequest, opts ...grpc.CallOption) (*StockExchangeDescriptions, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockExchangeDescriptions)
	err := c.cc.Invoke(ctx, StockExchangeService_GetStockExchanges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockExchangeServiceClient) GetStockExchange(ctx context.Context, in *StockExchangeRequest, opts ...grpc.CallOption) (*StockExchangeDescription, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockExchangeDescription)
	err := c.cc.Invoke(ctx, StockExchangeService_GetStockExchange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StockExchangeServiceServer is the server API for StockExchangeService service.
// All implementations must embed UnimplementedStockExchangeServiceServer
// for forward compatibility.
//
// *
// StockExchangeService provide information about stockexchanges and
// issuers
type StockExchangeServiceServer interface {
	// *
	// Gets predefined stockexchages
	// @return StockExchangeDescriptions
	//
	//	list of stock exchange informations
	GetStockExchanges(context.Context, *AccessTokenRequest) (*StockExchangeDescriptions, error)
	// *
	// Gets specific stock exchange
	// @param StockExchange
	//
	//	Requested stock exchange
	//
	// @return StockExchangeDescription
	//
	//	Stock exchange information
	GetStockExchange(context.Context, *StockExchangeRequest) (*StockExchangeDescription, error)
	mustEmbedUnimplementedStockExchangeServiceServer()
}

// UnimplementedStockExchangeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStockExchangeServiceServer struct{}

func (UnimplementedStockExchangeServiceServer) GetStockExchanges(context.Context, *AccessTokenRequest) (*StockExchangeDescriptions, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStockExchanges not implemented")
}
func (UnimplementedStockExchangeServiceServer) GetStockExchange(context.Context, *StockExchangeRequest) (*StockExchangeDescription, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStockExchange not implemented")
}
func (UnimplementedStockExchangeServiceServer) mustEmbedUnimplementedStockExchangeServiceServer() {}
func (UnimplementedStockExchangeServiceServer) testEmbeddedByValue()                              {}

// UnsafeStockExchangeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StockExchangeServiceServer will
// result in compilation errors.
type UnsafeStockExchangeServiceServer interface {
	mustEmbedUnimplementedStockExchangeServiceServer()
}

func RegisterStockExchangeServiceServer(s grpc.ServiceRegistrar, srv StockExchangeServiceServer) {
	// If the following call panics, it indicates UnimplementedStockExchangeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StockExchangeService_ServiceDesc, srv)
}

func _StockExchangeService_GetStockExchanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockExchangeServiceServer).GetStockExchanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockExchangeService_GetStockExchanges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockExchangeServiceServer).GetStockExchanges(ctx, req.(*AccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockExchangeService_GetStockExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockExchangeServiceServer).GetStockExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockExchangeService_GetStockExchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockExchangeServiceServer).GetStockExchange(ctx, req.(*StockExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StockExchangeService_ServiceDesc is the grpc.ServiceDesc for StockExchangeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StockExchangeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.consorsbank.module.tapi.grpc.StockExchangeService",
	HandlerType: (*StockExchangeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStockExchanges",
			Handler:    _StockExchangeService_GetStockExchanges_Handler,
		},
		{
			MethodName: "GetStockExchange",
			Handler:    _StockExchangeService_GetStockExchange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "TradingAPI.proto",
}

const (
	OrderService_StreamOrders_FullMethodName    = "/com.consorsbank.module.tapi.grpc.OrderService/StreamOrders"
	OrderService_UpdateOrders_FullMethodName    = "/com.consorsbank.module.tapi.grpc.OrderService/UpdateOrders"
	OrderService_GetQuote_FullMethodName        = "/com.consorsbank.module.tapi.grpc.OrderService/GetQuote"
	OrderService_AcceptQuote_FullMethodName     = "/com.consorsbank.module.tapi.grpc.OrderService/AcceptQuote"
	OrderService_AddOrder_FullMethodName        = "/com.consorsbank.module.tapi.grpc.OrderService/AddOrder"
	OrderService_ChangeOrder_FullMethodName     = "/com.consorsbank.module.tapi.grpc.OrderService/ChangeOrder"
	OrderService_CancelOrder_FullMethodName     = "/com.consorsbank.module.tapi.grpc.OrderService/CancelOrder"
	OrderService_ActivateOrder_FullMethodName   = "/com.consorsbank.module.tapi.grpc.OrderService/ActivateOrder"
	OrderService_DeactivateOrder_FullMethodName = "/com.consorsbank.module.tapi.grpc.OrderService/DeactivateOrder"
)

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// Order service provide functionality to control orders.
type OrderServiceClient interface {
	// *
	// Subscribes one trading account for orders updates
	// @param TradingAccount
	//
	//	Trading account for push
	//
	// @stream Orders
	//
	//	Orders list for seleted account
	StreamOrders(ctx context.Context, in *TradingAccountRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Orders], error)
	// *
	// Initiates orders update action. All changes come by the
	// StreamOrders subscription. This function doesn't wait for the action result.
	// @param TradingAccount
	//
	//	Trading account for update
	UpdateOrders(ctx context.Context, in *TradingAccountRequest, opts ...grpc.CallOption) (*Empty, error)
	// *
	// Request market quote for the selected security on the selected stock exchanges.
	// @param QuoteRequest
	//
	//	quote request with interested security and stock exchanges
	//
	// @return QuoteReply
	//
	//	quote reply with quotes
	GetQuote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteReply, error)
	// *
	// Sends accept quote order request to the short term market
	// @param AcceptQuoteRequest
	//
	//	accept quote request with order parameters
	//
	// @return OrderReply
	//
	//	result order or error
	AcceptQuote(ctx context.Context, in *AcceptQuoteRequest, opts ...grpc.CallOption) (*OrderReply, error)
	// *
	// Sends long term order to the market
	// @param AddOrderRequest
	//
	//	order request with order parameters
	//
	// @return OrderReply
	//
	//	result order or error
	AddOrder(ctx context.Context, in *AddOrderRequest, opts ...grpc.CallOption) (*OrderReply, error)
	// *
	// Sends order change request to the market
	// @param ChangeOrderRequest
	//
	//	changed order request with order parameters
	//
	// @return OrderReply
	//
	//	result order or error
	ChangeOrder(ctx context.Context, in *ChangeOrderRequest, opts ...grpc.CallOption) (*OrderReply, error)
	// *
	// Sends order cancel request to the market
	// @param CancelOrderRequest
	//
	//	cancel order request with order reference
	//
	// @return OrderReply
	//
	//	result order or error
	CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*OrderReply, error)
	// *
	// Sends order activate request to the market. #pro# only
	// @param ActivateOrderRequest
	//
	//	activate order request with order parameters
	//
	// @return OrderReply
	//
	//	result order or error
	ActivateOrder(ctx context.Context, in *ActivateOrderRequest, opts ...grpc.CallOption) (*OrderReply, error)
	// *
	// Sends order deactivate request to the market. #pro# only
	// @param DeactivateOrderRequest
	//
	//	deactivate order request with order parameters
	//
	// @return OrderReply
	//
	//	result order or error
	DeactivateOrder(ctx context.Context, in *DeactivateOrderRequest, opts ...grpc.CallOption) (*OrderReply, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) StreamOrders(ctx context.Context, in *TradingAccountRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Orders], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrderService_ServiceDesc.Streams[0], OrderService_StreamOrders_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TradingAccountRequest, Orders]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderService_StreamOrdersClient = grpc.ServerStreamingClient[Orders]

func (c *orderServiceClient) UpdateOrders(ctx context.Context, in *TradingAccountRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, OrderService_UpdateOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetQuote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuoteReply)
	err := c.cc.Invoke(ctx, OrderService_GetQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) AcceptQuote(ctx context.Context, in *AcceptQuoteRequest, opts ...grpc.CallOption) (*OrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderReply)
	err := c.cc.Invoke(ctx, OrderService_AcceptQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) AddOrder(ctx context.Context, in *AddOrderRequest, opts ...grpc.CallOption) (*OrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderReply)
	err := c.cc.Invoke(ctx, OrderService_AddOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ChangeOrder(ctx context.Context, in *ChangeOrderRequest, opts ...grpc.CallOption) (*OrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderReply)
	err := c.cc.Invoke(ctx, OrderService_ChangeOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*OrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderReply)
	err := c.cc.Invoke(ctx, OrderService_CancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ActivateOrder(ctx context.Context, in *ActivateOrderRequest, opts ...grpc.CallOption) (*OrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderReply)
	err := c.cc.Invoke(ctx, OrderService_ActivateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) DeactivateOrder(ctx context.Context, in *DeactivateOrderRequest, opts ...grpc.CallOption) (*OrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderReply)
	err := c.cc.Invoke(ctx, OrderService_DeactivateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
// All implementations must embed UnimplementedOrderServiceServer
// for forward compatibility.
//
// *
// Order service provide functionality to control orders.
type OrderServiceServer interface {
	// *
	// Subscribes one trading account for orders updates
	// @param TradingAccount
	//
	//	Trading account for push
	//
	// @stream Orders
	//
	//	Orders list for seleted account
	StreamOrders(*TradingAccountRequest, grpc.ServerStreamingServer[Orders]) error
	// *
	// Initiates orders update action. All changes come by the
	// StreamOrders subscription. This function doesn't wait for the action result.
	// @param TradingAccount
	//
	//	Trading account for update
	UpdateOrders(context.Context, *TradingAccountRequest) (*Empty, error)
	// *
	// Request market quote for the selected security on the selected stock exchanges.
	// @param QuoteRequest
	//
	//	quote request with interested security and stock exchanges
	//
	// @return QuoteReply
	//
	//	quote reply with quotes
	GetQuote(context.Context, *QuoteRequest) (*QuoteReply, error)
	// *
	// Sends accept quote order request to the short term market
	// @param AcceptQuoteRequest
	//
	//	accept quote request with order parameters
	//
	// @return OrderReply
	//
	//	result order or error
	AcceptQuote(context.Context, *AcceptQuoteRequest) (*OrderReply, error)
	// *
	// Sends long term order to the market
	// @param AddOrderRequest
	//
	//	order request with order parameters
	//
	// @return OrderReply
	//
	//	result order or error
	AddOrder(context.Context, *AddOrderRequest) (*OrderReply, error)
	// *
	// Sends order change request to the market
	// @param ChangeOrderRequest
	//
	//	changed order request with order parameters
	//
	// @return OrderReply
	//
	//	result order or error
	ChangeOrder(context.Context, *ChangeOrderRequest) (*OrderReply, error)
	// *
	// Sends order cancel request to the market
	// @param CancelOrderRequest
	//
	//	cancel order request with order reference
	//
	// @return OrderReply
	//
	//	result order or error
	CancelOrder(context.Context, *CancelOrderRequest) (*OrderReply, error)
	// *
	// Sends order activate request to the market. #pro# only
	// @param ActivateOrderRequest
	//
	//	activate order request with order parameters
	//
	// @return OrderReply
	//
	//	result order or error
	ActivateOrder(context.Context, *ActivateOrderRequest) (*OrderReply, error)
	// *
	// Sends order deactivate request to the market. #pro# only
	// @param DeactivateOrderRequest
	//
	//	deactivate order request with order parameters
	//
	// @return OrderReply
	//
	//	result order or error
	DeactivateOrder(context.Context, *DeactivateOrderRequest) (*OrderReply, error)
	mustEmbedUnimplementedOrderServiceServer()
}

// UnimplementedOrderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderServiceServer struct{}

func (UnimplementedOrderServiceServer) StreamOrders(*TradingAccountRequest, grpc.ServerStreamingServer[Orders]) error {
	return status.Error(codes.Unimplemented, "method StreamOrders not implemented")
}
func (UnimplementedOrderServiceServer) UpdateOrders(context.Context, *TradingAccountRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateOrders not implemented")
}
func (UnimplementedOrderServiceServer) GetQuote(context.Context, *QuoteRequest) (*QuoteReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQuote not implemented")
}
func (UnimplementedOrderServiceServer) AcceptQuote(context.Context, *AcceptQuoteRequest) (*OrderReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptQuote not implemented")
}
func (UnimplementedOrderServiceServer) AddOrder(context.Context, *AddOrderRequest) (*OrderReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AddOrder not implemented")
}
func (UnimplementedOrderServiceServer) ChangeOrder(context.Context, *ChangeOrderRequest) (*OrderReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeOrder not implemented")
}
func (UnimplementedOrderServiceServer) CancelOrder(context.Context, *CancelOrderRequest) (*OrderReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedOrderServiceServer) ActivateOrder(context.Context, *ActivateOrderRequest) (*OrderReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateOrder not implemented")
}
func (UnimplementedOrderServiceServer) DeactivateOrder(context.Context, *DeactivateOrderRequest) (*OrderReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeactivateOrder not implemented")
}
func (UnimplementedOrderServiceServer) mustEmbedUnimplementedOrderServiceServer() {}
func (UnimplementedOrderServiceServer) testEmbeddedByValue()                      {}

// UnsafeOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServiceServer will
// result in compilation errors.
type UnsafeOrderServiceServer interface {
	mustEmbedUnimplementedOrderServiceServer()
}

func RegisterOrderServiceServer(s grpc.ServiceRegistrar, srv OrderServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderService_ServiceDesc, srv)
}

func _OrderService_StreamOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TradingAccountRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrderServiceServer).StreamOrders(m, &grpc.GenericServerStream[TradingAccountRequest, Orders]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderService_StreamOrdersServer = grpc.ServerStreamingServer[Orders]

func _OrderService_UpdateOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradingAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).UpdateOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_UpdateOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).UpdateOrders(ctx, req.(*TradingAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetQuote(ctx, req.(*QuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_AcceptQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).AcceptQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_AcceptQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).AcceptQuote(ctx, req.(*AcceptQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_AddOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).AddOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_AddOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).AddOrder(ctx, req.(*AddOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ChangeOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ChangeOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_ChangeOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ChangeOrder(ctx, req.(*ChangeOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CancelOrder(ctx, req.(*CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ActivateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ActivateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_ActivateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ActivateOrder(ctx, req.(*ActivateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_DeactivateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).DeactivateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_DeactivateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).DeactivateOrder(ctx, req.(*DeactivateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderService_ServiceDesc is the grpc.ServiceDesc for OrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.consorsbank.module.tapi.grpc.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateOrders",
			Handler:    _OrderService_UpdateOrders_Handler,
		},
		{
			MethodName: "GetQuote",
			Handler:    _OrderService_GetQuote_Handler,
		},
		{
			MethodName: "AcceptQuote",
			Handler:    _OrderService_AcceptQuote_Handler,
		},
		{
			MethodName: "AddOrder",
			Handler:    _OrderService_AddOrder_Handler,
		},
		{
			MethodName: "ChangeOrder",
			Handler:    _OrderService_ChangeOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _OrderService_CancelOrder_Handler,
		},
		{
			MethodName: "ActivateOrder",
			Handler:    _OrderService_ActivateOrder_Handler,
		},
		{
			MethodName: "DeactivateOrder",
			Handler:    _OrderService_DeactivateOrder_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamOrders",
			Handler:       _OrderService_StreamOrders_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "TradingAPI.proto",
}

const (
	AccountService_GetTradingAccounts_FullMethodName               = "/com.consorsbank.module.tapi.grpc.AccountService/GetTradingAccounts"
	AccountService_StreamTradingAccount_FullMethodName             = "/com.consorsbank.module.tapi.grpc.AccountService/StreamTradingAccount"
	AccountService_StreamTradingAccountTransactions_FullMethodName = "/com.consorsbank.module.tapi.grpc.AccountService/StreamTradingAccountTransactions"
)

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// AccountService provide functionality with access
// to the trading accounts
type AccountServiceClient interface {
	// *
	// Gets trading accounts
	// @return TradingAccounts
	//
	//	List of trading accounts
	GetTradingAccounts(ctx context.Context, in *AccessTokenRequest, opts ...grpc.CallOption) (*TradingAccounts, error)
	// *
	// Subscribes one trading account for updates
	// @param TradingAccount
	//
	//	Trading account for push
	//
	// @stream TradingAccountInformation
	//
	//	Specific information for subscribed account (balance, kredit line, etc.)
	StreamTradingAccount(ctx context.Context, in *TradingAccountRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TradingAccountInformation], error)
	// *
	// Subscribes one trading account for the transactions updates
	// @param TradingAccount
	//
	//	Trading account for push
	//
	// @stream TradingAccountInformation
	//
	//	Transactions list for subscribed account
	StreamTradingAccountTransactions(ctx context.Context, in *TradingAccountRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TradingAccountTransactions], error)
}

type accountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountServiceClient(cc grpc.ClientConnInterface) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) GetTradingAccounts(ctx context.Context, in *AccessTokenRequest, opts ...grpc.CallOption) (*TradingAccounts, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradingAccounts)
	err := c.cc.Invoke(ctx, AccountService_GetTradingAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) StreamTradingAccount(ctx context.Context, in *TradingAccountRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TradingAccountInformation], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AccountService_ServiceDesc.Streams[0], AccountService_StreamTradingAccount_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TradingAccountRequest, TradingAccountInformation]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccountService_StreamTradingAccountClient = grpc.ServerStreamingClient[TradingAccountInformation]

func (c *accountServiceClient) StreamTradingAccountTransactions(ctx context.Context, in *TradingAccountRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TradingAccountTransactions], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AccountService_ServiceDesc.Streams[1], AccountService_StreamTradingAccountTransactions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TradingAccountRequest, TradingAccountTransactions]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccountService_StreamTradingAccountTransactionsClient = grpc.ServerStreamingClient[TradingAccountTransactions]

// AccountServiceServer is the server API for AccountService service.
// All implementations must embed UnimplementedAccountServiceServer
// for forward compatibility.
//
// *
// AccountService provide functionality with access
// to the trading accounts
type AccountServiceServer interface {
	// *
	// Gets trading accounts
	// @return TradingAccounts
	//
	//	List of trading accounts
	GetTradingAccounts(context.Context, *AccessTokenRequest) (*TradingAccounts, error)
	// *
	// Subscribes one trading account for updates
	// @param TradingAccount
	//
	//	Trading account for push
	//
	// @stream TradingAccountInformation
	//
	//	Specific information for subscribed account (balance, kredit line, etc.)
	StreamTradingAccount(*TradingAccountRequest, grpc.ServerStreamingServer[TradingAccountInformation]) error
	// *
	// Subscribes one trading account for the transactions updates
	// @param TradingAccount
	//
	//	Trading account for push
	//
	// @stream TradingAccountInformation
	//
	//	Transactions list for subscribed account
	StreamTradingAccountTransactions(*TradingAccountRequest, grpc.ServerStreamingServer[TradingAccountTransactions]) error
	mustEmbedUnimplementedAccountServiceServer()
}

// UnimplementedAccountServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountServiceServer struct{}

func (UnimplementedAccountServiceServer) GetTradingAccounts(context.Context, *AccessTokenRequest) (*TradingAccounts, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTradingAccounts not implemented")
}
func (UnimplementedAccountServiceServer) StreamTradingAccount(*TradingAccountRequest, grpc.ServerStreamingServer[TradingAccountInformation]) error {
	return status.Error(codes.Unimplemented, "method StreamTradingAccount not implemented")
}
func (UnimplementedAccountServiceServer) StreamTradingAccountTransactions(*TradingAccountRequest, grpc.ServerStreamingServer[TradingAccountTransactions]) error {
	return status.Error(codes.Unimplemented, "method StreamTradingAccountTransactions not implemented")
}
func (UnimplementedAccountServiceServer) mustEmbedUnimplementedAccountServiceServer() {}
func (UnimplementedAccountServiceServer) testEmbeddedByValue()                        {}

// UnsafeAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountServiceServer will
// result in compilation errors.
type UnsafeAccountServiceServer interface {
	mustEmbedUnimplementedAccountServiceServer()
}

func RegisterAccountServiceServer(s grpc.ServiceRegistrar, srv AccountServiceServer) {
	// If the following call panics, it indicates UnimplementedAccountServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountService_ServiceDesc, srv)
}

func _AccountService_GetTradingAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetTradingAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetTradingAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetTradingAccounts(ctx, req.(*AccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_StreamTradingAccount_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TradingAccountRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AccountServiceServer).StreamTradingAccount(m, &grpc.GenericServerStream[TradingAccountRequest, TradingAccountInformation]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccountService_StreamTradingAccountServer = grpc.ServerStreamingServer[TradingAccountInformation]

func _AccountService_StreamTradingAccountTransactions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TradingAccountRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AccountServiceServer).StreamTradingAccountTransactions(m, &grpc.GenericServerStream[TradingAccountRequest, TradingAccountTransactions]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccountService_StreamTradingAccountTransactionsServer = grpc.ServerStreamingServer[TradingAccountTransactions]

// AccountService_ServiceDesc is the grpc.ServiceDesc for AccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.consorsbank.module.tapi.grpc.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTradingAccounts",
			Handler:    _AccountService_GetTradingAccounts_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTradingAccount",
			Handler:       _AccountService_StreamTradingAccount_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamTradingAccountTransactions",
			Handler:       _AccountService_StreamTradingAccountTransactions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "TradingAPI.proto",
}

const (
	DepotService_StreamDepot_FullMethodName = "/com.consorsbank.module.tapi.grpc.DepotService/StreamDepot"
	DepotService_UpdateDepot_FullMethodName = "/com.consorsbank.module.tapi.grpc.DepotService/UpdateDepot"
)

// DepotServiceClient is the client API for DepotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// Depot service provides access to the depot linked to the account
type DepotServiceClient interface {
	// *
	// Subscribes one trading account for the depot data updates
	// @param TradingAccount
	//
	//	Trading account for push
	//
	// @stream DepotEntries depot entries linked to the account
	StreamDepot(ctx context.Context, in *TradingAccountRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DepotEntries], error)
	// *
	// Initiates depot update action. All changes come by the
	// StreamDepot subscription. This function doesn't wait for the action result.
	// @param TradingAccount
	//
	//	Trading account for update
	UpdateDepot(ctx context.Context, in *TradingAccountRequest, opts ...grpc.CallOption) (*Empty, error)
}

type depotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDepotServiceClient(cc grpc.ClientConnInterface) DepotServiceClient {
	return &depotServiceClient{cc}
}

func (c *depotServiceClient) StreamDepot(ctx context.Context, in *TradingAccountRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DepotEntries], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DepotService_ServiceDesc.Streams[0], DepotService_StreamDepot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TradingAccountRequest, DepotEntries]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DepotService_StreamDepotClient = grpc.ServerStreamingClient[DepotEntries]

func (c *depotServiceClient) UpdateDepot(ctx context.Context, in *TradingAccountRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DepotService_UpdateDepot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DepotServiceServer is the server API for DepotService service.
// All implementations must embed UnimplementedDepotServiceServer
// for forward compatibility.
//
// *
// Depot service provides access to the depot linked to the account
type DepotServiceServer interface {
	// *
	// Subscribes one trading account for the depot data updates
	// @param TradingAccount
	//
	//	Trading account for push
	//
	// @stream DepotEntries depot entries linked to the account
	StreamDepot(*TradingAccountRequest, grpc.ServerStreamingServer[DepotEntries]) error
	// *
	// Initiates depot update action. All changes come by the
	// StreamDepot subscription. This function doesn't wait for the action result.
	// @param TradingAccount
	//
	//	Trading account for update
	UpdateDepot(context.Context, *TradingAccountRequest) (*Empty, error)
	mustEmbedUnimplementedDepotServiceServer()
}

// UnimplementedDepotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDepotServiceServer struct{}

func (UnimplementedDepotServiceServer) StreamDepot(*TradingAccountRequest, grpc.ServerStreamingServer[DepotEntries]) error {
	return status.Error(codes.Unimplemented, "method StreamDepot not implemented")
}
func (UnimplementedDepotServiceServer) UpdateDepot(context.Context, *TradingAccountRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDepot not implemented")
}
func (UnimplementedDepotServiceServer) mustEmbedUnimplementedDepotServiceServer() {}
func (UnimplementedDepotServiceServer) testEmbeddedByValue()                      {}

// UnsafeDepotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DepotServiceServer will
// result in compilation errors.
type UnsafeDepotServiceServer interface {
	mustEmbedUnimplementedDepotServiceServer()
}

func RegisterDepotServiceServer(s grpc.ServiceRegistrar, srv DepotServiceServer) {
	// If the following call panics, it indicates UnimplementedDepotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DepotService_ServiceDesc, srv)
}

func _DepotService_StreamDepot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TradingAccountRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DepotServiceServer).StreamDepot(m, &grpc.GenericServerStream[TradingAccountRequest, DepotEntries]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DepotService_StreamDepotServer = grpc.ServerStreamingServer[DepotEntries]

func _DepotService_UpdateDepot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradingAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepotServiceServer).UpdateDepot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepotService_UpdateDepot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepotServiceServer).UpdateDepot(ctx, req.(*TradingAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DepotService_ServiceDesc is the grpc.ServiceDesc for DepotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DepotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.consorsbank.module.tapi.grpc.DepotService",
	HandlerType: (*DepotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateDepot",
			Handler:    _DepotService_UpdateDepot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamDepot",
			Handler:       _DepotService_StreamDepot_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "TradingAPI.proto",
}
